### ISSUE TITLE
[RSA] Decryption error on line 2418

### ISSUE THREAD

**Issue by cauliturtle** [phpseclib/phpseclib#1031]
Hi there

I am writing lines of code to decrypt `RSA/ECB/OAEPWithSHA256AndMGF1Padding` however I got "Decryption error on line 2418". 

Below is my implementation

```php
// reading private key
$mpk_store = file_get_contents($merchant_private_key);
openssl_pkcs12_read($mpk_store, $mpk, "");
$mpk_private_key = $mpk['pkey'];

// start decryption 
$rsa = new phpseclib\Crypt\RSA();
$rsa->setHash('sha256');
$rsa->setMGFHash('sha1');
$flag = $rsa->loadKey($mpk_private_key); // 
$key = $rsa->decrypt($encrypted_data);
```

Is there any things wrong?

Actually I am wondering below code is the same as It returns a binary key. 

```php
openssl_private_decrypt($encrypted_data, $decrypted, $mpk_private_key, OPENSSL_NO_PADDING);
```

**Comment by cauliturtle** [comment]
I try another flags in `openssl_private_decrypt($encrypted_data, $decrypted, $pk_resource, OPENSSL_PKCS1_OAEP_PADDING);` 

It shows 

```bash
error:040A1079:rsa routines:RSA_padding_check_PKCS1_OAEP_mgf1:oaep decoding error
error:04065072:rsa routines:RSA_EAY_PRIVATE_DECRYPT:padding check failed
```

**Comment by terrafrost** [comment]
I apologize for the delay - I've been on an Alaskan cruise via Holland America and I've been trying to ration my internet since I was paying by the minute.

Anyway, it's hard to say much with the information that you've thus far provided. One possibility: the PKCS12 private key is a DSA private key and not an RSA one. Without the pkcs12 file I can't rule this out as a possibility.

So what'd really help is if you give me a PKCS12 (*.pfx or *.p12) file and a ciphertext that reproduces the problem.

**Comment by cauliturtle** [comment]
Hi @terrafrost 

Really appreciate with your reply. Yes, I can send you the p12 file with the code. Is your email github_username@php.net?

**Comment by terrafrost** [comment]
Yah - terrafrost@php.net . Thanks!

**Comment by terrafrost** [comment]
I apologize for the delay. Anyway, try setting the MGF1 hash to sha256 as well.

Altho Java isn't mentioned in this post it is mentioned in the email correspondence and I think some of the confusion is due to the meaning of RSA/ECB/OAEPWITHSHA-256ANDMGF1PADDING. With Sun's built-in cryptography provider that sha1 is the MGF hash whereas with BouncyCastle sha256 is the MGF hash. In both cases the main hash is sha256 but the MGF hash differs.
