### ISSUE TITLE
StrictHostKeyChecking Option

### ISSUE THREAD

**Issue by lukepolo** [phpseclib/phpseclib#1032]
Is it possible to use StrictHostKeyChecking when sshing into the system ?

**Comment by bantu** [comment]
Maybe https://github.com/phpseclib/phpseclib/issues/404 has some pointers
for how you can achieve that.

**Comment by bantu** [comment]
@lukepolo Here is a somewhat longer answer: I am afraid you have to get the public host key from the SSH2 object yourself (there should be a method for that) and see whether it matches the expected (e.g. a potentially previously stored) host key. If you need support for a solution involving a known_hosts file, you could probably sponsor #404.

**Comment by lukepolo** [comment]
Ill look at what I can do this weekend

**Comment by terrafrost** [comment]
There is `getServerPublicHostKey()`. It's always a good idea to do it but I always omit it in the examples for brevity. But this isn't something phpseclib can really do on it's own since it doesn't know anything about the system it's running on. Like maybe you'd want to store the public host keys in a database but phpseclib wouldn't have any way of knowing about DB's.

**Comment by bantu** [comment]
@lukepolo Any update on this? I think this can be closed in favour of #404.

**Comment by lukepolo** [comment]
Yes this can be closed.
