### ISSUE TITLE
How do you replicate mcrypt_decrypt with Blowfish?

### ISSUE THREAD

**Issue by JRawly** [phpseclib/phpseclib#1088]
Working code:

`echo mcrypt_decrypt("blowfish", $key, $encryptedText, "cbc", $iv);`

This appropriately echoes the decrypted data

When I try to convert this to use Blowfish... I'm not getting anything.
I assume I am missing something, but I don't know what.

```
//Autoloader is used and use statement at top of file is in place

$crypt = new Blowfish(); //cbc mode is default
$crypt->setKey($key);
$crypt->setIV($iv);

echo $crypt->decrypt($encryptedText);
```

This does not echo anything.

What am I missing? Any help would be appreciated.

Joe

**Comment by terrafrost** [comment]
It'd help if you posted some sample text that demonstrated the problem but in lieu of that...

**Short Answer**
Try `$crypt->disablePadding()`.

**Long Answer**
phpseclib, by default, uses PKCS1 padding. Blowfish has a block size of 64 bits or 8 bytes. So let's say your plaintext was 15 bytes. That's not a multiple of the block size so phpseclib will add `chr(1)` to the end of the plaintext to pad it to 16 bytes. If you're short by two bytes it'll null pad `chr(2)` twice, etc.

If the ciphertext /is/ a multiple of the blocksize `chr(8)` will be added eight times.

So what happens if, after you've decrypted the ciphertext, the last byte is, say, chr(99)? At that point it's obvious that PKCS1 padding isn't being used so phpseclib returns false.

mcrypt does not do PKCS1 padding / unpadding. It pads by adding null bytes and then removing trailing null bytes.

**Comment by JRawly** [comment]
Hey, 

I was just writing up a sample for you (I did mean to include one when opening), but the disablePadding works excellently! Thank you!

Much appreciated @terrafrost 

Joe
