### ISSUE TITLE
How to speed up SFTP login time

### ISSUE THREAD

**Issue by kherP** [phpseclib/phpseclib#1098]
Currently the SFTP takes around 6 seconds to log in. I tried SFTP key-pairing and thought the time taken to log in will be shortened but turned out it took more than 6 seconds to log in. Is there anything I can configure to speed up the login time?

**Comment by bantu** [comment]
Do you have the GMP extension installed?

**Comment by kherP** [comment]
Hi bantu,

I'm quite new to SFTP. Do you mind telling how GMP extension can help in boosting the login time?

**Comment by bantu** [comment]
AFAIK the connection is only established on login. GMP should speed up SSH
key agreement.

On 20 Feb 2017 07:50, "kherP" <notifications@github.com> wrote:

Hi bantu,

I'm quite new to SFTP. Do you mind telling how GMP extension can help in
boosting the login time?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/phpseclib/phpseclib/issues/1098#issuecomment-281001103>,
or mute the thread

**Comment by terrafrost** [comment]
SSH negotiates the symmetric key via diffie-hellman key exchange, which involves modular exponentiation, among other things. With BigInteger's internal implementation that can be quite slow. Also, if you're doing RSA authentication that can slow things down as well depending on how big your key is. If you're gonna use a 1MB key vs a 1KB key (for example) that's gonna slow things down a ton.

To know whether or not you have gmp installed I guess post a copy of your phpinfo()

**Comment by kherP** [comment]
Hi bantu and terrafrost,

GMP extension boosts the login time dramatically! Thank you very much!
