### ISSUE TITLE
Not able to download file with size more than 100mb

### ISSUE THREAD

**Issue by kherP** [phpseclib/phpseclib#1099]
I tried to download file with size 102MB. The page loads for awhile and it shows File Not Found but my download function will only be triggered if the file exists ( $sftp->file_exists( $file ) ). Is there any file size limitation for using phpseclib to download the file? Or where can I configure the limit so I can download file more than 100MB?

**Comment by terrafrost** [comment]
There's no hard limit. One possibility: the script is just timing out. You could try doing [set_time_limit(0);](http://php.net/set-time-limit) to account for that possibility.

If that doesn't help then a few other things that might - maybe try looking at the errors. eg. `print_r($sftp->getErrors())`.

If that doesn't help then maybe provide me with the SSH logs. You can get them by doing `define('NET_SSH2_LOGGING', 2)` at the top of the file and then `$sftp->getLog()` after.

**Comment by kherP** [comment]
Hi terrafrost,

Here's the error and logs. The error shown is unreadable as shown as below:

> Array ( [0] => SSH_MSG_GLOBAL_REQUEST: hostkeys-00@openssh.comssh-rsa¼g IüQH×9>ß]³ž“Ñ.:üõŠa»gÄ…QÝjés@‚‡ ¶ñàò²NlÌ;<ú ëÜ¤aÊ- Ò»¤suÀW°¾ŸHVëÅšµ©réÿD©‹®Õ]ûè˜øúøòf%np¸÷ÉQjÿ‹±¿+Ï|fz$@ÿ0ìŒBÞÁQ?¤‡ú¥³´ÍF’Nœl ¯¤ˆ2ðÕ37Ð÷Ã4ÖÕ<;©%î­ÅøN€„…`(ÜÞ‰BÑÅðuºãêÔû85#ÍÄ<’èP„ŠEÑÚ54<°ß”¨ÜsÝ?/Ô˜áã;Ä Îb-S2Üqaœ>—³ssh-dss÷ÚKhÍ>Ø™Õ@ \Åö«C:GŽvŒè¢\Ý¯×F<ísA-Â8MŒóµ–On9T|š¤ÑDë5›ãÅá¿ÞŽáÐ.J%?½k [Rë!æÉRud­úyµÃc£Ê=ö®–·¨Fm•ÎDPò‰0’y{åƒÉjBRû|üìTyÞÿöiÎ]‚®¼ )¸%3¤š ‹üýŸNñ¥‡ÚW÷!ªÂ0O’uŒÓ8ÿ˜°“_]ƒõ¡i–>é3M…ú¯5 é`HõêmX!_*(t(ÂKr4‰aÔˆÄ/k¹Beã¸‡ŒDO”ám7N‚”Þ¶ïmò}(e*õáËšzï?H[ÿÁ:K°ZÅœeÄyðå#ÌŠ›å¯ß¨›Ýa™!ÌØ@¹ý)Vþ¤IQ7+è_­CÔÒQƒÓgª‘ƒØÞâÜbèZL ù $†Ãã¬ìš'ù¯k¬Zhecdsa-sha2-nistp256nistp256A—,†P¦jYèoZñ3Îñ1z{{éøÎ‘.G—?!:|Y¤Za.gÈ¸?†Ó§[Ì$ÝàøÄk·Æ3ssh-ed25519 ÿ?ÙÌG*”ÛâV6ý.Yúˆ’Ùß‰Ä£jšöC ) 

The log of ssh2:
[ssh2log.txt](https://github.com/phpseclib/phpseclib/files/802705/ssh2log.txt)

**Comment by kherP** [comment]
Hi terrafrost,

Here's the error and logs. The error shown is unreadable as shown as below:

> Array ( [0] => SSH_MSG_GLOBAL_REQUEST: hostkeys-00@openssh.comssh-rsa¼g IüQH×9>ß]³ž“Ñ.:üõŠa»gÄ…QÝjés@‚‡ ¶ñàò²NlÌ;<ú ëÜ¤aÊ- Ò»¤suÀW°¾ŸHVëÅšµ©réÿD©‹®Õ]ûè˜øúøòf%np¸÷ÉQjÿ‹±¿+Ï|fz$@ÿ0ìŒBÞÁQ?¤‡ú¥³´ÍF’Nœl ¯¤ˆ2ðÕ37Ð÷Ã4ÖÕ<;©%î­ÅøN€„…`(ÜÞ‰BÑÅðuºãêÔû85#ÍÄ<’èP„ŠEÑÚ54<°ß”¨ÜsÝ?/Ô˜áã;Ä Îb-S2Üqaœ>—³ssh-dss÷ÚKhÍ>Ø™Õ@ \Åö«C:GŽvŒè¢\Ý¯×F<ísA-Â8MŒóµ–On9T|š¤ÑDë5›ãÅá¿ÞŽáÐ.J%?½k [Rë!æÉRud­úyµÃc£Ê=ö®–·¨Fm•ÎDPò‰0’y{åƒÉjBRû|üìTyÞÿöiÎ]‚®¼ )¸%3¤š ‹üýŸNñ¥‡ÚW÷!ªÂ0O’uŒÓ8ÿ˜°“_]ƒõ¡i–>é3M…ú¯5 é`HõêmX!_*(t(ÂKr4‰aÔˆÄ/k¹Beã¸‡ŒDO”ám7N‚”Þ¶ïmò}(e*õáËšzï?H[ÿÁ:K°ZÅœeÄyðå#ÌŠ›å¯ß¨›Ýa™!ÌØ@¹ý)Vþ¤IQ7+è_­CÔÒQƒÓgª‘ƒØÞâÜbèZL ù $†Ãã¬ìš'ù¯k¬Zhecdsa-sha2-nistp256nistp256A—,†P¦jYèoZñ3Îñ1z{{éøÎ‘.G—?!:|Y¤Za.gÈ¸?†Ó§[Ì$ÝàøÄk·Æ3ssh-ed25519 ÿ?ÙÌG*”ÛâV6ý.Yúˆ’Ùß‰Ä£jšöC ) 

The log of ssh2:
[ssh2log.txt](https://github.com/phpseclib/phpseclib/files/805395/ssh2log.txt)

**Comment by terrafrost** [comment]
ssh2log.txt is a bit mangled. It looks like you copy / pasted the output from a webpage and that the output wasn't encapsulated with `<pre>` tags? Because of this not only are the new lines squashed into a space - so are consecutive spaces.

I just made a commit that should make this less of an issue for detailed logs:

https://github.com/phpseclib/phpseclib/commit/8abc0ee60ca4f72f58a9d8de182ef6a744cb6ec9

Anyway, in cleaning up your logs somewhat...

```
000006b0 00:1c:65:00:00:00:01:00:00:00:01:00:00:00:0b:45 ..e............E
000006c0 6e:64:20:6f:66:20:66:69:6c:65:00:00:00:00:00:00 nd of file......
000006d0 00:1c:65:00:00:00:01:00:00:00:01:00:00:00:0b:45 ..e............E
000006e0 6e:64:20:6f:66:20:66:69:6c:65:00:00:00:00:00:00 nd of file......
000006f0 00:1c:65:00:00:00:01:00:00:00:01:00:00:00:0b:45 ..e............E
00000700 6e:64:20:6f:66:20:66:69:6c:65:00:00:00:00:00:00 nd of file......
00000710 00:1c:65:00:00:00:01:00:00:00:01:00:00:00:0b:45 ..e............E
00000720 6e:64:20:6f:66:20:66:69:6c:65:00:00:00:00:00:00 nd of file......
00000730 00:1c:65:00:00:00:01:00:00:00:01:00:00:00:0b:45 ..e............E
00000740 6e:64:20:6f:66:20:66:69:6c:65:00:00:00:00       nd of file....

-> NET_SSH2_MSG_CHANNEL_DATA (since last: 0, network: 0s)
00000000 00:00:00:00:00:00:00:11:00:00:00:0d:04:00:00:00 ................
00000010 01:00:00:00:04:00:00:00:00                      .........

<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0312, network: 0.0312s)
00000000 00:00:01:00:00:00:00:1c:00:00:00:18:65:00:00:00 ............e...
00000010 01:00:00:00:00:00:00:00:07:53:75:63:63:65:73:7p .........Success
00000020 00:00:00:00                                     ....
```

So it looks like phpseclib is getting to the end of the file and then closing the file.

idk what version you're using but you're using at least 1.0.4 or 2.0.4 because #945 is being used.

Here's the last outbound SSH_FXP_READ packet phpseclib sends out:

```
-> NET_SSH2_MSG_CHANNEL_DATA (since last: 0, network: 0s)
00000000 00:00:00:00:00:00:00:1d:00:00:00:19:05:00:00:00 ................
00000010 01:00:00:00:04:00:00:00:00:00:00:00:00:06:af:80 ................
00000020 00:00:00:80:00                                  ..... 
```

Here's the decoding of that:

```
SSH Data:
00:00:00:00 = channel
00:00:00:1d = data length
SFTP Data:
00:00:00:19 = length
05 = type (SSH_FXP_READ)
00:00:00:01 = id
00:00:00:04 = handle length
00:00:00:00 = handle
00:00:00:00:06:af:80:00 = offset
00:00:80:00 = len
```

06AF 8000 is 112,164,864 in decimal, which is about 100mb. The last few SFTP responses are SSH_FXP_STATUS with an error message of "End of file" so the downloaded file isn't that big but that's an upper bound on the size of the file. SSH_FXP_READ requests attempt to read in chunks of 32KB. It'd take some work to figure out exactly how many bytes phpseclib is reading of the file but, none-the-less, I think it's safe to assume that phpseclib is reading every byte of the file.

You say the page "shows File Not Found". What's showing that message? What's the trigger for that message to be shown? Say phpseclib is running on computer A and is downloading the file (if it exists) from computer B. Does "File Not Found" mean that the file is being written to computer A's filesystem and it's not being found on computer A? Is the error message implying that it's not being found on computer B? If the latter it's certainly not coming to that conclusion from phpseclib since phpseclib actually is reading the file (as demonstrated above)...

**Comment by kherP** [comment]
I use following code to trigger the download:

`if( $sftp->file_exists($file) )`
`{`
`    $sftp->max_sftp_packet;`
`     // headers for attachment or streamed file`
`     if ($is_attachment)`
`     {`
`         header('Content-Type: application/octet-stream');`
`         header("Content-Transfer-Encoding: Binary"); `
`         header("Content-disposition: attachment; filename=\"".$fn."\""); `
`         header('Expires:-1');`
`         header('Cache-Control: must-revalidate, post-check=0, pre-check=0');`
`         header('Pragma: public');`
`         header('Content-Length: ' . $sftp->size($file));`
`         header("Accept-Ranges: bytes");`
`    }`
`    $sftp->get($file);`
`  }`

For the last part, if I added echo before $sftp->get($file) , the file not found will be shown as shown in the figure below:
![fnf](https://cloud.githubusercontent.com/assets/12553063/23534218/52a9b34e-fff1-11e6-92f5-c93a3509646b.png)

If without the echo, the download can be started but the progress of download stuck at 4.7mb.

**Comment by terrafrost** [comment]
It's not completely clear to me what you're trying to do.

Are you using phpseclib to download a bunch of *.php files and then you're trying to access those files via a webbrowser and find yourself unable to do so because of an error 404? If so then 107mb is kinda seems kinda big for a *.php file...

The code snippet you posted has no code in it to produce error 404 response codes, either, so it's not clear to me how you're actually getting an error 404. Normally I'd think that maybe the file just didn't exist at the URL you thought it did but then you say that when you do `echo $sftp->get($file)` instead of simply `$sftp->get($file)` you get data but just 4.7mb...

So, like I said, there's a lot about your situation that is unclear to me. Were the log files from when you were doing the echo or when you weren't? If the latter then I guess try posting the log file again, but this time, do so with `<pre>` encapsulating the output.

**Comment by kherP** [comment]
I just wanted to download the file. The script I used is exactly the same as the one I used to download file less than 100MB. The script works fine for file less than 100MB. 

I am using phpseclib to download .zip, .pptx those kind of files. 

I have no idea how the error was hit either. Actually when I do `$sftp->get($file)`, then only I was able to get 4.7mb. I was not able to get anything if I include `echo`.

 I have attached the download script I use and the log file at the bottom of this comment to ease your investigation.

The log file are from without doing echo. If I include echo, it will return error 500.


[logfile.txt](https://github.com/phpseclib/phpseclib/files/820059/logfile.txt)
[download.txt](https://github.com/phpseclib/phpseclib/files/820062/download.txt)

**Comment by terrafrost** [comment]
```php
            else
            {
                header( 'Location: https://' . $_SERVER['HTTP_HOST'] . '/domain/pagenotfound' );
                exit;
            }
```

I guess that'd explain the error 404's...

From your latest log file...

```
-> NET_SSH2_MSG_CHANNEL_DATA (since last: 0, network: 0s)
00000000  00:00:00:00:00:00:00:1d:00:00:00:19:05:00:00:00  ................
00000010  01:00:00:00:04:00:00:00:00:00:00:00:00:06:af:80  ................
00000020  00:00:00:80:00                                   .....
```

That is the *exact* same packet I decoded a few days ago and as I elaborated in my last post this packet is requestng data 100mb into the file.

You say only 4.7mb is being downloaded when `echo` isn't used. How do you know that? Are you basing that on the output of `$sftp->size()`?

As for the echo...

I did a little expirement.

```php
<?php
$a = '<!-- ' . str_repeat('a', 1024 * 1024) . '-->';
echo number_format(memory_get_usage());
```

That outputs 1,666,224.

```php
<?php
$a = '<!-- ' . str_repeat('a', 1024 * 1024) . '-->';
echo $a;
echo number_format(memory_get_usage());
```

That outputs 2,710,928.

My guess...  you're running out of memory.

So two possibilities:

1. increase your memory limit. eg. `ini_set('memory_limit' '128M')`
2. download in chunks and output in chunks. eg.

```php
$size = $sftp->size($file);
for ($offset = 0; $offset < $size; $offset+= 1024*1024) {
	$sftp->get(file, false, $offset, 1024*1024);
}
```

**Comment by kherP** [comment]
I am now able to download the file larger than 100mb using the chunks method but the speed is quite slow. Where can I configure to speed the download up?

**Comment by kherP** [comment]
This solved my issue. Thanks for the help!
