### ISSUE TITLE
SFTP::put fails to transfer php://input resource

### ISSUE THREAD

**Issue by 1ma** [phpseclib/phpseclib#1119]
According to the SFTP::put() DocBlock, the $data argument can be a resource instead of an string. 

However the method uses [fstat](http://php.net/manual/en/function.fstat.php) to figure out the size of the payload, and this function fails when the resource is not an actual file descriptor (thus the whole point of using a resource is moot). A small script demonstrating this behavior:

```php
// demo/index.php

<?php

$fs1 = fstat(tmpfile());
// array[26]

$fs2 = fstat($body = fopen('php://input', 'r')); // raw body of HTTP request
// bool(false)

$sftp = new \phpseclib\Net\SFTP('testserver.local');
$sftp->login('username', 'password');

// /a/test is successfully created in the remote server, but it is always an empty file
$sftp->put('/a/test', $body);
```

### Other links
- Initial discussion regarding the feature: https://github.com/phpseclib/phpseclib/issues/428
- Culprit line (xdebugged): https://github.com/phpseclib/phpseclib/blob/2.0/phpseclib/Net/SFTP.php#L1933, but there's another one in SFTP::get(): https://github.com/phpseclib/phpseclib/blob/2.0/phpseclib/Net/SFTP.php#L2117. I guess it would fail under the same condition (i.e. trying to put the contents of a remote file into a `php://memory` stream, for instance)

**Comment by terrafrost** [comment]
This does not appear to be an issue with `php://memory`. In my testing `fstat` on `php://memory` returns an array whereas in the version of PHP I tested `php://input` on it returned a false. Maybe at the time the feature was implemented - against the version of PHP I was testing it against - it behaved differently. Test code:

```php
<?php
$fp = fopen('php://memory', 'w+');
fputs($fp, 'zzzzz');
var_dump(fstat($fp));
var_dump(stream_get_meta_data($fp));
rewind($fp);
echo fread($fp, 1024);
```

Due to the way it works, unit testing `php://input` is a little more difficult.

One thing that could probably be done is this:

```php
$body = fopen('php://memory', 'w+');
stream_copy_to_stream(fopen('php://input', 'r'), $body);
rewind($body);
```

phpseclib could probably do this itself. eg. do `stream_get_meta_data` and f wrapper_type (in the array that's returned) is "PHP" and stream_type is "Input" then it copies the stream to `php://memory` as demonstrated above.

**Comment by 1ma** [comment]
You are right, I jumped to a hasty conclusion. It's only `php://input` that returns false (and HTTP  resources à la `fopen('https://google.com', 'r')`, that's all I've found).

As it happens I am working with the Slim framework, and it's RequestBody class does [exactly this](https://github.com/slimphp/Slim/blob/3.x/Slim/Http/RequestBody.php) with the input stream, and it works just fine when I pass that copied resource to `SFTP::put()`. I agree, maybe phpseclib should know when its apropriate to do this itself.

PD mind that the `wrapper_type` of HTTP resources is `http`. Since I don't know all the wrapper_types that can be problematic, a better approach might be "try fstat, if it returns false then try stream_copy_to_stream".

**Comment by terrafrost** [comment]
> I believe a better approach might be "try fstat, if it fails then try stream_copy_to_stream and fstat again"

The problem I have with that is that `fstat(true)` returns false. It issues a PHP Warning but it also returns false. Similarly, `fstat(mcrypt_module_open('rijndael-128', '', 'cbc', ''))` returns false but it, too, returns a PHP Warning, albeit a different one.

**Comment by 1ma** [comment]
I don't follow. Looking at the code seems like `$fp` is guaranteed to be a resource at that point. OTOH I can't fathom why would anyone want to pass the output of `mcrypt_module_open` as the `$data` argument of `SFTP::put` :thinking: .

But then again this is the first time I peek at phpseclib code and you are its main author, so you sure see farther than I do.

**Comment by terrafrost** [comment]
> Looking at the code seems like `$fp` is guaranteed to be a resource at that point.

Yah - it looks like you're right lol.

> OTOH I can't fathom why would anyone want to pass an `mcrypt_module_open` resource as the `$data` argument of `SFTP::put`.

It's just an example lol. The main point being that idk all the conditions under which `fstat` can return false and I wouldn't want `stream_copy_to_stream` to error out because an invalid stream was passed to it.

Anyway, I'll try to make this update later today! It was requested that I do a release shortly as well so this'll probably be in the new release.

Thanks!

**Comment by terrafrost** [comment]
The proposed changes have been made!:

https://github.com/phpseclib/phpseclib/commit/35a1102c0b2854ae7903fb82ac68cadd23ba02f5

**Comment by 1ma** [comment]
Awesome :smile: Thank you, man.

**Comment by 1ma** [comment]
Sorry to be so insistent - but can you push yesterday releases to Packagist? :) Thanks again.

**Comment by bantu** [comment]
Packagist shows 1.0.6 and 2.0.5 for me.

**Comment by 1ma** [comment]
Now it does for me too.
