### ISSUE TITLE
Function mcrypt_list_algorithms() is deprecated

### ISSUE THREAD

**Issue by woyteck** [phpseclib/phpseclib#1134]
PHP 7.1 is yelling at me with this deprecation error at:
phpseclib/Crypt/Common/SymmetricKey.php:1711

PHP 7.1.5-1+deb.sury.org~trusty+2 (cli) (built: May 22 2017 13:39:01) ( NTS )

**Comment by terrafrost** [comment]
phpseclib has used the error suppression operator on all mcrypt function calls since 1.0.4 / 2.0.4:

https://github.com/phpseclib/phpseclib/commit/640f10609fdb2aa825f8a42c6bee975879974e1c

Those versions were released on October 3, 2016. My recommendation: upgrade to the latest version of phpseclib from either the 1.0 or 2.0 

Removing mcrypt is not going to happen because, deprecated tho it may be, it's still a heck of a lot faster than the pure-PHP implementation. The fact that it's being used on your system suggests that OpenSSL isn't available so mcrypt is gonna be the fastest way to do encryption in PHP.

**Comment by antonydandrea** [comment]
Glad to see it passes the tests. I actually looked a little deeper after I opened this and found that the code checks if mcrypt is available before attempting to use it which is ideal.

"The fact that it's being used on your system suggests that OpenSSL isn't available so mcrypt is gonna be the fastest way to do encryption in PHP", it actually suggests that our systems need updating as OpenSSL is available on 7.2 and mcrypt not hence why we started this.

I find it staggering that you would be so against removing a dead library in favour for one that is not dead.

**Comment by terrafrost** [comment]
@antonydandrea 

> I find it staggering that you would be so against removing a dead library in favour for one that is not dead.

What do we _gain_ by removing mcrypt support? Purists like you get their jolly's off because the output of a grep looks good. Yippee! That's about the only thing removing mcrypt gets us because, as I've already established, mcrypt doesn't yield any errors even on PHP 7.2.

I mean, shit, if I'm gonna be so concerned about purists I'd break BC in all branches and make phpseclib ONLY work on the latest version of PHP (currently 7.2).  If you're not using PHP 7.2 you're using PHP wrong and you need every incentive to upgrade, am I right?</sarcasm>

What do we _lose_ by removing mcrypt support? Speed. Because the alternative is a hell of a lot slower.

**Comment by antonydandrea** [comment]
It passes the tests because thankfully, there is code that first checks if it is installed before trying to use it. That then leads to the point that most people after PHP 7.2 will not have it installed and so these so called speed benefits will simply not be seen.

To be honest, my original post was before I knew that it was only used if installed so it is all good.

**Comment by tessus** [comment]
@terrafrost 

> Removing mcrypt is not going to happen because, deprecated tho it may be, it's still a heck of a lot faster than the pure-PHP implementation. 

Agreed. However, there are alternatives, e.g. libsodium.

> The fact that it's being used on your system suggests that OpenSSL isn't available so mcrypt is gonna be the fastest way to do encryption in PHP.

Does this mean, if I use the openssl php extension, mcrypt extension is neither required nor needed?
