### ISSUE TITLE
php7.2 not contatin mcrypt extension

### ISSUE THREAD

**Issue by bscheshirwork** [phpseclib/phpseclib#1148]
Because `mcrypt` is deprecated
```bash
error: /usr/src/php/ext/mcrypt does not exist
```
moved to PECL

**Comment by terrafrost** [comment]
Can you provide the code that gives you that error?

As is, phpseclib shouldn't be using mcrypt if the extension isn't loaded. Quoting https://github.com/phpseclib/phpseclib/blob/1.0.7/phpseclib/Crypt/Base.php#L1645

```
            case CRYPT_ENGINE_MCRYPT:
                return $this->cipher_name_mcrypt &&
                       extension_loaded('mcrypt') &&
                       in_array($this->cipher_name_mcrypt, @mcrypt_list_algorithms());
```

Note `extension_loaded('mcrypt')`

**Comment by terrafrost** [comment]
It doesn't look like Travis CI even supports PHP 7.2 yet:

https://travis-ci.org/terrafrost/phpseclib/jobs/253681004

**Comment by zoispag** [comment]
@terrafrost will it work for PHP 7.2, when mcrypt will be completely removed?

**Comment by terrafrost** [comment]
For the past few years, even with 5.6, finding systems with mcrypt even installed is rare. The PHP that apt-get installed on Ubuntu hasn't had it in years. At least not by default. So, to answer your question...  yes, it should work, because if running phpseclib _without_ mcrypt _didn't_ work we'd have heard about it by now.

**Comment by nishanth6** [comment]
## **Issue Solved when installing php7.2-mcrypt**
I was also facing the same issue. Check this link https://stackoverflow.com/q/48275494/7713811 to get the solution
