### ISSUE TITLE
report a bug about $ansi->getHistory()

### ISSUE THREAD

**Issue by luolufang** [phpseclib/phpseclib#1150]
these is the test code;
```
/**
 * Created by PhpStorm.
 * User: misaki
 * Date: 2017/7/16
 * Time: 13:12
 */
include ('File/ANSI.php');

$ansi = new File_ANSI();
$ansi->setHistory(3000);
$string=file_get_contents("./1.txt");

$ansi->loadString($string);

echo $ansi->getHistory(); // outputs HTML
```

(https://github.com/phpseclib/phpseclib/files/1150863/1.txt)

when the file 1.txt convert to html
some information will be lost

```
#
interface Ethernet0/0/45
 port link-type access
 port default vlan 137
 port-security enable
 port-security protect-action shutdown
 port-security aging-time 30
 port-isolate enable group 1
 broadcast-suppression 50
#
interface Ethernet0/0/46
-type access                               //lost information
 port default vlan 137
 port-security enable
 port-security protect-action shutdown
 port-security aging-time 30
 port-isolate enable group 1
 broadcast-suppression 50
#
interface Ethernet0/0/47
 port link-type access
 port default vlan 137
 port-security enable
 port-security protect-action shutdown
 port-security aging-time 30
 port-isolate enable group 1
 broadcast-suppression 50
#
interface Ethernet0/0/48
 port link-type access
 port default vlan 137
 port-security enable
 port-security protect-action shutdown
 port-security aging-time 30
 port-isolate enable group 1
-suppression 50                                                //lost information
#
interface GigabitEthernet0/0/1
#
interface GigabitEthernet0/0/2
```

**Comment by terrafrost** [comment]
The issue is with lines like this:

```
  ---- More ----[42D                                          [42D broadcast-suppression 50
```

The ANSI escape code corresponding to `\x1B[(\d+)D` is telling the terminal to move the cursor left n lines (where n is the subpattern captured by `\d+`). In this case it's telling the terminal to move the cursor left 42 lines but it's only 16 lines in so 16 - 42 = -26. It then adds 42 lines (in the form of spaces) and tells the cursor to, again, go back 42 lines., which brings us back to -26.

Anyway https://github.com/phpseclib/phpseclib/commit/84d1628cb7734134b1ba80545b38985025942b79 should fix this.

I could have done the `if ($this->x < 0) $this->x = 0` check right before `$this->tokenization[count($this->tokenization) - 1].= $source[$i];` but decided to put it where it's currently at since that's the main one that's gonna be making drastic changes to the x position. Everything else - if it even affects the x position at all - will affect it by just one line whereas this can take you back n lines.
