### ISSUE TITLE
Nodejs version?

### ISSUE THREAD

**Issue by anhgien** [phpseclib/phpseclib#1221]
Hello,
I'm working with third party api, they use your RSA encryption to secure information when exchanging data. But I'm using Nodejs for my backup, after a day search Nodejs RSA libs that  compatible with your RSA lib, I cannot found any of them.
And I lock forward to seeing nodejs version of the phpseclib.
Thank you.

**Comment by terrafrost** [comment]
phpseclib is PKCS1 v2.1 compliant. If a language didn't have any phpseclib compatible RSA implementations that would also mean it didn't have any PKCS1 compliant RSA implementations and if that's the case I'd say you just ought not do RSA in that language at all. That said, node.js is not such a language and it is def possible to get the two to interoperate together as evidenced by this:

https://stackoverflow.com/questions/tagged/phpseclib+node.js

I'd also say that stackoverflow is probably a better place to ask this question because there are node.js experts there. I've dabbled in node.js here and there but I am not an expert by any means.
