### ISSUE TITLE
PHP 7.1. Function mcrypt_list_algorithms() is deprecated.

### ISSUE THREAD

**Issue by andriykonoz** [phpseclib/phpseclib#1228]
**Lib version:** checked from 2.0.4  to 2.0.9.

**PHP version:**
PHP 7.1.7-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Jul  7 2017 09:41:45) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.7-1+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2017, by Zend Technologies
    with Xdebug v2.5.5, Copyright (c) 2002-2017, by Derick Rethans
**Code sample:**
`$client = new \phpseclib\Net\SFTP($host);`
`$client->login($login, $password);`
**OpenSSL is enabled.**
Class SSH2 firstly select  as engine for himself but after enabling of continuous buffer it discard previously selected engine and try to chose mcrypt as engine but get deprecated error. 

Similar problem was reported here #1134 

By some reason suppression of deprecated functions is not work.

All work fine if comment mcrypt engine validation. (vendor/phpseclib/phpseclib/phpseclib/Crypt/Base.php:1594)

What should be done for removing this error?

**Comment by terrafrost** [comment]
The fact that error suppression isn't working is a bit annoying. Might be related to something in your php.ini file idk.

In lieu of the fact that error suppression isn't working...  I suppose the `isValidEngine()` method could be updated to not allow mcrypt's use if you're on PHP 7.1+. The only problem I have with that is that mcrypt is _significantly_ faster than the pure PHP version, deprecated tho it may be.

Not using mcrypt when it's available for that reason would be akin to having $1,000,000 USD in one in hundred s but refusing to spend it because the hundred dollar bills are Series 2006 instead of Series 2009.

It's also just all the more weird because I'm pretty sure Travis CI tests mcrypt on PHP 7.1 / 7.2..

I'd say maybe post your php.ini file?

**Comment by andriykonoz** [comment]
Thank you for fast reply. Problem really somewhere in php.ini file. I tried to reproduce this problem in almost the same docker container at home, but not succeeded. There are no problems in container on home PC. I will post php.ini on Monday when I get to my PC on work.

**Comment by andriykonoz** [comment]
Today I rechecked all again. All works fine. Application has custom error handler that was printed this errors to the console. Along with it in custom lib, that is used by me, files with absolute file-path was silently not loaded.  
Since file was not loaded and errors was printed in console, I assumed that problem was in deprecated functions. But I was wrong.
I close this issue now, since there is no problem with your library.
