### ISSUE TITLE
unpack(): Type I: not enough input, need 4, have 0

### ISSUE THREAD

**Issue by YaBoiLewis** [phpseclib/phpseclib#1237]
`02.01 04:22:22 [Server] Server thread/CRITICAL ErrorException: "unpack(): Type I: not enough input, need 4, have 0" (EXCEPTION) in "VGCore/src/VGCore/sound/nbs/NBSParser" at line 144`

Line 144 : `return $this->info(unpack("I", $this->info(4))[1]);`

Method : info() -
`public function info($bin) {
        if ($bin < 0) {
            $this->offset = strlen($this->buff) - 1;
            return "";
        } else if ($bin === true) {
            return substr($this->buff, $this->offset);
        }
        return $bin === 1 ? $this->buff[$this->offset++] : substr($this->buff, ($this->offset += $bin) - $bin, $bin);
    }`

$this->buff : 
`$this->buff = fread($file, filesize($path));`

$this->offset : 
`$this->offset = strlen($this->buff) - 1;`

I don't believe I should be getting this error - correct me if I'm wrong.

**Comment by terrafrost** [comment]
phpseclib doesn't have a file named NBSParser or a VGCore directory...

**Comment by YaBoiLewis** [comment]
Hi @terrafrost - I know.

Those are my directories/file. What I'm telling you is that I'm getting an error with the `unpack()` method. phpseclib has that method.

**Comment by terrafrost** [comment]
So you posted this thinking that because phpseclib uses unpack without error that they might be able to provide you advice on how to fix the error you're encountering?

If so then it's really context dependent.

http://php.net/pack says, of I, that it's an "_unsigned integer (machine dependent size and byte order)_". The fact that it's size and byte order is variable is why I'd never use I in unpack. Maybe it's expecting four bytes, maybe it's expecting eight. It depends, I guess, on if your host machine is 32 or 64-bit.

In your code `$bin` is 4, which means that this is the code that'll get executed:

```php
substr($this->buff, ($this->offset += $bin) - $bin, $bin);
```

So what if `$this->buff` is `'abcdefgh'` and `$this->offset` is 6? At that point you'd have `substr('abcdefgh', (6 + 4) - 4, 4)` == `substr('abcdefgh', 6, 4)` == `'gh'`.

Maybe in a correctly formatted NBS file that should never happen but sometimes you'll be given improperly formatted stuff and the code still ought to fail gracefully in spite of it.

Anyway, this question would be much better asked on stackoverflow. There are lots of people who are qualified to answer this question - some even more qualified than myself. And I don't have 24/7 availability. I have to sleep, have to go to work, etc, but on stackoverflow it's a bunch of different people from all over the planet. And the phpseclib issue tracker is really best suited to phpseclib issues. If people are asking general PHP questions legit phpseclib issues may be missed or my responses to them delayed.
