### ISSUE TITLE
result of xor is not correct

### ISSUE THREAD

**Issue by jk2K** [phpseclib/phpseclib#1245]
for example
```php
// result: -1
echo 1 ^ -2;

// result: 3
$bigDataN1 = new BigInteger("-2");
echo (new BigInteger(1))->bitwise_xor($bigDataN1);
```

```php
// result: -6725760161961546967
echo -6725760161961546982 ^ 51;

// result: 6725760161961546965
echo (new BigInteger(-6725760161961546982))->bitwise_xor(new BigInteger(51));
```

**Comment by terrafrost** [comment]
The issue is your use of negative numbers.

Let's say you're using 4-bit signed integers. At that point -1 would be represented thusly:

1111

eg. *every* bit is 1. So -1 with 32-bit signed integers would have 32 "on" bits.

So how would that work with arbitrary precision integers? Using that approach you'd have an infinite number of 1's. ie. `BigInteger(-1)` would give you a "PHP Fatal error:  Allowed memory size of x bytes exhausted" every time.

In your first example you do `1 ^ -2`. -2 is represented in two's complimenet thusly:

1110

1 is represented thusly:

0001

1110 XOR 0001 is 1111 or -1.

In phpseclib -2 is represented the same way as 2:

10

1 is represented as 1.

01 XOR 10 is 11 or 3.

Now it does look like GMP mode is behaving differently. Currently phpseclib is just passing the two parameters to `gmp_xor` but `gmp_xor` returns a result that matches `$a ^ $b`.

I have an idea as to how this might be accomplished.

When you have a negative number assume it has as many leading 1's as the positive number has bits.

If both numbers are negative then you find the position of the most significant 0 digit of both and then pad both with 1's such that their length matches.

Pursuant to that we could also handle "not's" of negative numbers differently. eg. pad negative with x 1's and then do a "not" on that, assuming that the precision is equal to the new size of the number. And even if the number is a multiple of what you're padding to then you should still pad, as you would, with PKCS1. 

That said, I'm disinclined to implement this behavior in the 1.0 or 2.0 branches as it would be a BC break. If maintaining BC would mean that there would be instances in which Hash.php (which in some places uses BigInteger to do bitwise operations) would never be able to give the correct result I'd consider breaking BC then but otherwise I'm pretty disinclined to do so.

So for the 1.0 / 2.0 branch I'll fix the GMP discrepancy and I'll add this (changing the behavior of not and xor for BigInteger) to my list of things to do for the 3.0 branch.

**Comment by terrafrost** [comment]
I've updated the master branch to handle this differently than the 1.0 / 2.0 branches:

https://github.com/phpseclib/phpseclib/commit/75f51fc8cc84697f7a843c5beb3c169bb47a9bcc
https://github.com/phpseclib/phpseclib/commit/e0cbd3fe78af7d5029a3d9f56631e9731d1b7e3a
