### ISSUE TITLE
phpinfo() is called without checking whether the function is available

### ISSUE THREAD

**Issue by weshooper** [phpseclib/phpseclib#1255]
It's common for `phpinfo()` to be disabled in production.

It doesn't appear needed (https://github.com/phpseclib/phpseclib/commit/7a628c62b0071d03bde6be82c2f77acdadb20df2) but I assume that change is waiting for a major release.

Therefore, would something like the following be acceptable for a 2.0.11 release? If so I'll whip up a PR for `BigInteger.php`.and `RSA.php`:

```
if (false === strpos(ini_get('disable_functions'), 'phpinfo')) { // Often disabled in production systems
    @phpinfo();
}
```

**Comment by terrafrost** [comment]
> It doesn't appear needed (7a628c6) but I assume that change is waiting for a major release.

Correct. It'll be in the 3.0 release.

For the actual code changes...  I'd say all of this ought to be in the if statement:

```php
                    ob_start();
                    @phpinfo();
                    $content = ob_get_contents();
                    ob_end_clean();
                    preg_match_all('#OpenSSL (Header|Library) Version(.*)#im', $content, $matches);
```

Also, I wouldn't do the [yoda conditions](https://en.wikipedia.org/wiki/Yoda_conditions) because they're not done anywhere else in the code and doing them in one place but not in any other would be inconsistent and I think consistency trumps their benefits. ie. I'd just assume employ an "all or none" approach.

**Comment by weshooper** [comment]
Ok, thanks for your thoughts, I'll open a PR shortly.

**Comment by eternalharvest** [comment]
I'm not sure what is the difference between `$versions['Header']` and `$versions['Library']`.
But i wonder if we can use `OPENSSL_VERSION` constants instead...

Ref) http://php.net/manual/en/openssl.constversion.php

**Comment by terrafrost** [comment]
@weshooper - That wouldn't solve the issue that the phpinfo() check was aiming to solve. It's been years since the change was implemented but best guess: it was the following two links which were the impetus for the change:

https://stackoverflow.com/questions/16628102/php-openssl-openssl-private-encrypt-crashes-webpage/16636809#16636809
https://bugs.php.net/bug.php?id=55470&edit=3

**Comment by weshooper** [comment]
@terrafrost wasn't me heh! 😄 Closing the issue since fixed.

**Comment by eternalharvest** [comment]
Sorry It was my comment...

Thank u for the detailed information.
I read the code of openssl php module.

It seems `$versions['Library']` comes from `SSLeay_version(SSLEAY_VERSION)`.
And there is no exported php function to call `SSLeay_version`, and no defined constant values we need.

https://github.com/php/php-src/blob/master/ext/openssl/openssl.c#L1590-L1591

As @terrafrost  mentioned,  it seems that is a best way.
