### ISSUE TITLE
new \phpseclib\Math\BigInteger(48); toHex(true) return 00?

### ISSUE THREAD

**Issue by refear99** [phpseclib/phpseclib#1264]
```
        $bigint =new BigInteger(48);

        var_dump($bigint);
        var_dump($bigint->toHex());
        var_dump($bigint->toHex(true));
        var_dump($bigint->toString());
```

This return:

```
object(phpseclib\Math\BigInteger)#550 (2) {
  ["value"]=>
  string(4) "0x00"
  ["engine"]=>
  string(16) "bcmath (OpenSSL)"
}
string(2) "30"
string(2) "00" //Why ?
string(2) "48"
```

Only integer 48 have this issue.

Thanks

**Comment by terrafrost** [comment]
It's related to this old (fixed) bug from 2012:

https://pear.php.net/bugs/bug.php?id=19494

The problem is that it's doing `empty($var)` to see if it's empty. That test works if `$var` is `''` or `0` or `null`, etc, but when `$var` is `'0'` that breaks things.

idk if I can stay awake long enough to get the fix for this done tonight but we'll see.

Thanks!

**Comment by refear99** [comment]
@terrafrost 
Seems there is no good solution for now ?

So how we deal `48` to `0` ?

**Comment by terrafrost** [comment]
https://github.com/phpseclib/phpseclib/commit/c63c2239726754249f025dc022f23ab76c70df9a should fix this.

**Comment by refear99** [comment]
@terrafrost 

Thanks

When release a new version?

**Comment by terrafrost** [comment]
I'll try to do so this weekend. Maybe sooner, time permitting, we'll see.

**Comment by terrafrost** [comment]
1.0.11 has been released.

Thanks!
