### ISSUE TITLE
Connection closed by server

### ISSUE THREAD

**Issue by micaelpdias** [phpseclib/phpseclib#1266]
I'm getting a connection closed by server error. I've enable logs but it doesn't get far enough to actually log anything. 

The error is thrown here: https://github.com/phpseclib/phpseclib/blob/2.0/phpseclib/Net/SSH2.php#L1196

It works fine on my vagrant dev environment so it must be something server related. Are you able to help with what packages I should check for differences?

Environment error happens: Ubuntu 14.04.5 LTS (GNU/Linux 3.16.0-77-generic x86_64)
Vagrant environment: Ubuntu 14.04.5 LTS (GNU/Linux 3.13.0-100-generic x86_64)

**Comment by terrafrost** [comment]
You could remove some of the error suppression. Shouldn't matter for the fsockopen since, for that, the error is output when that returns false, but who knows. It could maybe be the `stream_select` too:

```php
if (!@stream_select($read, $write, $except, $sec, $usec) && !count($read)) {
```

It's also possible that you have [selinux installed](http://yml.com/fv-b-1-619/selinux--apache-httpd--php-establishing-socket-connections-using-fsockopen---et-al.html) but I'd think fsockopen would return an error for that.

There could also be some iptables issues going on. Or maybe you're trying to connect via a hostname and you have the hostname mapped weirdly in your /etc/hosts file. If you're using AWS there could be some additional firewall rules for the machine that the OS doesn't know about.

**Comment by micaelpdias** [comment]
This just started working without any changes, I'm assuming the server was blocking connections.
