### ISSUE TITLE
The wordfence alert

### ISSUE THREAD

**Issue by olegabr** [phpseclib/phpseclib#1303]
```
This file may contain malicious executable code: wp-content/plugins/ethereumwallet/vendor/phpseclib/phpseclib/phpseclib/Crypt/Base.php
Type: File
Issue Found October 18, 2018 3:20 am
Critical
IGNORE
DETAILS
Filename: wp-content/plugins/ethereumwallet/vendor/phpseclib/phpseclib/phpseclib/Crypt/Base.php
File Type: Not a core, theme, or plugin file from wordpress.org.
Details: This file is a PHP executable file and contains the word "eval" (without quotes) and the word "unpack(" (without quotes). The eval() function along with an encoding function like the one mentioned are commonly used by hackers to hide their code. If you know about this file you can choose to ignore it to exclude it from future scans. This file was detected because you have enabled HIGH SENSITIVITY scanning. This option is more aggressive than the usual scans, and may cause false positives.
```

Can you please comment on this issue? What can be done here? 
Thank you.

**Comment by terrafrost** [comment]
> Can you please comment on this issue?

See https://github.com/phpseclib/phpseclib/issues/1293#issuecomment-428428043

> What can be done here?

I'm not going to do anything about it. It's a false positive. Sure, getting these periodic bug reports is annoying but the speedup that phpseclib gets through the use of `eval` makes it worth while. If the speedup was 0.1% I'm not sure the hassle of posts like this would be worth it but the speedup is, in fact, closer to 20-60% and that's a speedup that's too great to ignore.

It's kinda like phpseclib's use of mcrypt. mcrypt has been deprecated but phpseclib will still use it if OpenSSL isn't available and mcrypt is. phpseclib has gotten flack for that but the speedup mcrypt offers (when under the right conditions) is just too great to ignore. And since, in the case of mcrypt, the error deprecation operator is used, pretty much all bug reports made about it's use stem from the use of static code analyzers and not people actually using the library.

**Comment by terrafrost** [comment]
> This file is a PHP executable file and contains the word "eval" (without quotes) and the word "unpack(" (without quotes).

The fact that it's warning about the use of `unpack` as well is ridiculous. `eval`, I kinda get. `eval` is not something people should use lightly and, if you're not careful, it can absolutely introduce serious vulnerabilities. But `unpack`? For dealing with binary data `unpack` is absolutely indispensable.
