### ISSUE TITLE
Why are EOLed PHP versions supported?

### ISSUE THREAD

**Issue by simPod** [phpseclib/phpseclib#1326]
I upgraded to v2.0 and noticed that `SSH2::read()` has a documentation `@return string` but returns also `false`.

So I was wondering that adding typehints would help much, checked https://github.com/phpseclib/phpseclib/blob/master/composer.json#L56 to see that EOLed php versions are supported. Shouldn't we drop support for old versions so we can increase code quality and reduce defects?

I'm eager to send PR if desired.

**Comment by terrafrost** [comment]
> I upgraded to v2.0 and noticed that `SSH2::read()` has a documentation `@return string` but returns also `false`.

Feel free to create a PR.

> Shouldn't we drop support for old versions so we can increase code quality and reduce defects?

phpseclib uses [semantic versioning](https://semver.org/). In semantic versioning the version format is best understood as [major].[minor].[patch]. Raising the minimum requirements, via composer.json, would be a major BC break. In order to accommodate it the next release of the 2.0 branch would need to be 3.0 and I'd just assume a new 3.0 version do more than just raise the minimum required version of PHP.

To be far, the composer.json you linked to was in the master branch. Work on that branch is ongoing and the API is unstable. The master branch will eventually become the 3.0 branch but you shouldn't assume that what's currently in that branch is what'll be in that branch when 3.0 is finally released.

That said, I'd just assume not bump the minimum required PHP version unless I'm fully taken advantage of all the features that PHP version has to offer, where applicable. So right now the master branch requires 5.6, minimum. This is chiefly because of all the files in the File/ASN1/Maps directory. Those files use arrays as constants and employee constant expressions. PHP didn't support this until 5.6 per http://php.net/manual/en/migration56.new-features.php .

I'd just assume not bump the minimum required version to 7.0 until scalar type declarations, strict typing and return type declarations were supported (all of which were introduced in 7.0). Same thing goes for 7.1 and 7.2, etc.

**Comment by simPod** [comment]
How can we add strict typing and all modern php features if the minimum required version doesn't support it? The moment you add eg. first return typehint, you have to bump the minimum required php version. The reverse order is a no go – cannot run on legacy php versions when using modern features thus cannot have legacy version as the minimum one.

BTW bumping minimum required PHP version is not a BC break. Thanks to package manager you won't get new version if requrements are not fullfiled and therefore the fatal error won't occur. BC break is when you change for example a method signature in a patch version that can result in fatal error.

**Comment by terrafrost** [comment]
> BTW bumping minimum required PHP version is not a BC break. Thanks to package manager you won't get new version if requrements are not fullfiled and therefore the fatal error won't occur.

The 1.0 and 2.0 versions are also LTS versions. If people can't trust me to keep my word w.r.t. LTS then why should anyone expect me to keep my word w.r.t. proper semver?

phpseclib, from it's inception, has been written for people who, for whatever reason, don't have much control over their system. Consider Math_BigInteger. GMP is the fastest possible math engine available and yet phpseclib doesn't require it. It uses it if it's available but it doesn't require it. Same thing for a lot of the symmetric ciphers. OpenSSL is a heckuva lot faster than the pure-PHP implementations and altho phpseclib uses OpenSSL if it's available it doesn't require it.

If I bump phpseclib's PHP requirements to PHP 7.2+ then maybe I should also drop support for environments without GMP or OpenSSL?

> How can we add strict typing and all modern php features if the minimum required version doesn't support it? The moment you add eg. first return typehint, you have to bump the minimum required php version. The reverse order is a no go – cannot run on legacy php versions when using modern features thus cannot have legacy version as the minimum one.

You do it in the same commit.

**Comment by simPod** [comment]
> The 1.0 and 2.0 versions are also LTS versions. If people can't trust me to keep my word w.r.t. LTS then why should anyone expect me to keep my word w.r.t. proper semver?

Keeping LTS and bumping PHP minimum version can simply go together. There would be one last release for EOLed PHPs and then the development would continue on top of it. Composer would not install new library versions on unsupported platforms thus there's no risk of breaking things. Long time support is kept as versions 1 and 2 still get updates while bumping PHP can also count as security and performance-boosting update ;)

> If I bump phpseclib's PHP requirements to PHP 7.2+ then maybe I should also drop support for environments without GMP or OpenSSL?

I don't see a reason for it, IMO it's not related at all 🤔 

------------------

I'm planning to open a pull request and from this conversation, I still cannot derive what's the attitude of this library towards using safe/supported PHP versions then.

> You do it in the same commit or PR.

Should I code the PR in the old way then or can I write clean code with types etc while bumping the php version?

------------------

> phpseclib, from it's inception, has been written for people who, for whatever reason, don't have much control over their system

Just saying thanks, we have 100% control over the system but using this lib as it gives 100% control over ssh usage. The php ssh-ext has too much limitied API for our use case.

**Comment by terrafrost** [comment]
> Keeping LTS and bumping PHP minimum version can simply go together. There would be one last release for EOLed PHPs and then the development would continue on top of it.

That would mean that bug fixes done after that last release wouldn't work on EOL PHP versions. You and I obviously have different interpretations of what LTS means but in my mind when I say a version has "long term support" what I mean by that is...  if someone is _still_ running PHP 5.6 I'll continue to provide support to them and if they find an issue in phpseclib I'll do all that I can to fix it, the fact that they're running an EOL version of PHP not withstanding.

> > If I bump phpseclib's PHP requirements to PHP 7.2+ then maybe I should also drop support for environments without GMP or OpenSSL?
>
> I don't see a reason for it, IMO it's not related at all 🤔

A lot of the reasons you're giving for dropping support for EOL PHP versions apply to dropping the pure-PHP implementations of stuff as well. As you correctly observe, newer PHP versions give a "performance-boosting update". GMP also gives a "performance-boosting update" as does libsodium and OpenSSL. And, tbh, they probably provide better security than the PHP versions, as well. So, like I said, the reasons you give for dropping EOL PHP versions are also reasons to drop support for environments that don't have GMP or OpenSSL or libsodium or whatever.

> Should I code the PR in the old way then or can I write clean code with types etc while bumping the php version?

You're referring to the "_I upgraded to v2.0 and noticed that `SSH2::read()` has a documentation `@return string` but returns also `false`_" issue your first post mentioned? If the "old way" is to maintain EOL PHP support then yah - doing it the old way is like a one line change so it's a super easy code review lol.

> The php ssh-ext has too much limitied API for our use case.

I agree. FWIW I've kinda come to think even phpseclib's API is pretty limited. I really do want to revamp it and greatly expand it. My original plan had been that phpseclib 3.0 would include a complete API revamp but after spending like a year and a half on [ECDSA / EdDSA support](https://github.com/phpseclib/phpseclib/pull/1322)...  I'm thinking now that phpseclib 3.0 will just upgraded algorithm support (some of which is necessitating some refactoring just to avoid excessive code duplication). My new (tentative) plan is for phpseclib 4.0 to feature a much more expanded SSH / SFTP API.

I think you'll really like phpseclib 4.0 but it's just soo far away atm :(

**Comment by simPod** [comment]
> If the "old way" is to maintain EOL PHP support then yah - doing it the old way is like a one line change so it's a super easy code review lol.

Yeah, like no types especially, talking about larger PRs than one line change tho. I always ask upfront so I don't spend time on something that will definitely not be merged afterwards.

> I think you'll really like phpseclib 4.0 but it's just soo far away atm :(

Do you have a brief idea how "soo far away"? Year, two or decade? Just so I can imagine a timeframe ;)

**Comment by terrafrost** [comment]
So here are the big things I have left that I want to do for 3.0:

- ECDH support (and a distinct DH API)
- ChaCha20 and Poly1305
- make public keys immutable. instead of doing `(new ECDSA)->load('...')` you'd do `ECDSA::load('...')`

Maybe compression, too, depending on how I feel. I have a number of tweaks I want to do as well:

- speed up GCM. Right now phpseclib, when not using the PHP 7.1+ OpenSSL bindings or libsodium, is 6x faster than https://github.com/Spomky-Labs/php-aes-gcm is under those same conditions (phpseclib can do 1mb in 10s; that lib does 1mb in 60s)
- rm SSH1.php and SCP.php
- rewrite the code so that Common/Functions/Objects.php can be removed
- implement a better fix for #1245 

After that I'll want to pretty much redo the documentation. Maybe hosted on https://pages.github.com/.

So I guess before work on 4.0 would commence all of that would need to be done. As for how long that'd take...  well GCM support got implemented a lot faster then I expected. I'm thinking (hoping) that now that a lot of the finite field / elliptic curve stuff has been implemented everything else should go much faster. The finite field work made GCM support go by a lot faster. If I hadn't done the finite field work for ECDSA I probably would have used the very subpar reduction algorithm given in the GCM specs instead of the one that I am using and things would be much slower.

Maybe another year for 3.0? Maybe less idk lol. 4.0...  hopefully that won't take as long as 3.0 has.

I think the 3.0 branch has taken as long as it has because mathematical algorithms are hard whereas API's are relatively easy.
