### ISSUE TITLE
Read timeout

### ISSUE THREAD

**Issue by pedropilla** [phpseclib/phpseclib#1327]
Hello, first I want to thank you for the awesome lib! I'm dealing with network devices and sometimes we have devices that paginates, I solved the paginate problem with a loop but now I'm struggling with read timeout.

My problem is in the last iteraction in the loop, when I keep looking for a string that will not occur anymore so I fall on the read timeout (30s?). There's any way that I can manage this read timeout? I tried the setTimeout function but without success.

Thats my code

    $ssh->setTimeout(1);
    $ssh->read('/OLT-.*#/', \phpseclib\Net\SSH2::READ_REGEX);
    $ssh->write("show gpon onu state gpon-olt_$port\n");
    $i = 0;
    $index[$i] = $ssh->read('--More--');
    if (strpos($index[$i], '--More--') !== false){
        $i++;
        $ssh->write("\n");
        $index[$i] = $ssh->read('--More--');
        while (strpos($index[$i], '--More--') !== false){
                    $i++;
                    $ssh->write("\n");
                    $index[$i] = $ssh->read('--More--');
        }    
    }

**Comment by terrafrost** [comment]
> I fall on the read timeout (30s?)
The timeout is, by default, 10s.

Anyway, I think it might actually help if you increase your timeout a bit. It seems possible that it's occasionally timing out before `--More--` is returned. eg. `--More--` would be returned if you had waited a little longer but you're not.

Also, idk if the network devices prompt is sufficiently unique to make distinguishing it from other output viable (or even if the network device even has a prompt?) but if so I'd look fro that instead of waiting for it to timeout when a prompt isn't found.

And personally, it seems like your code might benefit from being written with a do / while loop instead. eg.

```php
$i = -1;
do {
    $i++;
    if ($i) {
        $ssh->write("\n");
    }
    $index[$i] = $ssh->read('--More--');
} while (strpos($index[$i], '--More--') !== false);
```
Or something like that.

Beyond that I'm not sure how much help I can offer. It's not entirely clear what exactly the issue is. Is it timing out when it shouldn't be timing out? If so then my suggestion of increasing the timeout should help.

**Comment by geoffhouse** [comment]
I've had similar problems. In SSH2.php, line 3429 it uses stream_get_contents, but nowhere is a timeout set.
https://github.com/phpseclib/phpseclib/blob/41c76d6e0eff7a68785d0531783cb656ceefe89f/phpseclib/Net/SSH2.php#L3405
Adding a stream_set_timeout before that seems to help. Not sure why no-one else is having this problem though - maybe it's a particular problem with the SSH server I'm connecting to.

**Comment by pedropilla** [comment]
> > I fall on the read timeout (30s?)
> > The timeout is, by default, 10s.
> 
> Anyway, I think it might actually help if you increase your timeout a bit. It seems possible that it's occasionally timing out before `--More--` is returned. eg. `--More--` would be returned if you had waited a little longer but you're not.
> 
> Also, idk if the network devices prompt is sufficiently unique to make distinguishing it from other output viable (or even if the network device even has a prompt?) but if so I'd look fro that instead of waiting for it to timeout when a prompt isn't found.
> 
> And personally, it seems like your code might benefit from being written with a do / while loop instead. eg.
> 
> ```
> $i = -1;
> do {
>     $i++;
>     if ($i) {
>         $ssh->write("\n");
>     }
>     $index[$i] = $ssh->read('--More--');
> } while (strpos($index[$i], '--More--') !== false);
> ```
> 
> Or something like that.
> 
> Beyond that I'm not sure how much help I can offer. It's not entirely clear what exactly the issue is. Is it timing out when it shouldn't be timing out? If so then my suggestion of increasing the timeout should help.

Perfect, my mistake sorry.
