### ISSUE TITLE
TeamSpeak3 Server Host Key Algorithm Mismatch

### ISSUE THREAD

**Issue by Hanashi** [phpseclib/phpseclib#1336]
If I connect with phpseclib to TeamSpeak3 server query (SSH), it comes a php exception:
`Server Host Key Algorithm Mismatch in /home/dev/www/httpsdocs/ts3query/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php on line 1822`

The PHP code:
```
<?php
require __DIR__ . '/vendor/autoload.php';
use phpseclib\Net\SSH2;

$ssh = new SSH2('localhost', 10022);
if (!$ssh->login('serveradmin', 'password')) {
    exit("Login Failed\r\n");
}
```

But it works with libssh2:
```
<?php
$connection = ssh2_connect('localhost', '10022');
if (!$connection)
	die('Connection failed');

if (!ssh2_auth_password($connection, 'serveradmin', 'password'))
	die('Authentication Failed...');
```
Show this: https://gist.github.com/muenchow/61cbb225602bba78f952c0e5751d798e#file-teamspeak_ssh_query_example-php

I believe this is a bug in phpseclib.

**Comment by Hanashi** [comment]
Is fixed in master branch.

**Comment by terrafrost** [comment]
I'd actually say it's a bug in the SSH server lol. The problem is that the server is saying it supports rsa-sha2-256 signatures but is then sending an ssh-rsa signature (with sha1) instead, hence the error. https://github.com/phpseclib/phpseclib/issues/1331#issuecomment-455034026 elaborates on this more fully.

The fix should be in the latest git versions of the 1.0 and 2.0 branches, as well, and I'm planning on releasing a new version this weekend.

Thanks!
