### ISSUE TITLE
Sftp Login Slow

### ISSUE THREAD

**Issue by ismail0234** [phpseclib/phpseclib#1345]
PHP Version 7.2.15-1+ubuntu16.04.1+deb.sury.org+1

Php Properties...
**Thread Safety:** disabled
**OpenSSL:** OpenSSL/1.0.2g
**sodium:** libsodium library version | 1.0.17
**mcrypt:** Version: 2.5.8
**gmp:** Version: 6.1.0

Sftp login time: 2.6 second

My Code:
$sftp = new SFTP('ip');
if (!$sftp->login('login', 'password')) {
            exit('Login Failed');
}

debug file:
[login.txt](https://github.com/phpseclib/phpseclib/files/2902402/login.txt)

How can I do it faster?

**Comment by bantu** [comment]
Sounds indeed rather slow to me. My first guess would be slow DNS, but you
are indicating you are using an IP. What is the network between the two
hosts like?

**Comment by ismail0234** [comment]
> Sounds indeed rather slow to me. My first guess would be slow DNS, but you are indicating you are using an IP. What is the network between the two hosts like?

64 bytes from xx.xx.xxx.187: icmp_seq=1 ttl=53 time=172 ms
64 bytes from xx.xx.xxx.187: icmp_seq=2 ttl=53 time=171 ms
64 bytes from xx.xx.xxx.187: icmp_seq=3 ttl=53 time=172 ms
64 bytes from xx.xx.xxx.187: icmp_seq=4 ttl=53 time=171 ms
64 bytes from xx.xx.xxx.187: icmp_seq=5 ttl=53 time=171 ms
64 bytes from xx.xx.xxx.187: icmp_seq=6 ttl=53 time=172 ms
64 bytes from xx.xx.xxx.187: icmp_seq=7 ttl=53 time=172 ms
64 bytes from xx.xx.xxx.187: icmp_seq=8 ttl=53 time=172 ms
64 bytes from xx.xx.xxx.187: icmp_seq=9 ttl=53 time=172 ms

Two server connection time

**Comment by terrafrost** [comment]
Here are the incoming packets:

<-
<- NET_SSH2_MSG_KEXINIT (since last: 0.1844, network: 0.1844s)
<- NET_SSH2_MSG_KEXDH_REPLY (since last: 0.2244, network: 0.2244s)
<- NET_SSH2_MSG_NEWKEYS (since last: 0, network: 0s)
<- NET_SSH2_MSG_SERVICE_ACCEPT (since last: 0.4077, network: 0.4077s)
<- NET_SSH2_MSG_USERAUTH_SUCCESS (since last: 0.1961, network: 0.1961s)
<- NET_SSH2_MSG_GLOBAL_REQUEST (since last: 0.1865, network: 0s)
<- NET_SSH2_MSG_CHANNEL_OPEN_CONFIRMATION (since last: 0.1885, network: 0.1885s)
<- NET_SSH2_MSG_CHANNEL_WINDOW_ADJUST (since last: 0.1856, network: 0s)
<- NET_SSH2_MSG_CHANNEL_SUCCESS (since last: 0, network: 0s)
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.1856, network: 0s)
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.1861, network: 0s)

Total time: 1.9449s

Here are the outgoing packets:

->
-> NET_SSH2_MSG_KEXINIT (since last: 0.3795, network: 0s)
-> NET_SSH2_MSG_KEXDH_INIT (since last: 0.0015, network: 0s)
-> NET_SSH2_MSG_NEWKEYS (since last: 0.0005, network: 0s)
-> NET_SSH2_MSG_SERVICE_REQUEST (since last: 0.0002, network: 0s)
-> NET_SSH2_MSG_USERAUTH_REQUEST (since last: 0.0001, network: 0s)
-> NET_SSH2_MSG_CHANNEL_OPEN (since last: 0.0001, network: 0s)
-> NET_SSH2_MSG_REQUEST_FAILURE (since last: 0.0001, network: 0s)
-> NET_SSH2_MSG_CHANNEL_REQUEST (since last: 0.0001, network: 0s)
-> NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0001, network: 0s)
-> NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0001, network: 0s)

Total time: 0.3823s. 99% of that time is due to the initial NET_SSH2_MSG_KEXINIT packet and I think that packets slowness may be more due to slowness in the server identification string that the server sent instead of anything phpseclib is doing.

It looks to me that the problem is on the servers end. Sometimes you can have low latency but slow overall speed. Maybe that's the issue.

My expectation is that any SFTP / SSH2 client you try to use is going to be slow.

**Comment by ismail0234** [comment]
> Here are the incoming packets:
> 
> <-
> <- NET_SSH2_MSG_KEXINIT (since last: 0.1844, network: 0.1844s)
> <- NET_SSH2_MSG_KEXDH_REPLY (since last: 0.2244, network: 0.2244s)
> <- NET_SSH2_MSG_NEWKEYS (since last: 0, network: 0s)
> <- NET_SSH2_MSG_SERVICE_ACCEPT (since last: 0.4077, network: 0.4077s)
> <- NET_SSH2_MSG_USERAUTH_SUCCESS (since last: 0.1961, network: 0.1961s)
> <- NET_SSH2_MSG_GLOBAL_REQUEST (since last: 0.1865, network: 0s)
> <- NET_SSH2_MSG_CHANNEL_OPEN_CONFIRMATION (since last: 0.1885, network: 0.1885s)
> <- NET_SSH2_MSG_CHANNEL_WINDOW_ADJUST (since last: 0.1856, network: 0s)
> <- NET_SSH2_MSG_CHANNEL_SUCCESS (since last: 0, network: 0s)
> <- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.1856, network: 0s)
> <- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.1861, network: 0s)
> 
> Total time: 1.9449s
> 
> Here are the outgoing packets:
> 
> ->
> -> NET_SSH2_MSG_KEXINIT (since last: 0.3795, network: 0s)
> -> NET_SSH2_MSG_KEXDH_INIT (since last: 0.0015, network: 0s)
> -> NET_SSH2_MSG_NEWKEYS (since last: 0.0005, network: 0s)
> -> NET_SSH2_MSG_SERVICE_REQUEST (since last: 0.0002, network: 0s)
> -> NET_SSH2_MSG_USERAUTH_REQUEST (since last: 0.0001, network: 0s)
> -> NET_SSH2_MSG_CHANNEL_OPEN (since last: 0.0001, network: 0s)
> -> NET_SSH2_MSG_REQUEST_FAILURE (since last: 0.0001, network: 0s)
> -> NET_SSH2_MSG_CHANNEL_REQUEST (since last: 0.0001, network: 0s)
> -> NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0001, network: 0s)
> -> NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0001, network: 0s)
> 
> Total time: 0.3823s. 99% of that time is due to the initial NET_SSH2_MSG_KEXINIT packet and I think that packets slowness may be more due to slowness in the server identification string that the server sent instead of anything phpseclib is doing.
> 
> It looks to me that the problem is on the servers end. Sometimes you can have low latency but slow overall speed. Maybe that's the issue.
> 
> My expectation is that any SFTP / SSH2 client you try to use is going to be slow.

Is there anything I can do for that?

**Comment by bantu** [comment]
> Is there anything I can do for that?

I'd recommend you look into what terrafrost hinted at. That is, use another client (e.g. OpenSSH) to verify whether that is also "slow".

> My expectation is that any SFTP / SSH2 client you try to use is going to be slow
