### ISSUE TITLE
Specification RSA OAEP 

### ISSUE THREAD

**Issue by 69slimm** [phpseclib/phpseclib#1361]
I just ask some basic question because i dont know about RSA too much.

1. are public key and private key always random every i'm refresh the code ? if so how length the public key and private key is ?

sorry may this sounds ridiculous for you. Your answer will help me in the future. thank you

**Comment by terrafrost** [comment]
The keys don't change. They're constant. Ciphertext produced by OAEP encryption with the keys has randomized padding, which means that if you encrypt the same plaintext multiple times it'll be different but the keys, themselves, don't change.

Now, if you create _new_ keys every time the page is loaded, then at that point, the keys will be different. But at that point it seems like the use OAEP encryption of immaterial since you're presumably not encrypting but are instead generating keys. And the modulo length (which is what people generally refer to when referring to the length of an RSA key) remains the same. A 1024-bit modulo is typically produced by 2x 512-bit prime numbers (altho I guess, technically, you could do a 256-bit prime number and a 768-bit prime number; or you could be doing multi-prime RSA) and there are lots of 512-bit prime numbers. It's kinda like how there are a lot of even 3 decimal digit numbers: 100, 102, 104, ..., 998.

**Comment by 69slimm** [comment]
Aplogize first. actually i have a lot question. Please lead me on.
1. so what exactly public key and private key ? is 512 bits or 1024 bits ? where can i see the value of that keys ?
2. How length the ciphertext is ? is 2048 bits or 1024 bits ?
3. can u explain what happend on this function _raw_encrypt() ? i thought looks like this M^e mod N

sorry for many question

**Comment by 69slimm** [comment]
and can you show me The formula of padding in public and private key ?

**Comment by terrafrost** [comment]
A lot of your questions would probably be better directed to crypto.stackexchange.com or reddit.com/r/crypto.

Anyway...

1. In it's simplest form both the public key and private key contain the same modulo (n) and a different exponent (e or d). The modulo of a 1024-bit key is 1024-bits. The modulo, itself, is produced by multiplying 2x 512-bit prime numbers.
2. The ciphertext is less than the modulo. So 1024 bits or less when using a 1024-bit key (key with a 1024-bit modulo)
3. `_raw_encrypt` does textbook RSA. ie. the padding of PKCS1 and OAEP modes are not employed.

> and can you show me The formula of padding in public and private key ?

It's all described in the PKCS1 standard:

https://tools.ietf.org/html/rfc8017

Originally PKCS1 contained just one padding scheme that I call PKCS1 mode / padding. OAEP was added in a later version of the PKCS1 standard. With the introduction of OAEP mode / padding the PKCS1 standard now includes 2x padding schemes.

Wikipedia's description might be helpful as well:

https://en.wikipedia.org/wiki/Optimal_asymmetric_encryption_padding

**Comment by 69slimm** [comment]
ok i thought it outputs 2048 bit ciphertext.
one more. so you meaning padding in public and private keys has same padding that using on PKCS1 padding ?

**Comment by terrafrost** [comment]
> ok i thought it outputs 2048 bit ciphertext.

It depends on your key. As I said in my earlier post (without the emphasis), "So 1024 bits or less _when using a 1024-bit key (key with a 1024-bit modulo)_".

Are you using a key generated by phpseclib or by something else? phpseclib 1.0 and 2.0, by default, create 1024-bit keys:

https://github.com/phpseclib/phpseclib/blob/1.0/phpseclib/Crypt/RSA.php#L590
https://github.com/phpseclib/phpseclib/blob/2.0/phpseclib/Crypt/RSA.php#L538

phpseclib-master does 2048-bit keys. But puttygen, ssh-keygen, etc, each can have their own independent defaults.

> one more. so you meaning padding in public and private keys has same padding that using on PKCS1 padding ?

No. Keys don't have padding. Private keys can be encoded in any number of ways but the most common way to encode them is described here:

https://crypto.stackexchange.com/a/21104/4520

It has more parameters than just the modulo and the private exponent because real-world RSA makes use of the chinese remainder theorem to speed up calculations.

Public key have a simpler format:

https://stackoverflow.com/a/12750380/569976

**Comment by 69slimm** [comment]
> Are you using a key generated by phpseclib or by something else? phpseclib 1.0 and 2.0, by default
im using default phpseclib 2.0.

how do i create 2048 bit using this ?

**Comment by 69slimm** [comment]
everytime i want to using `$rsa->encrypt();` should i doing `extract($rsa->createKey()); and $rsa->loadKey();` ?

**Comment by terrafrost** [comment]
To create a 2048-bit key do the following:

```php
extract($rsa->createKey(2048));
```
This is described in the documentation:

http://phpseclib.sourceforge.net/rsa/examples.html

> everytime i want to using `$rsa->encrypt();` should i doing `extract($rsa->createKey()); and $rsa->loadKey();` ?

No. I would create the key once and then save it somewhere and then just reload it repeatedly. I'm not sure what the point of generating a new key and encrypting something with that new key would be if that new key was basically thrown away after the initial encryption. At that point no one would be able to decrypt the message, hence there wouldn't be a lot of point in even encrypting it...

**Comment by 69slimm** [comment]
> No. I would create the key once and then save it somewhere and then just reload it repeatedly. I'm not sure what the point of generating a new key and encrypting something with that new key would be if that new key was basically thrown away after the initial encryption. 

so this is what i will do :
`extract($rsa->createKey(2048));
and go straight to encryption:
$rsa->encrypt(); 
`
dont need `$rsa->loadKey();` ?

ok thanks so much sir. Honestly im working a final test for graduation and in my test i must using RSA and SHA-256 as the cryptography algorithm based on PHP. Maybe soon i will ask you some question, it'll be some flow-work function that you made on OAEP and SHA-256 if you don't mind. would you ?

**Comment by terrafrost** [comment]
> > No. I would create the key once and then save it somewhere and then just reload it repeatedly. I'm not sure what the point of generating a new key and encrypting something with that new key would be if that new key was basically thrown away after the initial encryption.
> 
> so this is what i will do :
> `extract($rsa->createKey(2048)); and go straight to encryption: $rsa->encrypt(); `
> dont need `$rsa->loadKey();` ?

If you do `extract($rsa->createKey(2048));` and you'd do `$publickey->encrypt(...)` afterwards. `$rsa->createKey(2048)` returns an array with `publickey` and `privatekey` as keys. `extract()` turns those array keys into variables.

**Comment by 69slimm** [comment]
ok thanks for the explanation sir. im gonna ask you soon again. i will not close yet this conversation

**Comment by 69slimm** [comment]
@terrafrost sir im back again.
can fill this variable `"$l"` on this function `_rsaes_oaep_encrypt($m, $l = '')` ?

**Comment by 69slimm** [comment]
why it must empty ?

**Comment by terrafrost** [comment]
> @terrafrost sir im back again.
> can fill this variable `"$l"` on this function `_rsaes_oaep_encrypt($m, $l = '')` ?

It is not currently possible. I actually just noticed that this weekend whilst working on some refactoring lol. Anyway, https://tools.ietf.org/html/rfc3447#page-17 elaborates as to what it does:

>    Both the encryption and the decryption operations of RSAES-OAEP take
   the value of a label L as input.  In this version of PKCS #1, L is
   the empty string; other uses of the label are outside the scope of
   this document.  See Appendix A.2.1 for the relevant ASN.1 syntax.

idk why I didn't make it so it could be set, as I did for stuff like the MGF Hash vs the regular hash or the salt length or whatever. Maybe it was intentional, maybe it wasn't, idk. As the RFC hints at, however, and as personal experience would seem to suggest, I have yet to encounter an actual instance where it's actually used.

I may add a setter for it in the 1.0 / 2.0 branches at some point but idk it's not a high priority.

**Comment by 69slimm** [comment]
ok just follow the Guidebook. I will not scientic myself about this algorithm

**Comment by 69slimm** [comment]
thanks for the respond sir

**Comment by 69slimm** [comment]
Hey sir. apologize first.
do you using CRT function on creating private key ?

**Comment by 69slimm** [comment]
im sorry i mean using CRT for decryption ?

**Comment by terrafrost** [comment]
If the private key has all the CRT parameters, then yah, it uses it.

**Comment by 69slimm** [comment]
`function _os2ip($x)
    {
        return new BigInteger($x, 256);
    }`
sir what the BigInteger doing in this case ? why does it taking 256 ?

**Comment by 69slimm** [comment]
`function _exponentiate($x)`
and this one, it using same function to encrypt and decrypt, which one to encrypt and which one to decrypt ?

**Comment by terrafrost** [comment]
> sir what the BigInteger doing in this case ? why does it taking 256 ?

By default BigInteger assumes numbers are in base-10 format so if the number is supposed to be in another base you need to tell it.

eg. "1000" in base-10 is 1000. "1000" in base-256 is 825241648. ie. it's `chr(49) . chr(48) . chr(48) . chr(48)` so you do `(49 << 24) | (48 << 16) | (48 << 8) | 48`. In base-16 it's 4096 (eg. `echo 0x1000`), etc.

> and this one, it using same function to encrypt and decrypt, which one to encrypt and which one to decrypt ?

I'm not sure I understand what you're asking. As you noted, it _is_ using the same function to encrypt and decrypt. The function, itself, uses the chinese remainder theorem (CRT) trick if the parameters are available but otherwise falls back to traditional modular exponentiation.

**Comment by 69slimm** [comment]
> By default BigInteger assumes numbers are in base-10 format so if the number is supposed to be in another base you need to tell it.
why it must using base-256 ?

> I'm not sure I understand what you're asking. As you noted, it is using the same function to encrypt and decrypt. The function, itself, uses the chinese remainder theorem (CRT) trick if the parameters are available but otherwise falls back to traditional modular exponentiation.
sorry wrong question, what i meaning which one is CRT step and which one is traditional modular exponentiation ? this is on my mind, correct me if im wrong :
this is traditional modular exponentiation
```
switch (true) {
            case empty($this->primes):
            case $this->primes[1]->equals($this->zero):
            case empty($this->coefficients):
            case $this->coefficients[2]->equals($this->zero):
            case empty($this->exponents):
            case $this->exponents[1]->equals($this->zero):
                return $x->modPow($this->exponent, $this->modulus);
        }
```

and this is CRT step : 
```
$num_primes = count($this->primes);

        if (defined('CRYPT_RSA_DISABLE_BLINDING')) {
            $m_i = array(
                1 => $x->modPow($this->exponents[1], $this->primes[1]),
                2 => $x->modPow($this->exponents[2], $this->primes[2])
            );
            $h = $m_i[1]->subtract($m_i[2]);
            $h = $h->multiply($this->coefficients[2]);
            list(, $h) = $h->divide($this->primes[1]);
            $m = $m_i[2]->add($h->multiply($this->primes[2]));

            $r = $this->primes[1];
            for ($i = 3; $i <= $num_primes; $i++) {
                $m_i = $x->modPow($this->exponents[$i], $this->primes[$i]);

                $r = $r->multiply($this->primes[$i - 1]);

                $h = $m_i->subtract($m);
                $h = $h->multiply($this->coefficients[$i]);
                list(, $h) = $h->divide($this->primes[$i]);

                $m = $m->add($r->multiply($h));
            }
        } else {
            $smallest = $this->primes[1];
            for ($i = 2; $i <= $num_primes; $i++) {
                if ($smallest->compare($this->primes[$i]) > 0) {
                    $smallest = $this->primes[$i];
                }
            }

            $one = new BigInteger(1);

            $r = $one->random($one, $smallest->subtract($one));

            $m_i = array(
                1 => $this->_blind($x, $r, 1),
                2 => $this->_blind($x, $r, 2)
            );
            $h = $m_i[1]->subtract($m_i[2]);
            $h = $h->multiply($this->coefficients[2]);
            list(, $h) = $h->divide($this->primes[1]);
            $m = $m_i[2]->add($h->multiply($this->primes[2]));

            $r = $this->primes[1];
            for ($i = 3; $i <= $num_primes; $i++) {
                $m_i = $this->_blind($x, $r, $i);

                $r = $r->multiply($this->primes[$i - 1]);

                $h = $m_i->subtract($m);
                $h = $h->multiply($this->coefficients[$i]);
                list(, $h) = $h->divide($this->primes[$i]);

                $m = $m->add($r->multiply($h));
            }
        }
```

**Comment by terrafrost** [comment]
> why it must using base-256 ?

It's the most compact way of representing stuff. It's also the most common way. SSH uses base-256 RSA signatures for example. If I stored them in base-10 or base-16 an extra step would need to be taken to convert it to the needed format.

It's also what pretty much all the key formats use.

> sorry wrong question, what i meaning which one is CRT step and which one is traditional modular exponentiation ? this is on my mind, correct me if im wrong

You correctly identified the traditional exponentiation and the CRT exponentiation.

**Comment by 69slimm** [comment]
So it depends on the keys, right ? If the one of the keys representing these variable: $primes, $exponents, $coefficients - and it'll be using CRT exponentiation

> You correctly identified the traditional exponentiation and the CRT exponentiation.

and in CRT step, what's the difference in after if() and after else{}

**Comment by terrafrost** [comment]
> So it depends on the keys, right ? If the one of the keys representing these variable: $primes, $exponents, $coefficients - and it'll be using CRT exponentiation

It has to have all three, but yes.

> and in CRT step, what's the difference in after if() and after else{}

If the condition is met blinding is employed. https://en.wikipedia.org/wiki/Blinding_(cryptography) talks more about that.

**Comment by 69slimm** [comment]
Sir maybe this is out of topic. Do you know how to do brute force attack ? My teacher told me to proof how strong the RSA OAEP that i used from you to count the time after encrypted and before encrypted

**Comment by terrafrost** [comment]
> Sir maybe this is out of topic. Do you know how to do brute force attack ? My teacher told me to proof how strong the RSA OAEP that i used from you to count the time after encrypted and before encrypted

I guess there's this:

https://security.stackexchange.com/a/32076/15922

https://tools.ietf.org/html/rfc8017#section-7.1 and https://en.wikipedia.org/wiki/Optimal_asymmetric_encryption_padding discuss the security properties of OAEP in more detail.

But for RSA there's also brute forcing the modulo. More specifically, trying to find, via brute force, the two numbers that were utilized to generate it. If you do that then you can find the decryption exponent trivially easily. I kinda suspect this is more of what your teacher was referring to but idk

**Comment by 69slimm** [comment]
Ok sir. One more question.
is your hash using hmac as default when setKey() is present ?

**Comment by 69slimm** [comment]
and in RSA createKey(), what's 4096 stand for ?
`define('CRYPT_RSA_SMALLEST_PRIME', 4096)`

**Comment by terrafrost** [comment]
Just saw your responses lol.

> is your hash using hmac as default when setKey() is present ?

No. The OAEP specs do not specify this so phpseclib doesn'.

> and in RSA createKey(), what's 4096 stand for ?

The comments elaborate:

```
// per <http://cseweb.ucsd.edu/~hovav/dist/survey.pdf#page=5>, this number ought not result in primes smaller
// than 256 bits. as a consequence if the key you're trying to create is 1024 bits and you've set CRYPT_RSA_SMALLEST_PRIME
// to 384 bits then you're going to get a 384 bit prime and a 640 bit prime (384 + 1024 % 384). at least if
// CRYPT_RSA_MODE is set to CRYPT_RSA_MODE_INTERNAL. if CRYPT_RSA_MODE is set to CRYPT_RSA_MODE_OPENSSL then
// CRYPT_RSA_SMALLEST_PRIME is ignored (ie. multi-prime RSA support is more intended as a way to speed up RSA key
// generation when there's a chance neither gmp nor OpenSSL are installed)
```
