### ISSUE TITLE
No response for rawlist

### ISSUE THREAD

**Issue by bartbergmans** [phpseclib/phpseclib#1364]
When I use the rawlist('dirname') function I occasionally get the following error:

`Expected SSH_FXP_NAME or SSH_FXP_STATUS in /var/www/x/vendor/phpseclib/phpseclib/phpseclib/Net/SFTP.php on line 993`

After this error the rawlist returns an empty array, when the directory isn't empty. What could be the cause of this? It has worked for a year without any problems and now I get this error a few times a day.

**Comment by terrafrost** [comment]
It's not immediately obvious which version of phpseclib you're using. You're not using 2.0.15, for example, because line 993 in SFTP.php doesn't throw an exception:

https://github.com/phpseclib/phpseclib/blob/11cf67cf78dc4acb18dc9149a57be4aee5036ce0/phpseclib/Net/SFTP.php#L990-L996

So knowing that would help.

Also, what'd really help are the SSH logs. You can get them by doing `define('NET_SSH2_LOGGING', 2)` and then `echo $ssh->getLog()` when `rawlist` returns an empty array.
