### ISSUE TITLE
PHP 7.3 PHP Deprecated: Function mcrypt_* is deprecated in vendor/phpseclib/phpseclib/phpseclib/Crypt/Base.php

### ISSUE THREAD

**Issue by sookoll** [phpseclib/phpseclib#1368]
After upgrading to 7.3 from 7.2 I got a lot of deprecation errors about mcrypt. I search and found out that mcrypt was removed from 7.2 already. But then why I got these errors now?

I'm using phpseclib for SFTP file transfer only. I also have OpenSSL support, so why phpseclib still using mcrypt? How to avoid these errors?

**Comment by terrafrost** [comment]
In all likelihood mcrypt is being used for arcfour256 or arcfour128, both of which are stream ciphers. Quoting https://github.com/phpseclib/phpseclib/issues/1028#issuecomment-242819768:

> OpenSSL doesn't operate in "continuous mode". So normally `encrypt($a)` done twice yields the same result. But in continuous mode you wouldn't want it to. In continuous mode you'd want `encrypt($a) . encrypt($a) == encrypt($a . $a)`. SSH operates in continuous mode and phpseclib emulates continuous mode with OpenSSL for block ciphers. But it can't emulate continuous mode for stream ciphers such as RC4, hence why mcrypt is used over OpenSSL in the case of SSH.

So since OpenSSL is off the table the only remaining options are to either use mcrypt or a pure-PHP implementation. If you're getting those errors than that means that mcrypt is available, deprecated tho it may be. And, deprecation not withstanding, mcrypt is still a ton faster than any pure-PHP implementation could ever hope to be. Quoting https://github.com/phpseclib/phpseclib/issues/1028#issuecomment-242739527:

> So mcrypt offers a 45x speedup over the internal mode. OpenSSL offers a 6.5x speedup over mcrypt.
>
> I could make it so that mcrypt isn't called, even if it's available, on PHP 7.1+, but then your cryptography would be much much slower. Which isn't to say that the pure-PHP implementation is slow - I submit that it's the fastest pure-PHP implementation out there and I think doing a megabyte of data in half a second is still pretty good but.... it can be a lot better. And if you're doing gigabytes of data it probably needs to be a lot better. But, still, the pure-PHP version is a lot slower. And, personally, I think a few E_DEPRECATED warnings is preferable to hit in speed that people in your shoes (who have mcrypt installed but not OpenSSL) would experience if I suppressed it on 7.1+.
Technically, that post is describing AES - not RC4 - but the same general idea applies.

phpseclib does use the [error suppression operator](https://www.php.net/manual/en/language.operators.errorcontrol.php) to hide the errors you're seeing but I guess you've got PHP setup in such a way that that operator is being ignored. Well either that or you're using an absolutely ancient version of phpseclib (phpseclib added the error suppression operator in 1.0.4 / 2.0.4, both of which were released on October 3, 2016).

**Comment by terrafrost** [comment]
That said, the master branch does not use arcfour256 / arcfour128 as it's most preferred algorithm:

https://github.com/phpseclib/phpseclib/blob/master/phpseclib/Net/SSH2.php#L4274

In the master branch it depends on how your environment is setup. If you have libsodium or OpenSSL on PHP > 7.1 it'll use AES GCM (provided the SSH server supports it). Then (if you have OpenSSL installed) it'll use aes-*-ctr preferentially (again, assuming the SSH server supports it). It'll preferentially use aes-*-ctr if neither OpenSSL or libsodium are available but mcrypt is and, if nothing is available and the only option is to use the pure-PHP implementations, it'll preferentially use chacha20-poly1305@openssh.com and, after that, arcfour128 / arcfour256.

All of this can be manually adjusted by the user as well.

The reason arcfour128 / arcfour256 is being used preferentially, all the time, with the 1.0 / 2.0 branches is because those branches are (1) prioritizing speed over anything else and (2) are only considering the algorithm when making that determination. ie. 1.0 / 2.0 are not taking the environment into consideration as the master branch is doing.

Maybe I could back port that code but, for the time being, I just want to get 3.0 out. Then, after that, maybe I'll consider backporting.
