### ISSUE TITLE
read returning duplicate data

### ISSUE THREAD

**Issue by bragle** [phpseclib/phpseclib#1384]
I had some issues with read returning the same data over and over, so I did some digging and figured out that the problem was the line introduced in 732bda2 (_get_channel_packet will close the channel if stream_select times out). I have set the timeout to one second, and I need it to be that short. Would it be possible to make closing channel on timeout optional? 😺

**Comment by terrafrost** [comment]
Thinking about it that feature makes the most sense when `exec()` is being used. If you're doing `read()` it makes less sense.

I updated the code so that it only auto disconnects when `exec()` is being used. idk which version of phpseclib you're using so I created branches for all the versions:

https://github.com/terrafrost/phpseclib/tree/update-auto-channel-close-1.0
https://github.com/terrafrost/phpseclib/tree/update-auto-channel-close-2.0
https://github.com/terrafrost/phpseclib/tree/update-auto-channel-close-master

Hopefully one of them will make it behave the way you're wanting?

LMK!

**Comment by bragle** [comment]
Yeah, that's perfect! Im using 2.0 as for now.

Also, would it be possible to add a parameter to the read function that'll let you instantaneously poll the status of the streams (0 timeout)?

I completely understand if you don't want to implement that, but it would be quite handy in my case 😸 

Amazing work you've done, by the way!

**Comment by terrafrost** [comment]
> Also, would it be possible to add a parameter to the read function that'll let you instantaneously poll the status of the streams (0 timeout)?
>
> I completely understand if you don't want to implement that, but it would be quite handy in my case 😸

I think that's something I'll probably table until v4.0. I want to do some big BC breaking changes to SSH2.php (and X509.php). Like with `exec()` I was thinking about making it return an object with `__toString()` as a magic method so you can still do `echo $ssh->exec('ls -latr')`. As an object you could then read x bytes at a time or whatever.

I could do the same thing with `read()` as well idk.

I elaborate on this idea here:

https://github.com/phpseclib/phpseclib/issues/1071#issuecomment-391596953

Anyway, I think I'll try to do a new release of 2.0 this evening to include this update.

Thanks!

**Comment by terrafrost** [comment]
The fix has been merged and a new release has been made.

Thanks!
