### ISSUE TITLE
How can I encrypt videos or pictures?

### ISSUE THREAD

**Issue by hcweb** [phpseclib/phpseclib#1414]
hi,How can I encrypt videos or pictures?

**Comment by terrafrost** [comment]
For pictures I'd recommend using libsodium. eg. `sodium_crypto_secretbox($plaintext, $nonce, $key)`.

For videos that's prob not gonna work as you'll need to encrypt the video in chunks due to it's memory prohibitive size. So for that I'd recommend you do this:

```
$c = new AES(AES::MODE_CTR);
$c->disablePadding();
$c->enableContinuousBuffer();
$c->setIV(Random::string(16));
$c->setKey(Random::string(16));

$h = hash_init('sha256', HASH_HMAC, Random::string(32));


$in = fopen('movie.ext', 'r');
$out = fopen('encrypted.ext', 'w');

while (!feof($in)) {
    $data = fread($in, 1024);
    $data = $c->encrypt($data);
    hash_update($h, $data);
    fwrite($out, $data);
}

fwrite($out, hash_final($h, true));
fclose($out);
fclose($in);
```
This implements an encrypt-then-mac (EtM) authenticated encryption and decryption scheme (AEAD) using AES-128-CBC and SHA-256.

To decrypt you just need to remember that the last 32 bytes are the HMAC and then verify that accordingly.

I recommend libsodium for the first one because phpseclib provides a bunch of very low level cryptographic primitives. There are multiple ways one can create an AEAD scheme with phpseclib (encrypt-then-mac, encrypt-and-mac, mac-then-encrypt) but some ways are better than others. libsodium combines both into a single cryptographic primitive. phpseclib doesn't do this because applications like SSH or CMS or whatever need more fine tuned control than libsodium offers. But for our purposes it should be more than sufficient. At least for the image.
