### ISSUE TITLE
undefined method Crypt_Blowfish::isValidEngine()

### ISSUE THREAD

**Issue by porter707** [phpseclib/phpseclib#1415]
Hi,

We have clients that are hosted with Strato hosting and are having issues with phpseclib version 1.0.17+, version 1.0.16 works.

Host: sftp.hidrive.strato.com
Port: 22

https://www.strato.com/faq/en_us/online-storage-hidrive/what-are-the-paths-for-ftp-smb-webdav-rsync-etc/

Attached is the log they are getting one warning and then a fatal error:

`0005.041 (0) PHP event: code E_WARNING: Use of undefined constant CRYPT_BLOWFISH_MODE_CTR - assumed 'CRYPT_BLOWFISH_MODE_CTR' (this will throw an Error in a future version of PHP) (line 2046, /vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php)
0005.046 (0) PHP Fatal error (Error) has occurred during backup uploads to the sftp. Error Message: Call to undefined method Crypt_Blowfish::isValidEngine() (Code: 0, line 4618 in /vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php)`

I've confirmed that the blowfish file does exist and that the isValidEngine() function is in that file.

I don't have direct access to the site or the SFTP credentials but I have someone willing to help with debuggin so if theres any further information needed to help debug this I can get that for you.

**Comment by terrafrost** [comment]
Do you have PEAR installed? Per chance do you have PEAR's Crypt_Blowfish installed? 'cause there's kinda a conflict between that and phpseclib per #125. If this hypothesis is correct then your options are as follows:

- use phpseclib 2.0
- disable blowfish on phpseclib's end. ie. before you call `->login(...)` do this:
  ```php
  $a = $sftp->getSupportedEncryptionAlgorithms();
  $a = array_filter($a, function($val) {
      return substr($val, 0, 8) != 'blowfish';
  });
  $sftp->setPreferredAlgorithms([
      'client_to_server' => ['crypt' => $a],
      'server_to_client' => ['crypt' => $a],
  ]);
  ```
- delete PEAR's Crypt_Blowfish
- explicitly include phpseclib's Crypt_Blowfish before phpseclib attempts to

I suppose I could do a `method_exists` check in phpseclib 1.0, when attempting to auto-include Crypt_Blowfish, to see if the class that's loade has a `isValidEngine` method defined and, if not, issue a `user_error` and if so then exclude blowfish from the cipher suite that Net_SSH2 supports. I guess I'll hold off on this for now to see how widespread a problem this is.

Assuming this hypothesis is correct then the problem would have been introduced when I made it so that phpseclib picks it's preferred algorithm order based on the extensions available to phpseclib.

**Comment by porter707** [comment]
Hi, thanks for your reply. I've confirmed thaat PEAR is installed and that it was conflicting with their version of Crypt_Blowfish.

We've opted to explicitly include phpseclib's verson of Crypt_Blowfish and this resolves our issue.
