### ISSUE TITLE
new RSA() phpinfo throws an exception

### ISSUE THREAD

**Issue by nunoperalta** [phpseclib/phpseclib#1416]
I am having the problem described in #1400

However, I don't have "mirasvit/module-profiler" installed, and adding:

`$_SERVER['MAGE_PROFILER_STAT'] = null;`

does not resolve the problem.

The phpinfo() dump is happening on this call:

`$rsa = new \phpseclib\Crypt\RSA();`

Happens only if invoked from CLI.

**Comment by nunoperalta** [comment]
Ok. I understand what is happening.

The problem is that if there's anything in the phpinfo() dump that is unusual, phpseclib will crash.

In this case, there's an object that is put in $_ENV, and phpinfo() is including it (possibly because INFO_ENVIRONMENT is set) and then crashes phpseclib.

Is there any reason phpinfo() must be called when creating a new RSA()?

**Comment by terrafrost** [comment]
> Is there any reason phpinfo() must be called when creating a new RSA()?

OpenSSL is (optionally) used by 1.0 / 2.0 when creating keys. In particular, it's possible to have PHP compiled against one version of OpenSSL and then linked against another version with BC breaking changes. When this happens phpseclib will crash. The `phpinfo()` check is done to protect against this crashing.

Of course, as this ticket and #1400 document, crashing can still occur, despite it.

phpseclib 3.0 doesn't even use OpenSSL to create keys. So you could use that. Or, if you want to use 1.0 / 2.0 you could do this (at the top):

    define('CRYPT_RSA_MODE', 1);

That'll make it so that the internal engine is used, which should bypass the `phpinfo()` calls.

**Comment by nunoperalta** [comment]
Thank you.
I wouldn't mind to use 3.0, but I see there's no release for it yet, so I assume that it is still in development.

I tried defining CRYPT_RSA_MODE, but that doesn't seem to have fixed the problem.

I also tried:

`define('CRYPT_RSA_MODE', \phpseclib\Crypt\RSA::MODE_INTERNAL);`

**Comment by nunoperalta** [comment]
Looking at the code, this is what needs to be defined:

	define('MATH_BIGINTEGER_OPENSSL_DISABLE', 1);
	define('CRYPT_RSA_MODE', \phpseclib\Crypt\RSA::MODE_INTERNAL);

**Comment by terrafrost** [comment]
{quote}
I wouldn't mind to use 3.0, but I see there's no release for it yet, so I assume that it is still in development.
{quote}
At this point I'd say that it is only in-so-far as 1.0 and 2.0 are under development. The API can now be assumed to be stable for 3.0. I wouldn't have created a 3.0 branch unless I was committed to that API for that version.

I'm holding off on tagging a 3.0.0 release because I want to do a documentation revamp prior to doing that. 3.0 changes how public keys, in particular, work, quite a bit. SSH2 / SFTP, in contrast, are relatively unchanged.
