### ISSUE TITLE
PHP7.3 At least one byte needs to be present for successful C / b decodes

### ISSUE THREAD

**Issue by simPod** [phpseclib/phpseclib#1426]
On PHP 7.3 the `At least one byte needs to be present for successful C / b decodes` is being thrown in some cases.

https://github.com/phpseclib/phpseclib/blob/master/phpseclib/Common/Functions/Strings.php#L92

It is not the case on PHP 7.2 with the same code. I suppose there's some incompatibility with the new php version.  
Should I provide more info and if so, what would it be?

**Comment by simPod** [comment]
I just went to investigate this with forked master but no longer see these. Lookin fixed, thx!

**Comment by terrafrost** [comment]
So this was a legit issue but a rare one. It occurred about 0.2% of the time (1/512). https://github.com/phpseclib/phpseclib/commit/61ffe1a147973947195bc1c8390b2fc8c50f2145 fixes it.

Thanks!

**Comment by illnesse** [comment]
i'm suddenly getting this error, failing logins and 

`LengthException: At least one byte needs to be present for successful C / b decodes in /home/seedit4me/seedit4.me/vendor/phpseclib/phpseclib/phpseclib/Common/Functions/Strings.php:92`

and 

`phpseclib3\Exception\UnableToConnectException: Cannot connect to x.x.x.x:22. Error 115. Operation now in progress in /home/seedit4me/seedit4.me/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php:1230
`
on 3.0.5, 3.0.6, and master

it has been working flawlessly, the only thing changed is the ssh jobs are executed via horizon now instead of standard laravel queue worker, same php cli version though..
