### ISSUE TITLE
Exception thrown in PHP < 7.2 with sodium_compat installed

### ISSUE THREAD

**Issue by njandreasson** [phpseclib/phpseclib#1432]
https://github.com/phpseclib/phpseclib/blob/c78eb5058d5bb1a183133c36d4ba5b6675dfa099/phpseclib/Net/SSH2.php#L1702
The method call to sodium_memzero() referenced above is typically provided by the libsodium extension.
libsodium was introduced in PHP 7.2 but for earlier versions there is a compat library available called https://github.com/paragonie/sodium_compat
The crux is that sodium_memzero() is not implemented in the compat library and will therefor throw an exception (https://github.com/paragonie/sodium_compat/blob/v1.12.1/src/Compat.php#L3210).

I stumbled upon this in an application running on  PHP 7.1.33 with latest versions of phpseclib/phpseclib 2.0.23 and paragonie/sodium_compat v1.12.1.

If I downgrade phpseclib/phpseclib to 2.0.21 everything works again which I suppose is due to the same algorithm is not being used (curve25519-sha256).

As a "fix" I would suggest to simply not call sodium_memzero() for PHP versions below 7.2, just call unset() instead. Or perhaps try calling sodium_memzero() but within a try {} and if SodiumException is caught, use unset() instead.

**Comment by terrafrost** [comment]
Technically, before PHP 7.2, libsodium could be installed via PECL. In https://github.com/phpseclib/docker-php I have libsodium working in versions of PHP as low as 5.6 but it can be installed, in theory, on PHP 5.4. So idk that checking the PHP version is the best. I've gone ahead and done `extension_loaded` instead. See https://github.com/phpseclib/phpseclib/commit/e3557220d7b4f10b4b8420ba71845e88b3b69c50

I'm not doing `unset()`, atm, since PHP's garbage collection should take care of that.

Thanks!

**Comment by njandreasson** [comment]
Ah, that's of course true!
Thanks for fixing, looks good!
