### ISSUE TITLE
php 7 compatibility: INI directive 'mbstring.func_overload' is deprecated since PHP 7.2

### ISSUE THREAD

**Issue by michabbb** [phpseclib/phpseclib#1457]
hi there,

is there a chance to handle this code

https://github.com/phpseclib/phpseclib/blob/master/phpseclib/bootstrap.php#L14

in a different way ? 🤔

**Comment by terrafrost** [comment]
Not sure how. Deprecation != removal so that setting could still be set and still interfere with phpseclib.

I guess we could do strlen("...") != 2 (or whatever) but then the question is what that magic string would be and what the expected length ought to be...

**Comment by michabbb** [comment]
to be honest, i have no idea what the code is doing here, i am currently testing external libraries and their compatibility to php 7.4. so i am using php_codesniffer with [PHPCompatibility](https://github.com/PHPCompatibility/PHPCompatibility). as long as `Deprecation != removal` applies, everything is fine, but i just wanted to mention this, because it´s only a matter of time, till this line of code won´t work any longer. so if you want to deal with it now or later, it´s up to you. i am sorry that i am not able to make any suggestions here at this point.

**Comment by terrafrost** [comment]
> to be honest, i have no idea what the code is doing here

phpseclib will break if `mbstring.func_overload` is used. Other packages work around this by doing an if statement and doing stuff like `mb_strlen(..., '8bit')` / `strlen()` depending on the `mbstring.func_overload` setting. eg:

https://github.com/paragonie/random_compat/blob/master/lib/byte_safe_strings.php#L47

phpseclib's solution is just not even work. All those if statements slow things down and rather than deal with that slow down or even legitimize this retarded feature phpseclib just refuses to work.

>  just wanted to mention this, because it´s only a matter of time, till this line of code won´t work any longer

I don't see how it's going to cause an issue.  If `ini_get('mbstring.func_overload')` isn't a valid ini setting it'll be treated just as `ini_get('zzz')` is. ie. it'll return false.  This behavior is more thoroughly discussed in the README.md file for bcmath_compat:

https://github.com/phpseclib/bcmath_compat/blob/master/README.md

Maybe a custom ruleset should be created for phpseclib just as one was created for the paragonie suite of libraries:

https://github.com/PHPCompatibility/PHPCompatibilityParagonie/pull/2

Anyway, in light of your most recent post, I'm going to close this issue. This is a false positive by a static analyzer. It is not an issue.

**Comment by terrafrost** [comment]
I mean, phpseclib is unit tested on Travis CI through PHP 7.4. Any E_DEPRECATED errors would result in failing unit tests, of which phpseclib has none. More than that, because it's bootstrap.php that this is in, if this would yield E_DEPRECATED errors, then _every_ test phpseclib has would fail.

**Comment by michabbb** [comment]
thanks for clarification 👍
