### ISSUE TITLE
Broken pipe in /vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php:3965 

### ISSUE THREAD

**Issue by ndobromirov** [phpseclib/phpseclib#1511]
Hello,

I am currently using the latest version - `2.0.28 `
Occasionally I am getting the following error logs on production.
```
PHP Fatal error:  Uncaught yii\base\ErrorException: fputs(): send of 64 bytes failed with errno=32 Broken pipe in /app/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php:3965
trace Stack trace:
info #0 [internal function]: yii\base\ErrorHandler->handleError(8, 'fputs(): send o...', '/vendor/php...', 3965, Array)
info #1 /vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(3965): fputs(Resource id #28881, '\xD1\xC2\xA9\x18\x93\xF0\xEE\x94\xCB7\xFB\xA4^\x8D\xE8...')
info #2 /vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(4155): phpseclib\Net\SSH2->_send_binary_packet('\x01\x00\x00\x00\v\x00\x00\x00\x00\x00\x00\x00\x00')
info #3 /vendor/phpseclib/phpseclib/phpseclib/Net/SFTP.php(3177): phpseclib\Net\SSH2->_disconnect(11)
info #4 /vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(3188): phpseclib\Net\SFTP->_disconnect(11)
info #5 /vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(3204): phpseclib\Net\SSH2->disconnect()
info #6 [internal function]: phpseclib\Net\SSH2->__destruct()
info #7 {main}
info   thrown in /vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php on line 3965
```

From what I can get of the timings, it is related to a long-running process that is creating an instance that is being destroyed in the end of the script.
The library is used to handle SFTP communication with a particular server. The functionality works as it should, when the SFTP connection is actively used, as there is a forced reconnect based on a time interval before doing SFTP relate work.
My suspicion is that as it's a long-running process, it does it's own ting, and the connection times out. All the resources on PHP side are still valid, but the network level connection is dead (as it was not used for the let's say last 3-4-5 hours).
This results in the error above once the script is terminated and attempts to close the connection safely.

As I've written this, it seems like a false-positive, but if there is a way to work-around it, so it does not trigger this errors around a critical infrastructure will be very nice :). 
As it is currently breaking with a fatal, this means that other `__destruct` operations that follow might be skipped.

Amy way to have a keep-alive packet set out, so the connection stays alive for as long as needed? 
Is there any socket timeouts that can cause this?
Any directions on how this should be configured?
What do you think of preemptive disconnects to avoid the connection's time-out?

**Comment by terrafrost** [comment]
> As it is currently breaking with a fatal, this means that other `__destruct` operations that follow might be skipped.

What's probably happening is that an error is being issued (as opposed to an exception) and that's being turned into an exception with a custom [error handler](https://www.php.net/manual/en/function.set-error-handler.php). So probably just prepending the error suppression operator (eg. `@fputs(...)`) would do the trick.

> Amy way to have a keep-alive packet set out, so the connection stays alive for as long as needed?

It kinda depends on what you're doing but since PHP is largely synchronous...  if you do something like `sleep(1000)` in your code that means that no phpseclib code is going to be running.

In Javascript that wouldn't be a huge issue 'cause you could do `setInterval(...)` so that even if one part of the program was stalled out keep-alive packets could still be sent out, but alas, phpseclib isn't written in javascript!

> Is there any socket timeouts that can cause this?

Maybe idk

> What do you think of preemptive disconnects to avoid the connection's time-out?

Yah that should work.

FWIW I will say that normally when phpseclib gets disconnected whilst you're doing some other non-phpseclib time consuming task that phpseclib should auto reconnect when you next try to do a new PHP command. But obviously that's not gonna work if the error handler is turning errors into uncaught exceptions.

Does prepending `@` help?

**Comment by ndobromirov** [comment]
> Does prepending @ help?
Yes.

**Comment by terrafrost** [comment]
https://github.com/phpseclib/phpseclib/commit/ded9b3043fc717ff01be44afe1053a497d243eac should address this - thanks!
