### ISSUE TITLE
Please document namespace change in the changelog

### ISSUE THREAD

**Issue by gdejong** [phpseclib/phpseclib#1561]
For the `3.0` release the namespace has been renamed from `phpseclib` to `phpseclib3` (https://github.com/phpseclib/phpseclib/commit/653dbd7f946441387a8779d7ab7b8676c9b324ef).

I read the [CHANGELOG](https://github.com/phpseclib/phpseclib/blob/master/CHANGELOG.md) but did not find any reference to this breaking change.

Would you please consider adding a note regarding the namespace rename to the changelog?

**Comment by terrafrost** [comment]
I can add a note but keep in mind that's not the only BC breaking change between 2.0 and 3.0. The other big one is the way public keys are handled.

The phpseclib 2.0 way only supported RSA keys and didn't provide for immutable key objects:

```php
$rsa = new RSA;
$rsa->loadKey('...');
```

The phpseclib 3.0 way supports ECDSA / DSA / DH / RSA keys:

```php
PublicKeyLoader::load('...');
```
Keys returned now are either instances of PublicKey or PrivateKey whereas before there was no such distinction. Now, you can only do RSA encryption with a PublicKey because the encrypt() method doesn't exist with in the PrivateKey interface whereas it does for the PublicKey method.

Overall, the changes between 2.0 and 3.0 are _numerous_. Not all of them are BC breaking (switching from `array()` to `[]` is only BC breaking if you're trying to run phpseclib 3 on PHP 5.3) but still.

If you want to use phpseclib3's expanded key support but with the phpseclib2 API https://github.com/phpseclib/phpseclib2_compat should do the trick.

**Comment by terrafrost** [comment]
See https://github.com/phpseclib/phpseclib/commit/19afa6300a66caf9c58fa96036f99aa1b9917ef6
