### ISSUE TITLE
Why 3.0 is release with php 5.6 requirement

### ISSUE THREAD

**Issue by fezfez** [phpseclib/phpseclib#1569]
I wonder why the fresh 3.0 is released with php 5.6 required.
According to https://blog.packagist.com/php-versions-stats-2020-2-edition/ statistics

84,94 % of running php are ^7.2
92.39 % if we extends to ^7.1

According to https://www.php.net/supported-versions.php

php 5.6 is EOL since 2 year and 7.3 is now only security report.

^7.3 will allow strong type and will result in less bug, why such a choice ?

**Comment by terrafrost** [comment]
The master branch (which became the 3.0 branch) started to diverge from the 2.0 branch on or before July 2015 per https://github.com/phpseclib/phpseclib/pull/739 . So it took 5 years for phpseclib 3.0 to be released and I didn't want to wait another 5 years.

I mean, if I'm going to make phpseclib require PHP 7.2 as a minimum then I might as well actually take advantage of the features that 7.2 offers. Otherwise I'm kinda being a dick by saying phpseclib 3.0 requires PHP 7.2 when it really requires PHP 5.6. But doing that would take time. Sure, it's not gonna take years but I didn't think adding support for compression would take years either. I don't think making SFTP.php do $res = $sftp->open('filename.ext'); $res->read(1024); $res->close();` would take years either. Neither would making it so SSH2.php supports multiple channels. None of those, alone, maybe take a year of dev time, but all of them, together...  that starts to add up. So you have to draw a line in the sand somewhere.

That's the main reason. As for why I didn't draw the line in the sand in a place that included PHP 7.1 or 7.2 support...  well as you noted, there are def advantages to supporting newer versions. But there are disadvantages to:

- the numbers you cited are going to be skewed somewhat. If you're running PHP in Docker your source code might live outside of the container and doing composer install outside of the container will return the version of PHP running outside of the container - not the version inside the container.

- once you do `composer install` / `composer update` you really don't need composer. Consider https://wordpress.org/plugins/ssh-sftp-updater-support/ . 40,000 active installs. What if that was updated to use phpseclib 3.0? You'd include the vendor/ directory that Composer created and the autoload.php that Composer created. Bam, packagist.com suddenly has no insight into those servers. According to https://wordpress.org/about/stats/ only 74.8% of servers are running PHP 7.1+.

- spiritually, phpseclib is a solution aimed at everyone. If you have libssh2 installed you arguably don't need to use phpseclib but phpseclib is aimed at people who don't have it installed. I'd wager most servers are running PHP64 so maybe I should delete the PHP32 engine for BigInteger.php? Removing it means less code to maintain! If there's only one PHP engine instead of two I could consolidate PHP.php and PHP64.php into one file so there's less inheritance to wrap one's head around, etc. But wait, phpseclib is designed to run for anyone anywhere.

phpseclib 4.0 will support higher versions of PHP but idk when that'll be released. Right now no commits have been made to the master branch (which'll now eventually become 4.0).

**Comment by fezfez** [comment]
phpseclib ^2.0 still support php ^5.6 and can be install, so i see no reason to still support it on ^3.0 tags.
Maybe in many year when ^4.0 will be release you will have the same argue "why don't support PHP 5.X ?"

**Comment by terrafrost** [comment]
> phpseclib ^2.0 still support php ^5.6 and can be install, so i see no reason to still support it on ^3.0 tags.

I explained why in my last post. If that didn't explain my position then I don't think we're going to see eye to eye.

> Maybe in many year when ^4.0 will be release you will have the same argue "why don't support PHP 5.X ?"

phpseclib 4.0 will not support 5.6. idk what the minimum required version of phpseclib 4.0 will be and I'm not going to comment on a release for which work has yet to even commence. And even if I did, until I create a 4.0 branch, one shouldn't assume anything about what 4.0 is going to be like.

phpseclib 3.0 is actually scaled back from my original plans. I had planned on completely revamping X509.php and SSH2.php but significantly scaled back my plans as I didn't want to wait _another_ 5 years to release phpseclib 3.0.

Increasingly, SSH servers are dropping support for out-of-date algorithms, so releasing a version with support for more modern algorithms was becoming increasingly prudent, anyway, and waiting an additional 5 years to do a release would have resulted in people finding alternate solutions.

But hey - since you know what arguments I'll make in the future and apparently what I'll do in the future, even better than I do, then I guess there's no point in commenting further. I'm closing this thread and locking this conversation as there's really no point in continuing it further.

**Comment by terrafrost** [comment]
Oh - I will say that the bullet point list of reasons I gave are more after-the-fact benefits. The chief reason I made phpseclib 3.0 have PHP 5.6 as a minimum version is because I didn't want to wait any longer to do a release and I'm not going to lie about the minimum version that phpseclib requires. phpseclib _absolutely_ requires PHP 5.6 because it uses [constant expressions](https://www.php.net/migration56.new-features#migration56.new-features.const-scalar-exprs). 5.6.1 is required because phpseclib 3.0 uses `gmp_import` and `gmp_export`, which weren't introduced until PHP 5.6.1.

But as part of my moving phpseclib over to 5.6 I _fully_ embraced 5.6, including using the short array syntax (`[]` vs `array()`), which was added in PHP 5.4 (whereas phpseclib 2.0 supports 5.3).

When I bump the version requirements for the master branch (which will eventually become the 4.0 branch) I'll _fully_ embrace that new version.

I am not, however, going to bump the version requirements, effectively lying about them, just so I can get some sense of moral superiority or whatever. Sure, I suppose I could drop random_compat from composer.json and that'd effectively make the minimum version to PHP 7.0, but imho, that's just a dick move. If all it takes to make phpseclib work on PHP 5.6 is adding _one_ line to composer.json, then why the hell wouldn't I do it? By that same argument, if the _only_ thing I needed to do to make phpseclib 3.0 work on PHP 5.3 was to add one line, I'd do so in a heart beat, but due to my _full_ embrace of PHP 5.6, it would require changes to many thousands of lines. It'd be a _huge_ refactor.

When phpseclib bumps the minimum version requirement it will be a _full_ embrace of that new version and adding support for older versions of PHP won't just require adding one line to composer.json - it'll require a fairly massive rewrite, just as phpseclib 3.0 would if you wanted it to support 5.3.

I'm not going to bump the minimum version requirements to PHP 7.0 until phpseclib implements strict typing.

I'm not going to bump the minimum version requirements to PHP 7.1 until phpseclib implements everything for 7.0 _and_ implements symmetric array destructuring (ie. instead of `list($a, $b) = ...;` it'll then be `[$a, $b] = ...;`) and class constant visibility (eg. `public const WHATEVER = ...;` instead of just `const WHAEVER = ...;`) and negative string offsets (`substr($parts[$i - 1], -1)` becomes `$parts[$i - 1][-1]` and `$line[strlen($line) - 1]` becomes `$line[-1]`, etc), etc.

I'm not going to bump the minimum version requirements to PHP 7.2 until phpseclib implements everything for 7.1 _and_ parameter type widening (not sure the applicability of abstract method overriding or object return types atm).

Nothing in PHP 7.3 really screams out to me. Maybe array destructuring supporting reference assignments could be used _maybe_ idk

For PHP 7.4...  phpseclib won't support it until phpseclib supports typed properties, arrow functions (if applicable), limited return type covariance and argument type contravariance, nul coalescense operator (if applicable), unpacking inside arrays, etc. 

For PHP 8.0...  named arguments, constructor property promotion, union types, probably, maybe match expression, idk (I do use fall through cases a good amount in my switches, tho), nullsafe operator, maybe ::class on objects, etc.

And, again, that's just what I'm thinking, currently. Who the hell knows what I'll be thinking two years from now. Maybe I'll bump the version requirements without doing any of that. I can't fathom lowering them. Unless someone pays me $100,000 or so (the exact amount is prob negotiable lol) it's a very very safe bet that they're not going to be lowered. But hey, I guess you don't need to bet since you're a clairvoyant who can see my future better than I can 🙄

**Comment by terrafrost** [comment]
Actually, if you're wanting evidence that I'm, at minimum, going to be bumping the minimum version requirements for 4.0 to _at least_ PHP 7.0, see https://github.com/phpseclib/phpseclib/pull/1418 . The big thing I want to do for 4.0 is revamp X509 cause the current API is awful imho. Certainly SSH2 / SFTP could use improvements, as well, but X509 really needs them. And I'm going to do ArrayObject for that. idk if I'll use anonymous classes in that but, the broader point, remains: idk what the future holds but I can say with very high confidence that it _does_ include bumping the minimum required PHP version (albeit prob not in as extreme leaps and bounds as you'd prefer).

But while we're on the subject, other features from 8.0 I think could be really cool for phpseclib x.0:

https://wiki.php.net/rfc/inheritance_private_methods
https://wiki.php.net/rfc/static_return_type
https://wiki.php.net/rfc/stringable

There are also some things who's applicability is not known to me. eg. weak references / weak maps. I'd need to play around with that. idk when weak references were introduced (PHP 8 added weak maps) but phpseclib prob isn't going to support them anytime soon, even if they are applicable.

As for when phpseclib will require PHP 8 as the minimum version...  well, for those of us without crystal balls, it's really hard to say!

**Comment by terrafrost** [comment]
And if you're concerned about the fact that #1418 is over a year old...  also realize that for most of 2020 I was working on the documentation for phpseclib 3.0. If I hadn't done that phpseclib 3.0 would have been released a year ago. But releasing such wide sweeping changes as 3.0 introduced without documentation seems irresponsible.
