### ISSUE TITLE
Case mismatch between loaded and declared class names

### ISSUE THREAD

**Issue by geraudlacheny** [phpseclib/phpseclib#1570]
Hello,
I am a Symfony user and i try to use this bundle. But when i try to list the directories of my server via SFTP, it says : 

Case mismatch between loaded and declared class names: "phpseclib3\Crypt\EC\Curves\curve25519" vs "phpseclib3\Crypt\EC\Curves\Curve25519".

I can see the problem in Crypt/EC.php, in createKey() method L.165. If i put an ucfirst function before, it works but to the detriment of connection new SSH2. Both can't work together.

Thanks for your help

**Comment by terrafrost** [comment]
I'm not able to reproduce the issue on https://3v4l.org/tBktD

Works without issue on Mac OS X as well...

**Comment by geraudlacheny** [comment]
No I'm Windows 10 user and maybe the framework symfony 4 i used is involved (PSR-4)?
In the screenshot below, you can see that the debug "L.165" is only displayed and no "L.167". So the condition "if !class_exists()" doesn't work for me. It should check that "\phpseclib3\Crypt\EC\Curves\curve25519" is an existing class. It should say no and make a ucfirst("curve2551"9) then check that "\phpseclib3\Crypt\EC\Curves\Curve25519" is an existing class and say yes... But it does not.
Is it clearer ?

![phpseclib-capture](https://user-images.githubusercontent.com/21198829/103751685-fb3d6f80-5008-11eb-963d-b823ddf34613.jpg)

**Comment by terrafrost** [comment]
I understand the phpseclib side of things. What I didn't understand was how - if at all - Symfony factored into it. Like sometimes people say they're using Symfony and phpseclib together and that they're having a specific issue but the fact that they're using Symfony is completely irrelevant to the issue they're having. In your case it's not and, per your screenshot, the error is not reproducable without it.

What I will say is that [Curve25519](https://en.wikipedia.org/wiki/Curve25519), with an upper case "C", is the actual name of the curve, whereas the names of all of the [SECG](https://en.wikipedia.org/wiki/SECG) curves (eg. secp256k1, nistp256, etc) are all lower case. That's why they have the names that they do in phpseclib 3.

That said, I also realize that Symfony is big deal and compatibility issues with it is also a big deal. Let me think on this some.

**Comment by terrafrost** [comment]
I think https://github.com/phpseclib/phpseclib/commit/e14e9e92caeebee85012fc3cb676ad7549e9dbf5 should fix this.

Thanks!

**Comment by sveriger** [comment]
Thx for fixing this. When did you plan release a new tagged version 3.0.3?

**Comment by terrafrost** [comment]
I'll try to do so in the next few days! I have one other thing I want to get in before that releas!

**Comment by terrafrost** [comment]
> Thx for fixing this. When did you plan release a new tagged version 3.0.3?

Done!
