### ISSUE TITLE
phpseclib3\File\X509 needs to implement __isset to properly work here or add as property

### ISSUE THREAD

**Issue by applibs** [phpseclib/phpseclib#1590]
```
if (isset($subject->domains)) {
    $this->removeExtension('id-ce-subjectAltName');
}
```

and

`if (isset($subject->ipAddresses) && count($subject->ipAddresses))`

**Comment by terrafrost** [comment]
`$domains` and `$ipAddresses` ought to be defined at the top as class variables, I'll grant that. `__isset`, however, is not necessary, even with them _not_ being defined as class variables, as the following code demonstrates:

```php
<?php

class demo {}

$demo = new demo;
echo isset($demo->a) ? 'is set' : 'is not set';
echo "\n";
$demo->a = 'test';
echo isset($demo->a) ? 'is set' : 'is not set';
```
The output for _every_ version of PHP (4.3.0 to 8.0.1) is as follows:

```
is not set
is set
```
There are no runtime errors at all in that code. You can see it in action at https://3v4l.org/KerQF

I'll add `private $ipAddresses = null;` and `private $domains = null;` at the top, as time permits, but if there's any way this could actually cause a bug I'm not seeing it. I mean, it is sloppy not to have them defined at the top (hence my intention to add them) but just because something is sloppy doesn't mean it's a bug. It might be but there's no guarantee of that.

It's kinda like...  _not_ using SQL prepared statements may be sloppy but that doesn't necessarily mean that the code in question is 110% guaranteed to be SQL injectable either...

**Comment by terrafrost** [comment]
https://github.com/phpseclib/phpseclib/commit/845a2275e886ba9fb386c8f59cb383dd9c8963e9 should fix this.

Thanks!
