### ISSUE TITLE
Undefined class 'PrimeFields' 

### ISSUE THREAD

**Issue by applibs** [phpseclib/phpseclib#1591]
```
/**
 * Prime Field Integer factory
 *
 * @var \phpseclib3\Math\PrimeFields
 */
protected $factory;
```

**Comment by terrafrost** [comment]
```php
/**
 * Prime Field Integer factory
 *
 * @var \phpseclib3\Math\PrimeFields
 */
protected $factory;
```
You're right. Should be PrimeField, singular.

DocBlock comments are something I really don't pay much attention to, hence why errors like this can exist. Maybe bad DobBlock comments makes this library a little harder to use with PhpStorm but I don't really use PhpStorm. They're definitely _not_ gonna cause issues in code, since it's ultimately an issue in comments, but that doesn't mean that it ought not be fixed.

**Comment by applibs** [comment]
Believe me, I didn't invent those things.

**Comment by terrafrost** [comment]
https://github.com/phpseclib/phpseclib/commit/bdb6c08c3507c3aeb47a1bc5a198ee9bdb3618f7 should fix this - thanks!
