### ISSUE TITLE
Uncaught Error: Class 'phpseclib\Net\SFTP' not found in ...

### ISSUE THREAD

**Issue by e-edgren** [phpseclib/phpseclib#1595]
Hi.

I installed phpseclib (dev-master) via Composer and using the following to connect to my SFTP server.

```
require_once 'vendor/autoload.php';
use phpseclib\Net\SFTP;

$sftp = new SFTP('address');
if(!$sftp->login('username', 'password')) {
    exit('Login Failed');
}

$sftp->put('remote.php', 'local.php', SFTP::SOURCE_LOCAL_FILE);
```

I get this error message: `Fatal error: Uncaught Error: Class 'phpseclib\Net\SFTP' not found in ...`

Have I missed something?

**Comment by terrafrost** [comment]
You really shouldn't be using dev-master. Use the 3.0 branch or the 2.0 branch or something but not dev-master. I may make BC breaking changes from commit to commit with dev-master. 3.0 shouldn't have any (major) BC breaking changes.

But anyway, for 3.0 or (for right now) master you need to use `use phpseclib3\Net\SFTP;` - not `use phpseclib/Net/SFTP`. phpseclib v3 has some pretty big BC breaking changes from v2. SFTP doesn't have too many BC breaking changes but it has some as well. The main reason I changed the namespace'ing is so that you could run a [phpseclib2 shim using phpseclib3](https://github.com/phpseclib/phpseclib2_compat).

**Comment by e-edgren** [comment]
Alright. Thank you :)
