### ISSUE TITLE
[V3] Generating RSA keys is way slower than in V2

### ISSUE THREAD

**Issue by NicoHaase** [phpseclib/phpseclib#1596]
Calling `RSA::createKey(4096);` on PHP 7.4 got way slower in v3 than it was in v2. Our internal testsuite took less than a second in v2 for a similar call, and it takes nearly three minutes (factor 180!) in v3. Is there any way to speed this up?

Well, it's getting more mysterious as I'm writing this ticket. A test call with `$bits = 2048` just took about a minute(!) to be executed, another succeeding call with `$bits = 4096` took less than five seconds. Is this due to the userland implementation of BigInteger?

**Comment by terrafrost** [comment]
Can you post your phpinfo() output?

In v2 it prioritized engines thusly:

- GMP
- BCMath
- Internal

In v3 it's different:

- GMP
- PHP64 (with OpenSSL if it's available)
- BCMath
- PHP32 (with OpenSSL if it's available)

In my testing PHP64 is now faster than BCMath.

That said, the time is definitely subject to some variance because the way prime number generation works is that you just keep on picking numbers at random and you keep on testing them to see if they're prime numbers until you find a number that is prime. Sometimes this approach can take a while sometimes it doesn't - just luck of the draw. The [prime number theorem](https://en.wikipedia.org/wiki/Prime_number_theorem) talks about the distribution of prime numbers among the set of positive integers. From that you could probably deduce the average number of numbers that would have to be randomly generated for you to find an x-bit prime number. Maybe a standard deviation could be identified as well. But someone else can do that 😅

Back to your issue tho...  how often do y'all run the internal testsuite? If v2 was _consistently_ faster than v3 and tests are run multiple times a day that'd be more disconcerting. But if you only ran it ever like three times against v2 and twice against v3 then your sample set is prob not big enough to really give good stats idk lol

**Comment by terrafrost** [comment]
I guess one thing that could skew this too...  xdebug has historically slowed things down quite a bit. The latest version of xdebug is supposed to be waaaay faster but who knows how much faster and idk if y'all are using the latest xdebug version anyway.

I mention that because the pure-PHP mode / engine / whatever is more impacted by the use of xdebug than BCMath or GMP are. Consequently, it might not be a bad idea to use BCMath if xdebug is installed 🤔

**Comment by NicoHaase** [comment]
The internal test suite is not the core problem, but one that warned me before merging this update :) A single call (not multiple ones!) of `RSA::createKey(4096);` took way more than a minute. I'm not talking about running this multiple times, but a single time. This is part of a key generator that should print the resulting keys in an internal interface, so waiting so long is not acceptable.

The PHP settings haven't changed between using this in v2 and in v3, neither in terms of any extensions nor in the usage of xdebug.

**Comment by NicoHaase** [comment]
What I found out: BigInteger uses `phpseclib3\Math\BigInteger\Engines\PHP64`

**Comment by terrafrost** [comment]
It looks like 3.0 saw the removal of OpenSSL from the creation of private keys:

https://github.com/phpseclib/phpseclib/commit/0398f7a81550a487170edca0ed39f360d4509e83#diff-22c2d475f14b1307805ece908d9701d0273fe34b015d42d80b2b6cf456235888

(it's a big commit btw)

I make no mention of that change in the PR for that commit (#1322).

Best guess as to why I did it: I probably figured that if you had OpenSSL already available and weren't using GMP that OpenSSL was already being used with `isPrime()`, which I figured was the chief bottleneck, anyway, due to it's heavy use of modular exponentiation. ie. I probably figured that the fact that OpenSSL was being used for primality testing (vis-a-vis modular exponentiation), when available, made using it for RSA key generation redundant. But maybe, as you use larger and larger RSA keys other bottlenecks begin to appear, above and beyond that of primality testing.

>  I've edited the engine selection in `\phpseclib3\Math\BigInteger::initialize_static_variables`

Easier way to do that: `BigInteger::setEngine('PHP64', ['OpenSSL']);`

**Comment by NicoHaase** [comment]
So, do you have any idea about how to resolve this?

**Comment by terrafrost** [comment]
> So, do you have any idea about how to resolve this?

Yes. Adding OpenSSL back would do the trick. Is it the best solution, tho? idk. Anyway, I'm looking into this, but bear in mind that I'm not going to cut corners to get a solution out the door faster. I do that for my day job because they pay me to do that but I'm not going to do that for this library. At least not unless someone wants to make a significant donation lol

**Comment by NicoHaase** [comment]
Sorry, I think my last comment was a bit too short. I really appreciate the work you're doing, and there might be easier tasks than implementing such algorithms. If nobody else is facing any performance issues, I'm fine with using v2. If there is any way I could help you (like checking whether a branch resolves my problem), I'd be happy to provide help

**Comment by terrafrost** [comment]
https://github.com/phpseclib/phpseclib/commit/b49203d5b96135d1a2505dfb5991963c7a7e63ac should speed it up a lot. Not sure how it compares to v2 yet but there was an issue wherein a lot of OpenSSL calls would fail. 

Like normally it'd generate keys like this:

```
-----BEGIN PUBLIC KEY-----
MIICITANBgkqhkiG9w0BAQEFAAOCAg4AMIICCQKCAQEAvzLcmjDflBtO5BvuQYMe
UIh0wBeq+q4b5xAONwN3a+n++jUPoWz3wc1uO0Eq68JqqafPqqS1jla4VQMcLeAG
hB505qIqOmqiTh02cjbtQlgDTUx/tzDA/0A/sRZI5GHwuhOwQJk/J9STXY3vChUo
LcEStt6CzdkBx0WJnJ35mnqN2Pt4MsIrSwY2pqUfNUjb368785acFDRT20et9yIl
9vVtBCLWuvNEBzxvtX8jLIdovDgUk0fZOljUMAnviDQHkiD+ROpnaVIOWZRkvfZi
y3mtJqbUa63j04qpLGQPNP3Ptgd+T2LVXd7Jlcm5KX86+hvmM7mlUUhAPlDhhN10
zQKCAQAvzLcmjDflBtO5BvuQYMeUIh0wBeq+q4b5xAONwN3a+n++jUPoWz3wc1uO
0Eq68JqqafPqqS1jla4VQMcLeAGhB505qIqOmqiTh02cjbtQlgDTUx/tzDA/0A/s
RZI5GHwuhOwQJk/J9STXY3vChUoLcEStt6CzdkBx0WJnJ35mnqN2Pt4MsIrSwY2p
qUfNUjb368785acFDRT20et9yIl9vVtBCLWuvNEBzxvtX8jLIdovDgUk0fZOljUM
AnviDQHkiD+ROpnaVIOWZRkvfZiy3mtJqbUa63j04qpLGQPNP3Ptgd+T2LVXd7Jl
cm5KX86+hvmM7mlUUhAPlDhhN10z
-----END PUBLIC KEY-----
```
A 2048-bit key whose first byte is "\0". In this scenario `strlen($n->toBytes(true)) - 1` returns the correct padding amount.

BUT in some cases it'd generate a key like this:

```
-----BEGIN PUBLIC KEY-----
MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAQEBXtm9yhdmKHtbTda8RQJO
J6FJ72GMP5kKOJxmZV+je1RPR4agjq2rkicS5ULIqnqcvQMdypCFEWayBxOsX7PW
8/qbZKguXASPltHI/E5BvRq9TGBIX8GdkNJcKWcUDN1HVt+JeNN2KPNh31zldiH3
ldzEvCCtfpF0t0TMHOYVklTBgFsDZd1AT1+LmkG2DJZLIn5Q/iOjS3PaC9fxB7pr
US5peOeTEct3BsXtiSpQLvSNkoIUs2ViyO+Mb7Qy3ZBkbdC6HAuptNvnSmjNeCQ2
zcQ3qOE4n+PHvuEUagDofr3rb7Ebtb14JqWjsNtTIK/skbqJxZet6Cqhaaq84aY+
jwKCAQEAr2ze5QuzFD2tputeIoEnE9Ck97DGH8yFHE4zMq/Rvaono8NQR1bVyROJ
cqFkVT1OXoGO5UhCiLNZA4nWL9nref1NslQXLgJHy2jkficg3o1epjAkL+DOyGku
FLOKBm6jq2/EvGm7FHmw765yuxD7yu5iXhBWv0i6W6JmDnMKySpgwC2Bsu6gJ6/F
zSDbBkslkT8ofxHRpbntBev4g901qJc0vHPJiOW7g2L2xJUoF3pGyUEKWbKxZHfG
N9oZbsgyNuhdDgXU2m3zpTRmvBIbZuIb1HCcT/Hj33CKNQB0P171t9iN2t68E1LR
2G2pkFf2SN1E4svW9BVQtNVecNMfRw==
-----END PUBLIC KEY-----
```
It has a 2049-bit modulo as opposed to a 2048-bit modulo. Weird but shouldn't be an issue. BUT what was an issue is that the first byte was "\1", at which point `strlen($n->toBytes(true)) - 1` ceased to return the correct call.

Anyway, like I said, this may still be slower than v2, but it should be consistently loads faster than the latest release of v3. I'll do the v2 benchmarks shortly!

**Comment by NicoHaase** [comment]
Thanks a lot for investigating - I've tested this first fix, and it reduced the time to run `RSA::createKey(4096);` by magnitudes. In multiple runs of my testsuite, it never exceeded 15 seconds, most runs finished within less than 5 seconds

**Comment by terrafrost** [comment]
https://github.com/phpseclib/phpseclib/commit/e9f79655db3c2c65906460c3a3d600c1004f5729 should speed key generation up even more!

v2 does some `phpinfo()` checks, as well, but, for the time being, I'm opting not to do them. Like maybe they're only needed for PHP 5.3-5.6 but not for 5.6+.

Here are the checks v2 does:

https://github.com/phpseclib/phpseclib/commit/d4a98457bcc1e47852f1ccbffb845558c3078031

**Comment by NicoHaase** [comment]
That's wonderful - the key generation works as fast as in v2. Thanks a lot for putting your work into this :)
