### ISSUE TITLE
DivisionByZeroError RSA (version 3.0.4)

### ISSUE THREAD

**Issue by kocoten1992** [phpseclib/phpseclib#1614]
I got this while running tests, cannot reproduce though.

```php
  at engine/vendor/phpseclib/phpseclib/phpseclib/Math/BigInteger/Engines/GMP.php:270
    266|     {
    267|         $quotient = new self();
    268|         $remainder = new self();
    269| 
  > 270|         list($quotient->value, $remainder->value) = gmp_div_qr($this->value, $y->value);
    271| 
    272|         if (gmp_sign($remainder->value) < 0) {
    273|             $remainder->value = $remainder->value + gmp_abs($y->value);
    274|         }

  1   engine/vendor/phpseclib/phpseclib/phpseclib/Math/BigInteger/Engines/GMP.php:270
      gmp_div_qr()

  2   engine/vendor/phpseclib/phpseclib/phpseclib/Math/BigInteger.php:298
      phpseclib3\Math\BigInteger\Engines\GMP::divide()

  3   engine/vendor/phpseclib/phpseclib/phpseclib/Crypt/RSA.php:332
      phpseclib3\Math\BigInteger::divide()
```

At version 3.0.4

```
"name": "phpseclib/phpseclib",
"version": "3.0.4",
"source": {
    "type": "git",
    "url": "https://github.com/phpseclib/phpseclib.git",
    "reference": "845a2275e886ba9fb386c8f59cb383dd9c8963e9"
},
```

**Comment by terrafrost** [comment]
I'm not really sure how that's possible. Here's line 332 from Crypt/RSA.php:

```php
list($min) = $min->divide($n);
```

`$n` is defined thusly:

```php
$n = clone self::$one;
```

`$min` is defined thusly:

```php
                    extract(BigInteger::minMaxBits($bits));
                    /** @var BigInteger $min
                     *  @var BigInteger $max
                     */
```
(`minMaxBits` returns an associate array with min and max as keys)

Here's how `minMaxBits` is deals with min (from Math/Engines/Engine.php):

```php
        $min = str_repeat(chr(0), $bytes);
        $msb = $bits & 7;
        if ($msb) {
            $min = chr(1 << ($msb - 1)) . $min;
        } else {
            $min[0] = chr(0x80);
        }
```
`$msb` has seven different possible values - 0, 1, 2, 3, 4, 5, 6 or 7. For 0 the first character is set to `chr(0x80)`. For the rest the possible values are:

```
0: 1
1: 2
2: 4
3: 8
4: 16
5: 32
6: 64
```
If you called `minMaxBits(0)` the string you'd get would be `chr(0x80)`. Might be better if an exception was thrown, but still, since it's a non-zero value _even_ when `minMaxBits()` is passed a 0 (which would only happen if you did `RSA::createKey(0)` I don't see how the issue you're describing could happen, especially with the stack trace you've provided...

**Comment by kocoten1992** [comment]
It `could` mean my computer got memory corruption, I've a bad experience with memory corruption in the past (have replaced all memory stick though), hope this is the case.

Can close this issue though, thank you very much!
