### ISSUE TITLE
Feature request, persistent connections

### ISSUE THREAD

**Issue by powerpbx** [phpseclib/phpseclib#1622]
I added some timers and got the following results.

Keyloading takes 0.016s.
Login takes 0.6s.
Each exec command (which includes keyloading + login) takes about 1s total.

The problem is that I would like to do several commands, one after another, as individual outputs.  So the delay quickly adds up.
It would be nice If there was some way to keep a persistent connection. That would cut out over 0.6s for each command.

Something like:
```
$ssh->login()
$ssh->open();
$var1 = $ssh->exec('command1');
$var2 = $ssh->exec('command2');
$var3 = $ssh->exec('command3');
$ssh->close();
```
So that way keyloading and `$ssh->login()` only needs to occur once.

**Comment by terrafrost** [comment]
Replacing `fsockopen` with `pfsockopen` would be a good starting point. I tested out https://stackoverflow.com/q/15390159/569976 and it works via an Apache2 webserver I have whereas it doesn't work via the CLI. So I can probably build off that.

You're using 3.0 so I can build off of that as well.

The destructor would be problematic since that calls `fclose($this->fsock)`. I suppose a `$ssh->makeConnectionPersistent()` method could be added, to be called after the constructor but before the login.

All the variables at https://github.com/phpseclib/phpseclib/blob/3.0.5/phpseclib/Net/SSH2.php#L3184 would need to be persisted somehow. Maybe the destructor could be modified to set cookies when it's called but idk that that'd work well with frameworks like Laravel or whatever. Beyond that I'm not really sure what can be done here. In theory could be added - `$ssh->getPersistData()` - or some such but would we force that to be called when a timeout occurs?

https://www.php.net/manual/en/function.pfsockopen.php#87586 suggests that `ftell` can be used to see if a newly opened socket is a persistent one or not.

**Comment by powerpbx** [comment]
I found this in the documentation so it looks like it should work the way I want already.  I just need to change my code so the login occurs just before instead of being called each time.

```
5.1.7. Successive calls to SSH-2's exec()
Successive calls to SSH-2's exec() may not work as expected. Consider the following:

<?php
include('Net/SSH2.php');

$ssh = new Net_SSH2('www.domain.tld');
if (!$ssh->login('username', 'password')) {
    exit('Login Failed');
}

echo $ssh->exec('pwd');
echo $ssh->exec('cd /');
echo $ssh->exec('pwd');
?>
```
