### ISSUE TITLE
Exception when executing a big script

### ISSUE THREAD

**Issue by ppavel832** [phpseclib/phpseclib#1632]
I am trying to execute a big bash script of 1829124 bytes.
And I've got the following exception with a trace log.
```
SSH Exception: Only 172032 of 1829124 bytes were sent, in line 4014, trace: #0 C:\projects\ufas\vendor\phpseclib\phpseclib\phpseclib\Net\SSH2.php(2693): phpseclib3\Net\SSH2->send_binary_packet('b\x00\x00\x00\x00\x00\x00\x00\x04exec\x01\x00...')
#1 C:\projects\ufas\public\index.php(416): phpseclib3\Net\SSH2->exec('#!/bin/bash\nETP...')
```

The phpseclib version from composer.json is:
```
{   
   "require": {
        "phpseclib/phpseclib": "^3.0"
    }
}
```

The code is very simple:
```php
define('NET_SSH2_LOGGING', 2);
global $script, $host, $username, $password;
try {
  $ssh = new SSH2($host);
  $ssh->login($username, $password);
  $ssh->exec($script);
  echo $ssh->getLog();
}
catch(Exception $) {
  error_log("SSH Exception: " . $e->getMessage() . ", in line " . $e->getLine() . ", trace: " . $e->getTraceAsString() .  "\n", 3, 
  ERROR_LOG_NAME);
}
```
I have no log with echo `$ssh->getLog();` because exception is thrown before this line.
I tried to put `$ssh->setTimeout(30);` before the `$ssh->exec($script)`, but still no luck. 
The number of sent bytes is always different. It seems it's trying to send data and then something interrupts it. The connection established is good and it works fine for the smaller scripts. Or commands like `$ssh->exec('ls')`.
Are there any limitations for the size of scripts can be executed with exec command? Can they be enlarged?

**Comment by terrafrost** [comment]
I get a `Connection closed prematurely` error when I try to run this:

```php
$cmd = str_repeat('true && ', 1024 * 128) . ' ls -latr';
echo $ssh->exec($cmd);
```
That said, I'm not really sure it's going to be possible to make it so that phpseclib can support excessively large commands via `$ssh->exec()`. With `$ssh->write()` commands can be sent in chunks. You can do `$ssh->write("true && l"); $ssh->write("s - latr\n");` and (assuming you're sending to bash) it'd be the same thing as sending `$ssh->write("true && ls -latr\n");`. That's not how `exec()` works. With `exec()` you send the _whole_ command all in one go. You can't split it up like you can with `$ssh->write()`.

SSH packets also do have an upper bound on how big they can be. When stuff can be split up across multiple packets that size limit isn't an issue but when they can't be split across multiple packets it does become a limiting factor.

Here's what the SSH specs say about the max packet size:

```
   All implementations MUST be able to process packets with an
   uncompressed payload length of 32768 bytes or less and a total packet
   size of 35000 bytes or less (including 'packet_length',
   'padding_length', 'payload', 'random padding', and 'mac').  The
   maximum of 35000 bytes is an arbitrarily chosen value that is larger
   than the uncompressed length noted above.  Implementations SHOULD
   support longer packets, where they might be needed.  For example, if
   an implementation wants to send a very large number of certificates,
   the larger packets MAY be sent if the identification string indicates
   that the other party is able to process them.  However,
   implementations SHOULD check that the packet length is reasonable in
   order for the implementation to avoid denial of service and/or buffer
   overflow attacks.
```

Source: http://tools.ietf.org/html/rfc4253#section-6.1

In light of this my recommendation would be to do it with an [interactive shell](https://phpseclib.com/docs/commands#interactive-shell) or to create a `./script.sh` script and do `$ssh->exec('./script.sh')` instead of `$ssh->exec('really big sequence of commands')`.
