### ISSUE TITLE
Access to undeclared static property

### ISSUE THREAD

**Issue by tomsommer** [phpseclib/phpseclib#1638]
```
Error: Access to undeclared static property: phpseclib3\Crypt\Common\Formats\Keys\PuTTY::$types in /vendor/phpseclib/phpseclib/phpseclib/Crypt/Common/Formats/Keys/PuTTY.php:133
Stack trace:
phpseclib3\Crypt\Common\Formats\Keys\PuTTY::load(Array, NULL)

```

**Comment by terrafrost** [comment]
I haven't forgotten about this - I've been busy for the past several days so hopefully I'll be able to focus on this more within the next few days.

Thanks!

**Comment by terrafrost** [comment]
Are you trying to access phpseclib3\Crypt\Common\Formats\Keys\PuTTY directly? If so it's not supposed to be accessed directly.

`$types` is defined in phpseclib3\Crypt\EC\Formats\Keys\PuTTY, phpseclib3\Crypt\RSA\Formats\Keys\PuTTY and phpseclib3\Crypt\DSA\Formats\Keys\PuTTY

If you know the key format but not the type...  I'd still recommend using `PublicKeyLoader::load(...)` but if you wanted a `PublicKeyLoader::loadFormat(...)` I guess I could add that!

**Comment by tomsommer** [comment]
I use ::load, see the Stack trace

`phpseclib3\Crypt\Common\Formats\Keys\PuTTY::load(Array, NULL)`

**Comment by terrafrost** [comment]
So yah `phpseclib3\Crypt\Common\Formats\Keys\PuTTY::load(Array, NULL)` is not intended to be accessed directly.

In the RSA/LoadKey.php unit tests I do `phpseclib3\Crypt\RSA\Formats\Keys\PuTTY::load(Array, NULL)`.

I guess that wouldn't work out so well if you didn't know the key type (eg. EC, DSA or RSA).

Maybe I can add a `getComment()` method to AsymmetricKey so that you could do `echo $publickey->getComment()`. Not all formats support comments, however, so for those that don't, I guess it could return null or false or something.

I wouldn't add a `setComment()` method since that can be set with the second parameter to of `toString()`. eg. `$key->toString('PuTTY', ['comment' => 'whatever']);`.

**Comment by tomsommer** [comment]
`getComment()` would be nice, and `null` if none

**Comment by terrafrost** [comment]
See https://github.com/phpseclib/phpseclib/commit/d9615a6fb970d9933866ca8b4036ec3407b020b6
