### ISSUE TITLE
phpseclib3 Private key with password unable to parse

### ISSUE THREAD

**Issue by gvandenbosch** [phpseclib/phpseclib#1657]
When I try sign a certificate  with a key that is created `withPassword` then I get the following error:

```
CRITICAL - 2021-05-16 22:56:19 --> Unable to parse using either OneAsymmetricKey or PublicKeyInfo ASN1 maps
#0 /var/www/html/bramamkb/vendor/phpseclib/phpseclib/phpseclib/Crypt/RSA/Formats/Keys/PSS.php(117): phpseclib3\Crypt\Common\Formats\Keys\PKCS8::load('0\x82\t\xDD0W\x06\t*\x86H\x86\xF7\r\x01...', '')
#1 /var/www/html/bramamkb/vendor/phpseclib/phpseclib/phpseclib/File/X509.php(2607): phpseclib3\Crypt\RSA\Formats\Keys\PSS::load('-----BEGIN ENCR...')
#2 /var/www/html/bramamkb/app/Models/Pki/PkiModel.php(123): phpseclib3\File\X509->sign(Object(phpseclib3\File\X509), Object(phpseclib3\File\X509))
```

However when I create a key without a password, the `sign` function works fine.

This is the way I create the key with password:

```
private function generatePrivatekey()
{   
        $result = []; 
    
        $privateKey = RSA::createKey(4096);
        $privateKey = $privateKey->withHash('sha256');

        $result['privatekeypw'] = bin2hex(Random::string(32));  
        $privateKey = $privateKey->withPassword($result['privatekeypw']);
        $result['privatekey'] = $privateKey;
        return $result;
}   
```
Loading the key:

```
$signingPrivkey = PublicKeyLoader::load($signedby_ca['privatekey'], $signedby_ca['privatekeypw']);
$signedbyCA->setPrivateKey($signingPrivkey);
```

The error will generate when I try to sign:

```
$sign_result = $signingFile->sign($signedbyCA, $subjectCA)
```

Could anyone give a pointer what I am doing wrong?

**Comment by TimoDJatomika** [comment]
Hi.
I'm getting the same error. 

I'm trying to create a CRL (also with an encrypted private key). I thought `PublicKeyLoader::load($pkeyEncrypt, "secret")` would load my private key. 

I also tried to decrypt the private key using openssl:
```php
$pkeyDecrypt = openssl_pkey_get_private($pkeyEncrypt, "secret");
openssl_pkey_export($pkeyDecrypt, $pkeyDecryptOut);
```

I didn't got any error while loading the decrypted private key like this.
```php
$keyBasicLoad = PublicKeyLoader::load($pkeyDecryptOut);
```

But I was unable to create a CRL :/

**Comment by gvandenbosch** [comment]
I managed to solve it finally, I did that by setting the SIGNATURE_PKCS1 padding.

Create key function:

```
private function generatePrivatekey()
    {   
        $result = []; 
    
        $privateKey = RSA::createKey(4096);
        $privateKey = $privateKey->withPadding(RSA::SIGNATURE_PKCS1);
        $privateKey = $privateKey->withHash('sha256');
    
        $result['privatekeypw'] = bin2hex(Random::string(32));  
        $privateKey = $privateKey->withPassword($result['privatekeypw']);
        $result['privatekey'] = $privateKey;
        return $result;
    } 
```

When loading the key:

```
$signingPrivkey = PublicKeyLoader::load($signedby_ca['privatekey'], $signedby_ca['privatekeypw']);
$signingPrivkey = $signingPrivkey->withPadding(RSA::SIGNATURE_PKCS1);
```

**Comment by terrafrost** [comment]
First, I apologize for the delay. This has been a god awful week at my day job and that's kept me from replying to posts here sooner.

Second, it'd help if the full code that reproduced the issue had been posted. That way I'm not having to fill in the gaps.

> The error will generate when I try to sign

What error do you get?

> I managed to solve it finally, I did that by setting the SIGNATURE_PKCS1 padding.

Quoting https://phpseclib.com/docs/x509#public--private-keys , "_Note that whereas in the 1.0 and 2.0 branches, the signature algorithm was set by using an additional parameter in the `sign` method (or `signCSR`, `signCRL`, etc) in this case it's set based on the key. So if you want to create an rsaEncryption X509 cert you'd need to do `$publicKey = $publicKey->withHashing(RSA::SIGNATURE_PKCS1)` since, by default, RSA keys use `RSA::SIGNATURE_PSS`._".

This makes me wonder...  maybe the error you're getting isn't from phpseclib at all but from something else?

Either way it's hard to really comment without further details or an example that fully reproduces the issue.

**Comment by terrafrost** [comment]
I was able to reproduce the issue and implemented a fix here:

https://github.com/phpseclib/phpseclib/commit/84f07cc9cb8e04346ad50be69856c80b9feb5caa

Thanks!
