### ISSUE TITLE
Release 2.0.32 and 3.0.9

### ISSUE THREAD

**Issue by phil-davis** [phpseclib/phpseclib#1668]
I would be nice to have the fix for issue #1659 and #1665 released please (and whatever else is waiting for release in the 2.0 and 3.0 branches)

**Comment by micbar** [comment]
@terrafrost can we speed this up?

We have a code freeze in 10 days for our core release and that is quite critical.

Thanks!

**Comment by terrafrost** [comment]
I was asked about this 6 days ago at https://github.com/phpseclib/phpseclib/issues/1665#issuecomment-853593946 and my response at the time was:

> I'll try to do so in the next few weeks. I want to implement one thing, in particular, before the next release.
> 
> Thanks!

As a general rule I do _not_ like doing releases whilst I have pending code changes. I also am not the biggest fan of saying one thing and then doing something else nor am I the biggest fan of doing a new release after every commit.

That said, it has been a while since I've done a release, so I guess I'm willing to do a release this weekend. That's within your 10 day window.

FWIW the issues that I'd like to have out before a new release are:

- #1606 
- tests/Functional/Net/SSH2Test.php / testChannelDataAfterOpen() periodically fails on older versions of OpenSSH (SSH-2.0-OpenSSH_5.9p1 and SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.8 but NOT SSH-2.0-OpenSSH_7.2p2 Ubuntu-4ubuntu2.8) on Travis CI.
  
  Here are the logs of a failed connection with the sshd logs intermingled:

  https://travis-ci.com/github/terrafrost/phpseclib/jobs/505597527

  Here are the logs of a successful connection with the sshd logs intermingled:

   https://travis-ci.com/github/terrafrost/phpseclib/jobs/505597528

  I'm pretty sure https://github.com/phpseclib/phpseclib/commit/2d6705dfbdc36783ed29d5818a9353d575d06da1 is the culprit. In some situations it's needed, in other situations, it breaks things. To remedy this I figure I'll just put in a method to toggle the behavior on and off

  _(there is not a ticket for this issue)_
- I'd like to implement the "intelligent login" feature discussed in #1648

If I don't have them fixed by this weekend I'll just do a release without them and then the remaining issues can be resolved on the next release that I do at my discretion.

**Comment by phil-davis** [comment]
@terrafrost do you want me to help with any of the above?

**Comment by terrafrost** [comment]
If you can, sure! The 3x issues require a fairly in-depth knowledge of SSH2 but it'd be soooo totally awesome if someone else was able to make those kinds of contributions to this library.

Like right now this library seems to me to have a [bus factor](https://en.wikipedia.org/wiki/Bus_factor) of 1, which isn't a good thing!

**Comment by terrafrost** [comment]
New releases have been made.

I did not get to include fixes for the issues I mentioned above in this release :( Pretty disappointed with that :( I mean, I did get 2x new tickets here that took some time and had one additional support request on stackoverflow but meh.

**Comment by yatishmadhav** [comment]
Hi @terrafrost - we have just gotten the below in out logs and was lead here from a search on the error:

`CRITICAL: Uncaught PHP Exception RuntimeException: "Invalid Size" at /var/www/.../vendor/phpseclib/phpseclib/phpseclib/Net/SFTP.php line 2979`

We are on v3.0.5 at the moment.

Please advise? Would appreciate that.

Thank you
Yatish

**Comment by phil-davis** [comment]
Issue #1606 discusses this, and commit https://github.com/phpseclib/phpseclib/commit/0673370edace281f1345d7411e0ec65406835530 fixes that case. It is in 3.0.9.

I havven't had any problem with 3.0.9 - I guess you are recommended to update to the latest patch release 3.0.9.

**Comment by terrafrost** [comment]
@yatishmadhav - I'd do as phil-davis suggested and upgrade to the latest version. If that doesn't fix the issue then post back here and we'll proceed from there!

**Comment by yatishmadhav** [comment]
@phil-davis  @terrafrost  - We have updated to 3.0.9, I tested the process and I am still getting this in the error logs:

request.CRITICAL: Uncaught PHP Exception RuntimeException: "Invalid Size" at /var/www/.../vendor/phpseclib/phpseclib/phpseclib/Net/SFTP.php line 2963 {"exception":"[object] (RuntimeException(code: 0): Invalid Size at /var/www/.../vendor/phpseclib/phpseclib/phpseclib/Net/SFTP.php:2963)"}

Please advise what else the issue may be?

**Comment by terrafrost** [comment]
> @phil-davis @terrafrost - We have updated to 3.0.9, I tested the process and I am still getting this in the error logs:
> 
> request.CRITICAL: Uncaught PHP Exception RuntimeException: "Invalid Size" at /var/www/.../vendor/phpseclib/phpseclib/phpseclib/Net/SFTP.php line 2963 {"exception":"[object] (RuntimeException(code: 0): Invalid Size at /var/www/.../vendor/phpseclib/phpseclib/phpseclib/Net/SFTP.php:2963)"}
> 
> Please advise what else the issue may be?

Quoting https://github.com/phpseclib/phpseclib/issues/1606#issuecomment-894445288 : 

> It looks like this fix was implemented the day after 3.0.9 was released.
>
> I'm going to be out of town this weekend but maybe next weekend I can do a new release.
>
> Thanks!

I'm going to try to do a release tomorrow.

In the mean time, try the latest git version?
