### ISSUE TITLE
Constant time Base64 encoding is slow

### ISSUE THREAD

**Issue by JakubOnderka** [phpseclib/phpseclib#1745]
Hello, 

what is the reason, when encoding public key to PEM, constant time base64 method is used?

https://github.com/phpseclib/phpseclib/blob/7e38313802b62606cf27ddf573a7c47e88b5d33f/phpseclib/Crypt/Common/Formats/Keys/PKCS8.php#L637-L639

Constant time base64 method is more than 4 times slower than default PHP `base64_encode` method.

**Comment by terrafrost** [comment]
https://github.com/phpseclib/phpseclib/pull/988 is the PR that added that feature.

The reason you'd want constant time algorithms is to protect against a type of side channel attack known as timing attacks. Often times this does incur a performance penalty and sometimes when this performance penalty is too great people will say [enough is enough](https://crypto.stackexchange.com/a/27315/4520).

In this particular case, yah, it's a 4x performance hit, but I also don't imagine people are going to be doing base64 encode's over and over and over again. Like there are some parts of the phpseclib code that may be called a million or more times when you're trying to do something like generate a prime number or something. For those parts of the code speed trumps everything else. But there are other parts of the code where speed and security can be weighed against one another in equal parts.

Now, in the particular example you mentioned, it's not hugely important. As the name implies, public keys are designed to be public and if information about the public key can be gleaned by timing attacks it's not a huge concern.

But since it's also not in a piece of code that's called over and over again it's not something I'm overly concerned with. Unless there are use cases I'm not considering?

All other things being equal, I see it kinda like [prepared statements](https://en.wikipedia.org/wiki/Prepared_statement) in SQL, as well. Like `$db->query('SELECT * FROM users WHERE user_id = ' . intval($_GET['user']))` _is_ secure BUT prepared statements, despite being more verbose, are generally recommended over that because it's harder to screw up with them. Like with `$db->query()` if you forget to cast to an integer then the code will most likely still work and the vulnerability will evade detection. But if you use prepared statements then you get protection from the onset - there's nothing, security-wise, that can be forgotten.

If you have a use case where this matters LMK and I can change things up but if it's the difference between 0.00001s and 4 * 0.00001s then I'll prob just leave it as is!

**Comment by terrafrost** [comment]
https://github.com/phpseclib/phpseclib/commit/e5396968c56b6ff0d4ea12f0454dd8f8e735c676 should fix this!
