### ISSUE TITLE
EMSA-PSS sign

### ISSUE THREAD

**Issue by andrew-svirin** [phpseclib/phpseclib#1747]
Hello,

Is this script https://github.com/railslove/epics/blob/c1b9167b0f1daf076075164b7eb36b66c85ca3fb/lib/epics/key.rb#L32
Is the same that?:
```php
        $rsa = new \phpseclib\Crypt\RSA();
        $rsa->setPassword($password);
        $rsa->loadKey($privateKey, \phpseclib\Crypt\RSA::PRIVATE_FORMAT_PKCS1);
        $rsa->setHash('sha256');
        $rsa->setMGFHash('sha256');
        $rsa->setSignatureMode(\phpseclib\Crypt\RSA::SIGNATURE_PSS);
        $sign = $rsa->sign($data);
```

**Comment by terrafrost** [comment]
Yup - looks like it to me. I hacked the Ruby code together to get this:

https://pastebin.com/bUYyszh2

I then used this on the PHP end to verify it:

https://pastebin.com/2tHyLn0P

And it worked. If those same settings verify a key then they should create a key that's just as compatible. Note that EMSA-PSS signatures employ randomized padding so that if you try to sign the same string twice you'll get different signatures each time, even if you're using the same library.

**Comment by andrew-svirin** [comment]
@terrafrost Thanks a lot for information.

**Comment by andrew-svirin** [comment]
@terrafrost may be the way to make zero padding to have the same result?

**Comment by salmonila** [comment]
So you don't want PSS padding or PKCS1 padding but instead you don't want
any padding? That's basically the same thing as unpadded RSA encryption aka
modular exponentiation.

Or maybe you're wanting a salt length of zero?

**Comment by andrew-svirin** [comment]
I have next puzzle. That can not solve =)
These 2 sentences
![image](https://user-images.githubusercontent.com/16819743/151679142-9e926d47-9948-4778-8075-c1b29be58734.png)
![image](https://user-images.githubusercontent.com/16819743/151679160-b07d4771-a920-4434-b827-a553091cb63e.png)

And next function that from data (not principal data)
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Document xmlns="urn:iso:std:iso:20022:tech:xsd:pain.001.001.03" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:iso:std:iso:20022:tech:xsd:pain.001.001.03 pain.001.001.03.xsd">
...some xml data...
</Document>
```
Generating this result every time
```
9og0N3S3o51JOwLfoDgOTXHZOSDUja8sUVJnwX6uN/Q=
```

**Comment by terrafrost** [comment]
My guess is that you need to do an additional sha256 hash on the message itself. eg.

```php
        $rsa = new \phpseclib\Crypt\RSA();
        $rsa->setPassword($password);
        $rsa->loadKey($privateKey, \phpseclib\Crypt\RSA::PRIVATE_FORMAT_PKCS1);
        $rsa->setHash('sha256');
        $rsa->setMGFHash('sha256');
        $rsa->setSignatureMode(\phpseclib\Crypt\RSA::SIGNATURE_PSS);
        $sign = $rsa->sign(hash('sha256', $data, true));
```

**Comment by andrew-svirin** [comment]
Sign is very large =( than should be.

It is interesting that exists encoding EMSA_PSS
https://www.gnu.org/software/gnu-crypto/manual/api/gnu/crypto/sig/rsa/EMSA_PSS.html

May be similar exists in phpseclib?

**Comment by terrafrost** [comment]
phpseclib absolutely supports PSS signatures:

https://phpseclib.com/docs/rsa#rsasignature_pss

phpseclib has supported PSS signatures since the 1.0 version and, indeed, uses PSS signatures by default. Like unless you specifically specify the signature type to be PSS, phpseclib will default to PSS. This has actually caused some "problems" because PKCS1 signatures are a lot more common than PSS signatures.

What are you testing this out against? Maybe instead of me giving you code to test against you could just give me access to whatever it is that you're testing this against? I'm guessing it's some sort of API. Could you set me up on a sandbox?

**Comment by terrafrost** [comment]
And the reason I suggested doing a sha256 hash on the data prior to it's being passed to the sign method is because (1) the documentation says _with SHA-256 hash value as input_ and (2) it kinda looks like that's what https://github.com/railslove/epics is doing:

https://github.com/railslove/epics/blob/e2ef49bd1dcf6f73b295ee166bcdaf7fa0322ec4/lib/epics/generic_upload_request.rb#L46-L48
```
  def signature_value
    client.a.sign( digester.digest(document.gsub(/\n|\r/, "")) )
  end
```
Note how `digester.digest` is being called. `digester` is defined as `@digester ||= OpenSSL::Digest::SHA256.new`.

https://github.com/railslove/epics/blob/e2ef49bd1dcf6f73b295ee166bcdaf7fa0322ec4/lib/epics/signer.rb#L19-L27
```
  def sign!
    signature_value_node = doc.xpath("//ds:SignatureValue").first

    if signature_node
      signature_value_node.content = Base64.encode64(client.x.key.sign(digester, signature_node.canonicalize)).gsub(/\n/,'')
    end

    doc
  end
```
The `digest` method does `content_to_digest = Base64.encode64(digester.digest(doc.xpath("//*[@authenticate='true']").map(&:canonicalize).join)).strip`.

That said, keep in mind, prior to yesterday, I had never written a lick of Ruby in my life...

**Comment by andrew-svirin** [comment]
Hi, @terrafrost 
I dived too deep to find my problem with sign. Read what is PKCS, learned Java to execute their code (understood that it is separate pain to be Java developer). And found what the value I expected was .... simple sha256 hash. I was wonder after 3 weeks of research and did not expect that, because in request this digest was sent encrypted and in doc is written to send signature value of ESMA-PKCS1. But server do not analyse the field with value, I received error because this endpoint was broken absolutely. I found it when tried to combine hLen and sLen of different value to fit verify *sign* by public key, and data value, and by chance found that *sign* was simple hash sha256. 

And what I want to ask: ESMA-PKCS1 is equal with ? 
https://github.com/phpseclib/phpseclib/blob/2.0/phpseclib/Crypt/RSA.php#L2878 

where size is $size = mb_strlen($rsa->modulus, '8bit'); ? But this methods with underscore.

**Comment by terrafrost** [comment]
Nice detective work!

> And what I want to ask: ESMA-PKCS1 is equal with ?
https://github.com/phpseclib/phpseclib/blob/2.0/phpseclib/Crypt/RSA.php#L2878

It's used by PKCS1 signatures.

> where size is $size = mb_strlen($rsa->modulus, '8bit'); ?

phpseclib doesn't use the [mbstring extension](https://www.php.net/mbstring) because phpseclib's goal is to work with a minimal number of system dependencies. Some crypto libraries, however, do use it, in large part because some systems may use mbstring to ["overload" the regular string functions](https://www.php.net/manual/en/mbstring.overload.php). So like whereas normally `strlen('😀')`  would return 4 on a system with mbstring overloading `strlen('😀')` might return 1 or 2, which would completely break most cryptography libraries.  If you use `mb_strlen(..., '8bit')` you avoid this problem. But you'll have lowered portability if you do that and a shim would slow things down quite a bit.

phpseclib's solution is to just not support such systems at all. If you're using Composer to install phpseclib then bootstrap.php will be included, which throws an exception if mbstring overloading is enabled.
