### ISSUE TITLE
About Collecting total response over SSH

### ISSUE THREAD

**Issue by raghuveer** [phpseclib/phpseclib#1773]
Hi,

I have a usecase wherein, I have to run series of commands while capturing the outcome in a file/db based log.

My request is to understand if we can capture entire response of a SSH command till the next appearance of command prompt (to enter another SSH command)?

Please share your inputs

Thank you

**Comment by terrafrost** [comment]
The use case you describe is supported.

It'd be easiest to do `$output = $ssh->exec('commandA');` and `$output = $ssh->exec('commandB');` but if you do that the state will be lost between successive commands. Like if you do `$ssh->exec('cd /'); echo $ssh->exec('pwd');` then the directory it shows won't be `/` but rather `/home/neubert`.

If you want to get around this limitation you can use interactive read / write. eg.

```
$ssh->read('[prompt]');
$ssh->write("commandA\n");
$output = $ssh->read('[prompt]');
$ssh->write("commandB\n");
$output = $ssh->read('[prompt]');
```

**Comment by raghuveer** [comment]
Thank you @terrafrost 

I will try this.

I need to be able to run linux commands as well as shell scripts, php cli applications etc over SSH while transferring files in between using SFTP.

Logging the response of each command is required for respective teams, to later review the logs w.r.t. noted issues.

will try the suggested approach of read, write example.

Thank you

**Comment by raghuveer** [comment]
tried checking how much time it takes between two scenarios,

1) 
`$time_start = microtime(true);



$sftp->read('[prompt]');
$sftp->write("ls -la\n");
$output1 = $sftp->read('[prompt]');
echo "output1: " . $output1 . "\n";
$sftp->write("pwd\n");
$output2 = $sftp->read('[prompt]');
echo "output2: " . $output2 . "\n";  

$time_end = microtime(true);
$time = $time_end - $time_start;

echo "It took $time seconds to complete this activity\n";`

2) 
`$time_start = microtime(true);

$sftp->write("ls -la\n");
$sftp->write("pwd\n");
$sftp->setTimeout(5);
echo $sftp->read(); 


$time_end = microtime(true);
$time = $time_end - $time_start;

echo "It took $time seconds to complete this activity\n";`

I ran the above two code snippets, I got output in different timings,

Results are 30.02 seconds for the former and 5.16 seconds for the latter.

Note: if I comment the timeout of 5 seconds, the latter becomes 10 seconds tentatively for the latter.

I would request your inputs on two aspects,

1) Will it take more time when we collect output on command basis? I am worried if it will take many minutes or double the time when we run long running commands when compared to running commands as per "scenario 2" or directly on putty (SSH client)?

2) will the command and result be captured when collecting the output as per "scenario 1"? or any other way to seperate command and result?

@terrafrost request you to please check and share your inputs

Thank you

**Comment by raghuveer** [comment]
@terrafrost tried generating logs, but log is not being created. Shared code, by replacing server ip, filename and passphrase. I see command and execution outcome when I run the php file over a putty based SSH session.
`


//define('NET_SFTP_LOGGING', SFTP::LOG_SIMPLE);
define('NET_SFTP_LOGGING', 2);

$rsa_private_key = \phpseclib3\Crypt\PublicKeyLoader::load(file_get_contents('/home/username/.ssh/rsa_private_key.pem'), 'cccccccccccc');

$sftp = new \phpseclib3\Net\SFTP("xxx.xx.xx.xx", 22); // the port number is optional
//$sftp->login('root', $rsa_private_key);
$sftp_login = $sftp->login('root', $rsa_private_key);

if($sftp_login) {
		 echo "SFTP Login Success\n";
} else {
	echo "SFTP login Failure\n";
	
}

echo "<pre>";

$time_start = microtime(true);

$sftp->read('[prompt]');
$sftp->write("ls -la\n");
$output1 = $sftp->read('[prompt]');
echo "output1: " . $output1 . "\n";
$sftp->write("pwd\n");
$output2 = $sftp->read('[prompt]');
echo "output2: " . $output2 . "\n";  


/* $sftp->write("ls -la\n");
$sftp->write("pwd\n");
$sftp->setTimeout(5);
echo $sftp->read();  */  


$time_end = microtime(true);
$time = $time_end - $time_start;

echo "It took $time seconds to complete this activity\n";

//print_r($sftp->getLog());
echo $sftp->getLog();

`

please tell me, if I did something wrong? I remember able to generate logs when I tried back in February 2022. Not sure why it is not happening.

Thank you

**Comment by terrafrost** [comment]
Try `define('NET_SSH2_LOGGING', 2);`

**Comment by raghuveer** [comment]
@terrafrost started getting log after trying the above define statement.
[phpseclib-log-18-05-2022_18-30.txt](https://github.com/phpseclib/phpseclib/files/8716390/phpseclib-log-18-05-2022_18-30.txt)

The commands I ran are test ones and the above log is generated with the same linux commands.

Please check and share your inputs

Thank you

**Comment by terrafrost** [comment]
Looks like you're using digital ocean!

Anyway I'll take a look this evening, after work!

**Comment by terrafrost** [comment]
Try this:

```php
echo $ssh->read('[root@rockylinux-s-1vcpu-1gb-nyc3-01 ~]#');
$ssh->write("ls -la\n");
echo $ssh->read('[root@rockylinux-s-1vcpu-1gb-nyc3-01 ~]#');
$ssh->write("pwd\n");
echo $ssh->read('[root@rockylinux-s-1vcpu-1gb-nyc3-01 ~]#');
```

**Comment by raghuveer** [comment]
Tried the way you suggested, it took 0.26 seconds. Here is the log,
[phpseclib-log-19-05-2022_14-19.txt](https://github.com/phpseclib/phpseclib/files/8727545/phpseclib-log-19-05-2022_14-19.txt)


Then I had attempted to collect the outcome into variables and printed that using echo statements. 
`
echo $sftp->read('[root@rockylinux-s-1vcpu-1gb-nyc3-01 ~]#');
$sftp->write("ls -la\n");
$output1 = $sftp->read('[root@rockylinux-s-1vcpu-1gb-nyc3-01 ~]#');
echo "output1: " . $output1 . "\n";
$sftp->write("pwd\n");
$output2 = $sftp->read('[root@rockylinux-s-1vcpu-1gb-nyc3-01 ~]#');
echo "output2: " . $output2 . "\n";
  

`
This attempt took 0.23 seconds. here is the log,
[phpseclib-log-output_collected_19-05-2022_14-24.txt](https://github.com/phpseclib/phpseclib/files/8727556/phpseclib-log-output_collected_19-05-2022_14-24.txt)

 **Query:**

Does this mean I replace 
`
$ssh->read('[prompt]');
`
with
`
$ssh->read('[root@rockylinux-s-1vcpu-1gb-nyc3-01 ~]#');
`
???

My only thought is that, hardcoding might be troubling when compared to auto-identification, please share your thoughts

Thank you

**Comment by terrafrost** [comment]
> Then I had attempted to collect the outcome into variables and printed that using echo statements.
> 
> ```
> echo $sftp->read('[root@rockylinux-s-1vcpu-1gb-nyc3-01 ~]#');
> $sftp->write("ls -la\n");
> $output1 = $sftp->read('[root@rockylinux-s-1vcpu-1gb-nyc3-01 ~]#');
> echo "output1: " . $output1 . "\n";
> $sftp->write("pwd\n");
> $output2 = $sftp->read('[root@rockylinux-s-1vcpu-1gb-nyc3-01 ~]#');
> echo "output2: " . $output2 . "\n";
> ```

Well `'[root@rockylinux-s-1vcpu-1gb-nyc3-01 ~]#'` is exactly what's in your logs. From your logs:

```
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0293, network: 0.0001s)
00000000  00:00:00:02:00:00:00:29:5b:72:6f:6f:74:40:72:6f  .......)[root@ro
00000010  63:6b:79:6c:69:6e:75:78:2d:73:2d:31:76:63:70:75  ckylinux-s-1vcpu
00000020  2d:31:67:62:2d:6e:79:63:33:2d:30:31:20:7e:5d:23  -1gb-nyc3-01 ~]#
00000030  20
```
For test purposes let's keep just the hex encoding. We'll remove the offsets, spaces, printable raw bytes and the colons (`:`). That leaves us with this:

```
00000002000000295b726f6f7440726f636b796c696e75782d732d31766370752d3167622d6e7963332d3031207e5d2320
```
Now let's convert '[root@rockylinux-s-1vcpu-1gb-nyc3-01 ~]#' to hex with `bin2hex`. That [gives us](https://3v4l.org/aMS1r) `5b726f6f7440726f636b796c696e75782d732d31766370752d3167622d6e7963332d3031207e5d23`. If you do Ctrl + F you can see that that is a substring within the orig string.

What does `bin2hex('[root@rockylinux-s-1vcpu-1gb-nyc3-01 ~]#')` yield for you? If you're PHP file is being encoded with, say, UTF-16 LE then that could yield a different result. When I tried to save a PHP file with that encoding it didn't even recognize it as PHP (prob because that would turn `'<?php` into `"<\0?\0p\0h\0p\0"` but who knows how you're ultimately using the code. Like what I'm getting at is that the code your IDE is showing you may not be an accurate representation of how the code exists, byte for byte, on the file system.

Another example: Notepad, for Windows, doesn't show new lines (\n) when they're by themselves. They're just kinda invisible characters. Same thing with browsers. You put a [soft hyphen](https://en.wikipedia.org/wiki/Soft_hyphen) between two characters, let's say two instances of A, then the string length isn't 2 - it's 3 - even tho, visuaully, it appears to be 2.

> Does this mean I replace
> 
> ```
> $ssh->read('[prompt]');
> ```
> with
> 
> ```
> $ssh->read('[root@rockylinux-s-1vcpu-1gb-nyc3-01 ~]#');
> ```
> ???

Correct.

> My only thought is that, hardcoding might be troubling when compared to auto-identification, in code maintenance perspectives know?

I mean, I guess you could put it into a config.php file, if you're concerned about it.

The thing is...  in an interactive shell the server can send data to you at any time and vice versa. You can't send data too fast either.

Like if you ssh into a machine via the CLI or via PuTTY, you normally don't type commands until you see the prompt. If you're running a command that you don't think should take a long time and are not seeing the prompt you might hit Ctrl + C before you try to type in the next command. And what if you run a command like vim or nano? At that point the prompt isn't visible so you know that what you're typing in isn't going to be interpreted by bash - it'll be interpreted by vim or nano.

Like if you type in vim, wait for vim to load, go into interactive mode by hitting `i` on the keyboard, and then type in `ls -latr` and then hit Enter you're not going to get a directory listing because that's not how vim is interpreting that sequence of characters.

`$ssh->read()` / `$ssh->write()` attempt to run commands and read output in this environment. It's not really intended to be used in an automated manner (`$ssh->exec()` would be better) but it can be. Kinda like how screen scraping a website is suboptimal compared to accessing an API but if no API is available then ya gotta do what ya gotta do.

So how do you recognize the prompt? I mean, I guess you could use a regular expression but idk what the optimal regular expression for prompt detection would be. Your prompt looks like `'[root@rockylinux-s-1vcpu-1gb-nyc3-01 ~]#'`. Mine looks like `root@ubuntu-s-1vcpu-1gb-nyc3-01:~#`. So like yours has square brackets around it, mine doesn't, and yours has a space between the nyc3-01 and the tilde (~) and mine doesn't.

But let's say you had a regex that was absolutely perfect for recognizing the prompt. It wouldn't work 100% of the time. It couldn't. Like let's say you type in `vim filename.ext` on the command line and hit enter. And let's further say that filename.ext has the prompt within it. At that point doing `$ssh->read()` for the prompt would return a false positive.

If you really want to work around this issue you should strongly consider `$ssh->exec()`. There are differences between `$ssh->exec()` and interactive shells however. Like with `$ssh->exec()` doing `$ssh->exec('cd /');` and then `echo $ssh->exec('pwd');`...  on the CLI doing `pwd` after `cd /` would return `/` but `$ssh->exec()` is stateless. The state of the system at the end of one call to that method doesn't effect the state of the system on the next call to that method. The state does not persist across multiple `$ssh->exec()` calls. You can work around this by doing either `$ssh->exec('cmdA && mdB');` or `$ssh->exec('cmdA; cmdB');`.

> P.S. for first read statement, I see last login date & time along with failed login count etc, as shown below,
> 
> ```
> Activate the web console with: systemctl enable --now cockpit.socket
> 
> Last failed login: Thu May 19 08:51:35 UTC 2022 from 168.227.78.229 on ssh:notty
> There were 14 failed login attempts since the last successful login.
> Last login: Thu May 19 08:48:11 2022 from 104.131.41.154
> ```

Shouldn't make a difference. Here's some relevant source code from SSH2::read():

https://github.com/phpseclib/phpseclib/blob/62c36daa672eaf735ab49e11406bbf675a69680c/phpseclib/Net/SSH2.php#L2871-L2874

Doing `strpos('aba', 'b')` returns a integer, despite b being in the middle of the string and phpseclib uses `strpos` in `$ssh->read()`.

**Comment by raghuveer** [comment]
@terrafrost Thanks a lot for the detailed response.

While I thought to store username & server references for the use with read() method, I need to connect to multiple servers with different usernames, and whose privileges are different (i.e., while some have sudo privileges, some others donot, as they represent normal users).

Thinking, probably, I need to start collecting the server hostname, in addition to the username, that is considered at present.

But as you pointed out, collecting username and server hostname might not be enough, as symbols around also have their significance, need to check how to handle this situation.

**Comment by terrafrost** [comment]
> Since you use strpos, can I consider using username@server_hostname for the read prompt, that info I will collect and store in the database for re-use as per need, when connecting to different servers over SSH?

That'd work for my SSH server and yours! idk if that'd work for all possible prompts, however. One way to find out, I guess lol

That said, it might be better to do `$ssh->exec()` instead of `$ssh->read()` / `$ssh->write()`. I guess to help you out with that it would be helpful to know what commands you're running (presumably you're doing more than just `ls -la` and `pwd` lol). Posting on superuser.com or serverfault.com might be useful as well.

**Comment by raghuveer** [comment]
The goal is to run series of commands, trigger scripts etc...

In my previous attempt used exec() in adhoc way, to perform SFTP operations. As you suggested to try multiple operations in single exec() call, I will use exec() or read() & write() combinations as per need and to fit the purpose.

I have one another query,

can we "display live output" in web browser (if required), while also being able to save the output in filesystem/database kind of? Can we do this only with exec() only or using a combination of read() & write() methods?

while I wanted to ask this point, came across this aspect in https://www.sitepoint.com/phpseclib-securely-communicating-with-remote-servers-via-php/

@terrafrost 
please share your inputs

thank you

**Comment by terrafrost** [comment]
> can we "display live output" in web browser (if required), while also being able to save the output in filesystem/database kind of? Can we do this only with exec() only or using a combination of read() & write() methods?

This should do the trick:

```php
$ssh->exec('ping 127.0.0.1', function($str) {
    echo $str;
    //if (strpos($str, 'icmp_seq=5') !== false) {
    //    return true;
    //}
});
```
That said, if you run it via the web browser you may need to [flush](http://php.net/flush) the output buffer and even then YMMV.

The commented out code shows how you could use a callback method to return early based on whatever your criteria might be. ie. if the callback method returns bool(true) then exec() will return early.

**Comment by raghuveer** [comment]
While there is a feature request if I can show the response on web browser, I didnot plan that earlier as I intended to do using message queue workers. I asked you to understand the situations just incase

Thanks a lot @terrafrost
