### ISSUE TITLE
Where do the packets that set the attributes come from? 

### ISSUE THREAD

**Issue by DD77-cloud** [phpseclib/phpseclib#1798]
I have an issue with SFTP version being set to 3 and the attributes NET_SFTP_ATTR_CREATETIME and NET_SFTP_ATTR_ACCESSTIME being set to on causing the _parseTime function to error out. 

Now are those setting set by the server or the client? As i understand it they are retrieved via the _send_sftp_packet function? 

Thanks.

**Comment by terrafrost** [comment]
The server sets them.

In #1708 WS_FTP was sending SSH_FILEXFER_ATTR_CREATETIME and SSH_FILEXFER_ATTR_MODIFYTIME, which are only used in SFTP v4/5/6, even tho phpseclib was using SFTP v3. But that was fixed in 3.0.12+, 2.0.35+ and 1.0.20+.

What version of phpseclib are you using? What's the server you're connecting to? You can get the server by doing `echo $sftp->getServerIdentification()`. Also, can you provide the SFTP logs? You can get those by doing `define('NET_SFTP_LOGGING', 2);` at the top and `echo $sftp->getSFTPLog()` after you get the error.

Thanks!

**Comment by DD77-cloud** [comment]
> The server sets them.
> 
> In #1708 WS_FTP was sending SSH_FILEXFER_ATTR_CREATETIME and SSH_FILEXFER_ATTR_MODIFYTIME, which are only used in SFTP v4/5/6, even tho phpseclib was using SFTP v3. But that was fixed in 3.0.12+, 2.0.35+ and 1.0.20+.
> 
> What version of phpseclib are you using? What's the server you're connecting to? You can get the server by doing `echo $sftp->getServerIdentification()`. Also, can you provide the SFTP logs? You can get those by doing `define('NET_SFTP_LOGGING', 2);` at the top and `echo $sftp->getSFTPLog()` after you get the error.
> 
> Thanks!

Thank you very much the fix mentioned in that ticket (https://github.com/phpseclib/phpseclib/commit/40035dc59c33fdf32d716b0804495104c54b5105) resolved the issue!
Terribly sorry about the delay but took a while to get the confirmation that that's what we've been looking for.
