### ISSUE TITLE
php-xml dependency of phpseclib

### ISSUE THREAD

**Issue by mrvanes** [phpseclib/phpseclib#1817]
We are using phpseclib as a dependency of JumboJett's OIDC implementation and one of our OIDC providers uses ES256 keys, that can't be parsed by phpseclib.

It would be nice if, in the future, phpseclib (and thus JumboJett OIDC implementation) would support these keys.

The (OIDC) jwks endpoint returns:
```
{"keys": [{"kty": "RSA", "use": "sig", "kid": "Mjg2VVRmSVE4NnltSU5EZGZlOEVSOUxfWDR3SXhXOHpCRkZsdkNZeGl2RQ", "n": "sjXai4YYpBY-Bg9YqxPMAuAqk-bSgoo4X0XRmlKmnpvgTo6npvhBQk7xqnXRrW7MAtPYAS66psCpVlltEFCx1g6qo_NzMvQZeIskXLvZvdoBL7Hs5nBFlt0uaRCbAHvQvvta5TIhEcZvqo8u0R60viq7GGwtJum2EZinXm_Nsk02OvlO_2bdC1yz_uFIECpi35lPx2SLSz6aIa746LoHcnnuJI_jXgai8EDULJ8KkHRCkFLV4ju0CcqYWKNe327F4fZLJ_UEWA17fU3r_iBEPfUpfjWLv_v1LoOLwjxFfSr1E6FMow78R2ed-up7Yfkn-ucQxXch5_kQh_Ie9ZpCsw", "e": "AQAB"}, {"kty": "EC", "use": "sig", "kid": "bEE1UDdHZHI3MVRoUW9WTmxmVUh1OG1SaVk5NW5ERDdWRHhTSDJCeGh2QQ", "crv": "P-256", "x": "M46i3bnHoDJ0hRNNoPEwNZVkSsnHfHRVhlHELhktPBQ", "y": "XnT-yuoZnbZ3-M3HQYZ6GuJGI0nTygaxfuQaM67J_RI"}]}
```

And phpseclib says "Unable to read key", raised in PublicKeyLoader.php on line 68.

**Comment by terrafrost** [comment]
Looks like the [JSON Web Key](https://datatracker.ietf.org/doc/html/rfc7517) format. idk a ton about it but I'll try to take a look this week as time permits and will post back here my thoughts!

**Comment by mrvanes** [comment]
Yes, OIDC is based on jwt and jwks, JumboJett creates an xml to load the keys with phpseclib.
This is where I suppose JumboJett prepares and calls PublicKeyLoader:
https://github.com/jumbojett/OpenID-Connect-PHP/blob/master/src/OpenIDConnectClient.php#L980

**Comment by mrvanes** [comment]
Never mind, php-xml was missing on the test server.
Would have been nice if composer would have warned when installing phpseclib since it's phpseclib that chokes on the missing xml parser I guess?

**Comment by terrafrost** [comment]
Oh. Yah - the libxml extension is required.

Some extensions - like PCRE and Hash - are core extensions and are always enabled and can't be disabled. I thought libxml was, similarly, a core extension, but I guess it isn't. Per https://www.php.net/manual/en/dom.requirements.php it's enabled by default and there's no discussion of how to disable it (altho one could surmise that doing `--disable-libxml` might do the trick idk) but I guess it can be.

I guess this does change from version to version too. Like per https://www.php.net/manual/en/hash.installation.php the Hash extension has been enabled by default since PHP 5.1.2 but it didn't become a core extension until PHP 7.4.0. https://www.php.net/manual/en/pcre.installation.php doesn't mention a version in which PCRE became a core extension so one can surmise, for that one, that it always has been (altho I suppose a look at archive.net would be fruitful).

Anyway, I'll make a code change to check if the libxml extension is present and, if not, to not even try to load XML formatted private keys.

I'll write shims for some things but writing a pure PHP shim for libxml is a gargantuan undertaking that I am not prepared to do. And tbh I doubt anyone would be because 99.9% of PHP installs have that extension installed and it's hard to justify that level of effort if the number of people installing it is going to be sooooo incredibly low.

Would JSON Web Key support still be useful? If OIDC is _based_ on JSON Web Key that may mean that it is subtly different than JSON Web Key as well...

**Comment by mrvanes** [comment]
Thanks for your elaborate answer.
I would never expect you to write your own shim for libxml, what I meant to say was: "All is well after installing php-xml package" (this is Debian 11, btw). What I suggested was making php-xml module a (composer) requirement of phpseclib, so that composer would scream at me when installing JumboJett OIDC implementation (and phpseclib as a dependancy) if that's even possible to express in a composer package?

OIDC is based on oAuth and uses JWT's and JWKS to do (and check) the signing. The link to JumboJett repo shows how that maintainer forges an xml key from the jwks document it found. It may be worth looking into parsing jwks keys natively, but I can't decide that for you.

**Comment by terrafrost** [comment]
I don't want to make php-xml a dependency in composer.json because then you won't be able to use _any_ part of phpseclib if you don't have it installed when, in reality, the only part of phpseclib that'll be affected by this is it's ability to load XML formatted keys.

> it's phpseclib that chokes on the missing xml parser

I'm not sure I'd call returning false the same thing as chocking, unless I'm misunderstanging things? Looking at the source code I see that all the XML key loaders throw an exception if DOMDocument doesn't exist as a class:

```php
        if (!class_exists('DOMDocument')) {
            throw new BadConfigurationException('The dom extension is not setup correctly on this system');
        }
```
PublicKeyLoader catches these exceptions and returns false if every key loader class throws an exception. The exceptions are useful in case you want to load a specific key format and want to see why it's not loading.

> OIDC is based on oAuth and uses JWT's and JWKS to do (and check) the signing. The link to JumboJett repo shows how that maintainer forges an xml key from the jwks document it found. It may be worth looking into parsing jwks keys natively, but I can't decide that for you.

I'll try to add it as time permits. Hopefully this week, like I said earlier.

Thanks!

**Comment by mrvanes** [comment]
I think I would have been helped better with the exception instead of a false from PublicKeyLoader because it led me into thinking something was wrong with the key type, instead of it's wrapper.

**Comment by terrafrost** [comment]
So I did some preliminary work on supporting JSON Web Keys but I'm also trying to add support for encrypted OpenSSH private keys and I'm pretty close to that and don't want to lose inertia on that. I do intend on adding support for JSON Web Keys however.

As for PublicKeyLoader throwing an exception vs returning false...  the problem with that is that is how PublicKeyLoader works. It basically just brute forces the key type. It tries to load the key as a PKCS1 key. Does the PKCS1 plugin throw an exception? If so then move onto the PKCS8 plugin. Does that throw an exception? Then move onto the PuTTY plugin, etc. It keeps on trying different format plugins until it finds one that doesn't throw an exception.

Using that approach PublicKeyLoader wouldn't throw just one exception - it'd throw a whole lot of exceptions, which obviously doesn't work. I suppose I could catch each exception, concatenate all the messages from each one and turn that into a big giant super exception but idk how useful that'd be.

**Comment by terrafrost** [comment]
My work on encrypted OpenSSH private keys has concluded:

https://github.com/phpseclib/phpseclib/commit/0c8994bbadffd45cd979a1354258b14ec68a025d

I'm gonna take about a week to work on another non-phpseclib related project (whilst still providing general phpseclib support) and then I'll try to work on adding JSON Web Keys support to 3.0 / master.

Thanks!

**Comment by terrafrost** [comment]
https://github.com/phpseclib/phpseclib/commit/0b3c6e27fcdd58d747cea054d536e319a38ca5be adds JWK support.

Sorry about the delay.

I also still need to add X25519 and X448 support as well.

Right now it supports RSA and P-256, P-384, P-521, secpk256k1, Ed25519 and Ed448. You can load JWK keys or create them by doing `$key->toString('JWK')`. If you want to add parameters like use or kid you can do it thusly:

```php
$key->toString('JWK', [
    'use' => 'enc',
    'kid' => '1'
]);
```
