### ISSUE TITLE
SFTP works on command line with PubkeyAcceptedKeyTypes ssh-rsa

### ISSUE THREAD

**Issue by yogeshbb** [phpseclib/phpseclib#1865]
From my ubuntu 22 I am able to connect to Azure Blob as:
`sftp -o PubkeyAcceptedKeyTypes=+ssh-rsa -i [private_key] [username]@[host]`
But with phpseclib 3.0.17
```php
$sftp = new SFTP($host);
$t=$sftp->login($username, $host, PublicKeyLoader::loadPrivateKey(file_get_contents($private_key)));

//OR

$t=$sftp->login($username, PublicKeyLoader::loadPrivateKey(file_get_contents($private_key)));
```
unable to connect, error I am getting is:
`SSH_MSG_USERAUTH_FAILURE`

My private key goes like `-----BEGIN OPENSSH PRIVATE KEY-----` ..

**Comment by terrafrost** [comment]
Can you do this and tell me what the output is?:

```php
echo \phpseclib3\Crypt\RSA::loadFormat('OpenSSH', '...');
```

As is, a few possibilities exist:

- OpenSSH private keys can contain multiple keys but phpseclib only supports OpenSSH keys with one key
- it's possible some cipher other than aes256-ctr is being used or another kdf other than bcrypt is being used (altho if OpenSSH supports any other algorithms for keyrs that'd be news to me)
- it's possible the checkint's don't match
- etc

**Comment by terrafrost** [comment]
It looks like the key is being loaded by phpseclib correctly. At this point the next step would be to try to understand what's going at the SSH-layer. To do so three approaches could be taken.

1. I could try to debug by proxy. I ask you to get log files and based on that I may ask you to add debug code and that cycle continues until I figure out what the issue is. The problem with this method is that if it takes you 2-3 days to respond and then it takes me 2-3 days to respond this can wind up dragging on for weeks.

2. You could provide me an SSH / SFTP login and private key that demonstrate the problem. You can email the info to terrafrost@php.net if you're up for that.

3. I could try to reproduce the issue myself. Doing anything with Azure's SFTP offering is a PITA. I last played around with Azure in #1821 and I hated it. Plus, at the time I used the free tier but that's only available for a limited time and now I guess enough time has passed that I have to use the pay-as-you-go subscription and unless you're going to be reimbursing me then I'm a bit loathe to do this, the fact that I feel like it's a time waster notwithstanding (since learning Azure isn't my goal here). Like because my free tier expired I'd have to re-figure out how to enable SFTP, which is going to take time, and then I'll have to figure out what I never did figure out in #1821 - why I was getting errors when trying to get public key logins. I could see days being wasted on this. And unlike the first option where the bulk of the time is spent waiting for the other person to reply, in this case, the bulk of the time would be spent with me trying to learn a UI that, with luck, I'll never have to re-use ever again.

Of these options I'd prefer the second option! If you could provide me with that info that'd be cool.

**Comment by terrafrost** [comment]
Also, I apologize for the delay - between the fact that I was vacationing in Europe (I live in Texas), my trying to work on another phpseclib feature that's prob gonna take months, a late Thanksgiving celebration (I got back to Texas late on Thanksgiving day and celebrated Thanksgiving with my family on Back Friday) and just dread regarding the prospect of working with the Azure UI's, my response was a bit delayed.

Apologies!

**Comment by terrafrost** [comment]
I was able to create an SFTP instance on Azure and am able to reproduce the issue with phpseclib. PuTTY does not have the issue but, honestly, I think PuTTY is behaving inappropriately, per https://stackoverflow.com/q/74590919/569976.

I also do not believe Azure is behaving appropriately BUT....  none-the-less, try this:

https://github.com/terrafrost/phpseclib/tree/1865-3.0

(the latest commit in that branch should "fix" the issue)

**Comment by terrafrost** [comment]
I emailed the creator of PuTTY to understand why it's behaving the way it's behaving and got this response back:

> The mechanisms for the use of rsa-sha2-512 in _server_ authentication
(the client checking the server's host key), and in _user_
authentication (the user proving their identity to the client) are
completely different, and not connected to each other.
>
> Because host keys are negotiated by both sides listing all the
algorithms they support, it's easy. Each side independently announces
which set of RSA variants it can handle, and they pick according to the
client's preference order, and conduct the key exchange.
>
> But this has nothing at all to do with _user_ authentication. It sounds
as if you're assuming that the client would detect the server's support
for rsa-sha2-512 _in general_ from its presence in the host key
algorithm list in particular. But that can't work, in general - what if
the server only has some other kind of host key, like Ed25519? Then the
host key list wouldn't tell the client what it needed to know for
userauth.
>
> So instead, there's a completely different mechanism for the server to
communicate a willingness to accept SHA-2 based RSA signatures in user
authentication. It's done by using the RFC 8303 SSH_MSG_EXT_INFO
mechanism, and including "server-sig-algs" in its EXT_INFO packet.
>
> If your server is presenting rsa-sha2-512 as one of its host keys, but
is either not implementing RFC 8303 at all or not sending a
"server-sig-algs" list, then that would explain what you're seeing.

If that were the correct interpretation then one would think that RFC8332 should mention RFC8303 but it doesn't. Maybe an errata against the RFC should be opened but it's neither here nor there, I suppose. I believe the code change in the branch I linked to should fix the issue, all the same. LMK if it does indeed work for you and I'll merge it into the 1.0 / 2.0 / 3.0 / master branches.

Thanks!

**Comment by yogeshbb** [comment]
> I was able to create an SFTP instance on Azure and am able to reproduce the issue with phpseclib. PuTTY does not have the issue but, honestly, I think PuTTY is behaving inappropriately, per https://stackoverflow.com/q/74590919/569976.
> 
> I also do not believe Azure is behaving appropriately BUT.... none-the-less, try this:
> 
> https://github.com/terrafrost/phpseclib/tree/1865-3.0
> 
> (the latest commit in that branch should "fix" the issue)

@terrafrost Sure I will try this and update you. Thank you for digging up in to the issue!
