### ISSUE TITLE
Sockets not removed properly

### ISSUE THREAD

**Issue by M393** [phpseclib/phpseclib#1871]
With each sftp connection a new socket is added to the process but they don't seem to be removed after destruction.
Do I need to call a method to properly clean things up?

The script runs continuously as a service. The list grows until the process reaches its fd limit, then it is crashes. Restarting it periodically works as a workaround, but if possible I'd like to avoid that.
```sh
root@webserver:/proc/3393/fd# ls -lv
total 0
lr-x------ 1 root root 64 Dec  5 15:58 0 -> /dev/null
l-wx------ 1 root root 64 Dec  5 15:58 1 -> /dev/null
l-wx------ 1 root root 64 Dec  5 15:58 2 -> /dev/null
lrwx------ 1 root root 64 Dec  5 15:58 4 -> 'socket:[634567327]'
lrwx------ 1 root root 64 Dec  5 15:58 5 -> 'socket:[634567329]'
lrwx------ 1 root root 64 Dec  5 15:58 6 -> 'socket:[634567331]'
lrwx------ 1 root root 64 Dec  5 15:58 7 -> 'socket:[634567333]'
lrwx------ 1 root root 64 Dec  5 15:58 8 -> 'socket:[634566500]'
lrwx------ 1 root root 64 Dec  5 15:58 9 -> 'socket:[634567337]'
lrwx------ 1 root root 64 Dec  5 15:58 10 -> 'socket:[634567339]'
lrwx------ 1 root root 64 Dec  5 15:58 11 -> 'socket:[634566569]'
lrwx------ 1 root root 64 Dec  5 15:58 12 -> 'socket:[634566644]'
```
php 7.2.24-0ubuntu0.18.04.15
phpseclib 3.017

Thanks for any help.

**Comment by terrafrost** [comment]
In Net/SSH2.php, `__destruct()` calls `disconect()`, which in turn, does this:

```php
        if (is_resource($this->fsock) && get_resource_type($this->fsock) === 'stream') {
            fclose($this->fsock);
        }
```

That said, I tried to duplicate the issue without success. Here's my code:

```php
<?php
$fsock = fsockopen('website.com', 22);
fclose($fsock);
sleep(600);
```

I got the process id by doing `ps aux | grep test.php` and I then did `ls -lv` in the `/proc/{pid}/fd` directory and I didn't see any socket files in that directory. I _did_ see a socket file if I commented out the `fclose($fsock)` line but not otherwise.

Maybe you could do `get_resource_type($this->fsock)` just before that if statement to see what it says?

I'm honestly kinda wondering if this isn't some PHP 7.2 bug that newer versions have fixed.

**Comment by M393** [comment]
I narrowed it down to the `SFTP` destructor not being called.
Probably because `WeakReference` [is only available from php 7.4 on](https://www.php.net/manual/en/class.weakreference.php).
Calling `disconnect` in my own code will remove the socket and  then the destructor will also run.

**Comment by terrafrost** [comment]
Ah - yah - #1672 talks about the introduction of WeakReferences.

**Comment by M393** [comment]
Ok, thanks.
Calling disconnect is no problem. Hopefully I can upgrade the PHP version soon.
