### ISSUE TITLE
php 5.3 compatibilty for branch 2.0 release 2.41 

### ISSUE THREAD

**Issue by jinraynor1** [phpseclib/phpseclib#1883]
Hi there, I'm getting  few array declaration error for older php 5.3 due to short array syntax

- File: phpseclib/Net/SSH2.php
line: 2748

         $algos = ['rsa-sha2-256', 'rsa-sha2-512', 'ssh-rsa'];

- File: phpseclib/Net/SFTP.php
line: 926

         $afterPWD = $beforePWD = [];

**Comment by terrafrost** [comment]
https://github.com/phpseclib/phpseclib/commit/ad7a7d5c8f0288d7d30af2120987d7574bf202d6 fixes this.

I also moved phpseclib over to GitHub Actions instead of Travis CI. GitHub As part of that migration phpseclib 2.0 is now subject to continuous integration tests on PHP 5.3 (the square array syntax was introduced in PHP 5.4) so hopefully snafu's like this won't happen again.

Thanks!
