### ISSUE TITLE
How to get all ANSI in callback

### ISSUE THREAD

**Issue by jjp0714** [phpseclib/phpseclib#1890]
**when run exec Callbacks**

**code:**
```
$cmd = "PACFILE=/var/www/deploy-web/.pac/config-staging.sh pac deploy run";
$ssh->exec($cmd, function ($message) {
	echo $message;
});

```
**result:**
```
>> Deploying ...
[42;37m /usr/bin/php7.4 vendor/bin/phpunit [0m
PHPUnit 9.6.3 by Sebastian Bergmann and contributors.

FAILURES!
Tests: 1, Assertions: 2, Failures: 1.
[45;37m >>>>>>>>>>>>>>>Tests FAILED!<<<<<<<<<<<<<<< [0m
```

**when run code with enablePTY and read:**

**code:**
```
$cmd = "PACFILE=/var/www/deploy-web/.pac/config-staging.sh pac deploy run";
$ssh->enablePTY();
$ssh->exec('passwd');
echo $ssh->read();
```

**result:**
```
>> Deploying ...
[42;37m /usr/bin/php7.4 vendor/bin/phpunit [0m
PHPUnit 9.6.3 by Sebastian Bergmann and contributors.

[37;41mFAILURES![0m
[37;41mTests: 1[0m[37;41m, Assertions: 2[0m[37;41m, Failures: 1[0m[37;41m.[0m
[45;37m >>>>>>>>>>>>>>>Tests FAILED!<<<<<<<<<<<<<<< [0m
```

**It can be found that when enablePTY is used, the two lines "FAILURES" and "Tests: 1, Assertions: 2, Failures: 1." in the result will have ANSI styles. How do I get these ANSI styles in Callbacks?** 

These problems have troubled me for many days, I need everyone's help.

**Comment by terrafrost** [comment]
This is a PHPUnit thing - not a phpseclib thing. In reviewing PHPUnit's [TextUI/DefaultResultPrinter.php](https://github.com/sebastianbergmann/phpunit/blob/9.6.3/src/TextUI/DefaultResultPrinter.php#L469) I see that this is ultimately due to this:

https://github.com/sebastianbergmann/environment/blob/3fade0c8462024d0426a00dc1ad0a2fda0df733f/src/Console.php#L55-L77

Maybe , if `stream_isatty` or `posix_isatty` are not defined on your system, you could define them and have them return true. It's a bit hackish but, in looking at the PHPUnit / Environment source code I'm not sure what else you can do. Well, you could post on the PHPUnit issue tracker and see if a new version could make it changeable.

**Comment by jjp0714** [comment]
> 
Thanks for your reply, maybe I got confused. 
According to your ideas, I will go to find more documents about PHPUnit.

**Comment by jjp0714** [comment]
> This is a PHPUnit thing - not a phpseclib thing. In reviewing PHPUnit's [TextUI/DefaultResultPrinter.php](https://github.com/sebastianbergmann/phpunit/blob/9.6.3/src/TextUI/DefaultResultPrinter.php#L469) I see that the behavior you describe is ultimately due to this:
> 
> https://github.com/sebastianbergmann/environment/blob/3fade0c8462024d0426a00dc1ad0a2fda0df733f/src/Console.php#L55-L77
> 
> Maybe , if `stream_isatty` or `posix_isatty` are not defined on your system, you could define them and have them return true. It's a bit hackish but, in looking at the PHPUnit / Environment source code I'm not sure what else you can do. Well, you could post on the PHPUnit issue tracker and see if a new version could make it changeable.

// 连接到远程服务器
$ssh = new \phpseclib\Net\SSH2('example.com');

// 登录到服务器
$ssh->login('username', 'password');

// 执行命令，并使用闭包获取输出结果
$ssh->exec('ls', function($stream) {
    // 获取输出结果
    $output = '';
    while ($data = $stream->read(1024)) {
        $output .= $data;
    }

    // 处理输出结果
    echo $output;
});
