### ISSUE TITLE
Fix CVE-2023-27560 in version 2.0.41

### ISSUE THREAD

**Issue by simonberger** [phpseclib/phpseclib#1893]
[CVE-2023-27560](https://github.com/advisories/GHSA-hm7p-r324-hhf3) has been filed and fixed in 3.0.19 but it is still, as far as I have seen, unfixed in version 2 and at least there is no none conflicting release available.

https://github.com/Roave/SecurityAdvisories started blocking requirements to version 2 completely for everyone using this security package.

**Comment by terrafrost** [comment]
It is not fixed in the 2.0 branch because it is _not_ an issue in the 2.0 branch. 

Quoting the CVE:

> Math/PrimeField.php in phpseclib through 2.0.41 has an infinite loop with composite primefields.

That file does not even exist in the 2.0 branch and never has:

https://github.com/phpseclib/phpseclib/tree/2.0.41/phpseclib/Math https://github.com/phpseclib/phpseclib/tree/2.0/phpseclib/Math

2.0 does not implement PrimeFields nor does it implement any feature that would even make use of them (eg. elliptic curves, GCM, UHASH) and I am not going to be backporting any of those features to the 2.0 branch.

Regardless, I did release phpseclib 2.0.42. Obviously it doesn't include a fix for this non-issue but I also recognize that this situation is liable to cause disruption, all the same, and that releasing a new version, altho it ought not be necessary, does resolve the issue.

**Comment by terrafrost** [comment]
I did open up a PR against `Roave/SecurityAdvisories` to fix this here:

https://github.com/Roave/SecurityAdvisories/pull/108

They closed it because "_This project only contains a `composer.json` from upstream reported advisories, generated every hour: you will need to contact the author of the upstream advisory instead, and get it adjusted_".

I have been in contact with the people who opened up the original CVE and am trying to get them to update it (altho whether or not it's even possible to update an existant CVE is unclear to me).

**Comment by simonberger** [comment]
Thank you for the information and the quick fix for the current situation. :)
