### ISSUE TITLE
Make compatible with PHP8 by releasing the change from master-branch as 3.0

### ISSUE THREAD

**Issue by PatchRanger** [phpseclib/phpseclib#1915]
Hello.

I've discovered that `random_compat` blocks me from upgrading to PHP8.
I found that the master-branch of the phpseclib contains the change I need, getting rid of the random_compat-dependency: https://github.com/phpseclib/phpseclib/commit/97902d4bd37000bdd6ca7ffef366af3cc0de65d0#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34 .

Could you please port this change into the 3.0-branch?

**Comment by terrafrost** [comment]
On my local system I'm running PHP 8.2.3 and had no issues installing phpseclib 3.0 from scratch. It installed random_compat v9.99.100. After I did this brand new fresh install I ran some test code (connecting to an SSH2 server and doing `echo $ssh->exec('ls -latr');`) without any issue.

I then switched things up a bit. I used Composer to install phpseclib 3.0 from scratch on PHP 5.6.29. This resulted in random_compat v2.0.21 being installed.  I then tried to run the same test code as before on it with PHP 8.2.3 and had no issues.

`Random::string()`, which Net/SSH2.php calls, is basically a thin wrapper around `random_bytes`, which is what `random_compat` provides, at least on PHP 5.6, which is the only version of PHP that phpseclib 3.0 supports that doesn't have `random_bytes` built in.

Additionally, on GitHub Actions, phpseclib 3.0 is unit tested from PHP 5.6 all the way to PHP 8.2 and altho you may see periodic failures due to `phpseclib3\Tests\Unit\File\X509\CRLTest::testCreateCRL` or periodic segfaults on PHP 5.6 (https://github.com/phpseclib/phpseclib/pull/1766#issuecomment-1066232504 elaborates) the unit tests pass.

So what issues are you having with phpseclib 3.0 on PHP 8.0+? 'cause I'm not having any issues.

Also, as `random_compat` is what enables phpseclib 3.0 to work on PHP 5.6, dropping it as a dependency would create a BC break for people using PHP 5.6. Sure, I suppose it's fair to ask how many people are using phpseclib 3.0 PHP 5.6, but, regardless, phpseclib 3.0 is an LTS version. If I'm going to break BC, for _anyone_, I better have a gosh darned good reason. Like if I'm gonna break BC without good reason then how is that any different then me changing the namespace from phpseclib3\ to terrafrost\?
