### ISSUE TITLE
Error when downloading large file (3.5GB) - Expected NET_SFTP_DATA or NET_SFTP_STATUS. Got packet type:

### ISSUE THREAD

**Issue by IanFo1** [phpseclib/phpseclib#1934]
I am trying to download a large file (3.5GB) but I am getting a thrown error: `Expected NET_SFTP_DATA or NET_SFTP_STATUS. Got packet type: `.  I have seen a few issues on here that are similar but the solutions didn't work for me.  I have attached the logging I was able to get which lead me to believe this is a different issue.  Is the file size just a limitation I cannot work around or could I try something else?  Is there away I could possibly loop the download to re-establish the connection as it might be timing out since this is such a large file?  Right now I am just running the `get` method to download the file.

[Results of the getLog method](https://github.com/phpseclib/phpseclib/files/12431834/SFTPLog.txt)

phpseclib version: 3.0.21

The methods `getErrors` and `getSFTPErrors` where empty arrays and the following constants where defined:
`define('NET_SSH2_LOGGING', SSH2::LOG_COMPLEX); define('NET_SFTP_LOGGING', SSH2::LOG_COMPLEX);`

**Comment by terrafrost** [comment]
I'll try to take a look at this this weekend.

Thanks!

**Comment by IanFo1** [comment]
I managed to find some other setup methods to extend my timeout and I managed to get this to work.  It took about an hour to download the file but I got it.  Sorry for the extra stress and not reading the code thoroughly.  For reference, the following settings helped me get the file but I don't know which one or combination I needed.  I could probably optimize it more but I don't really have the time.  If you have any suggestions to get it down from 1 hour I can try them.

```
        $oSFTP = new SFTP($cHost);
        $oSFTP->login($cUserName, $cPassword);
        $oSFTP->sendKEXINITLast();
        $oSFTP->setTimeout(0);
        $oSFTP->setKeepAlive(5);
        $oSFTP->enableDatePreservation();
        $oSFTP->get($cSFTPPath, $cLocalPath)
```

For some extra info and strangeness, I am downloading a lot of large files and something weird happened.  The 3.5GB file I talked about in my first issue only took 10 minutes while a 2.2GB file took the 1 hour.  My guess is that the server I am connecting to isn't sending back the information needed to refresh the connection?  Not sure if you have seen that before but let me know if you have any thoughts, if you have the time.

**Comment by terrafrost** [comment]
I was able to download a 5.1GB file without issue just now.

> Is there away I could possibly loop the download to re-establish the connection as it might be timing out since this is such a large file?

In theory this should work:

```php
// truncate existing file (if one exists)
$fp = fopen('local.file', 'w');
ftruncate($fp, 0);
fclose($fp);

// download file in 10mb chunks
$fp = fopen('local.file', 'a');
$size = $sftp->filesize('remote.file');
while (fstat($fp)['size'] < $size) {
	$sftp->get('remote.file', $fp, fstat($fp)['size'], 10 * 1024 * 1024);
}
```
Unfortunately, that doesn't work in the latest version because of https://github.com/phpseclib/phpseclib/commit/320c43a4a0ff8838dc810c61b90e7b62d3c0d060 . So like the issue is fixed in the latest git version of each branch (1.0, 2.0, 3.0, master) but not in the latest released version.

I still want to go through the logs but I got hung on on a silly typo w.r.t. the afore mentioned commit last night. But, from your latest post...  my guess is `$oSFTP->setTimeout(0)` is prob what helped. None of the packets seem excessively slow but when you have a whole lot of packets I guess natural network latency can begin to add up. When I did my 5.1GB transfer I was doing so from a network on localhost so there was pretty much zero network latency.

Anyway, that's my best guess at the moment in lieu of having gone through your logs!
