### ISSUE TITLE
Deprecation notices 8.2

### ISSUE THREAD

**Issue by waplet** [phpseclib/phpseclib#2013]
- Creation of dynamic property phpseclib3\Crypt\RSA\PublicKey::$publicExponent is deprecated
- Creation of dynamic property phpseclib3\Crypt\Hash::$blockSize is deprecated

I see PrivateKey has `publicExponent` but PublicKey doesn't. 

calling

```
$rsa = RSA::loadPublicKey([
            'e' => new BigInteger(base64_decode((string) $secretParams['e']), 256),
            'n' => new BigInteger(base64_decode((string) $secretParams['n']), 256),
        ])->withPadding(RSA::ENCRYPTION_PKCS1);
```

**Comment by terrafrost** [comment]
What version of phpseclib are you running? I'd hazard to guess that you're probably running an out of date version of phpseclib.

https://github.com/phpseclib/phpseclib/commit/0b9b0074c9a7e593b9af1efebd3c31293ce76bce added `$publicExponent` to RSA.php, which, in turn, is what RSA\PublicKey.php extends. That same commit added `$blockSize` to Hash.php.

It looks like those lines have been been present in every version of phpseclib since [3.0.15](https://github.com/phpseclib/phpseclib/releases/tag/3.0.15), which was released in Sept 2, 2022.

**Comment by waplet** [comment]
Oh, yeah, sorry, it indeed it 3.0.14 i am using now.
