### ISSUE TITLE
Maximum execution time exceeded in version 3.0.38

### ISSUE THREAD

**Issue by liborm85** [phpseclib/phpseclib#2020]
Version 3.0.38 changed behavior for execution time.

If multiple exec commands are run in version 3.0.38 (or 3.0.39) is throw error maximum execution time exceeded. It works correctly in version 3.0.37.

Example for reproduce problem (sleep 1 simulate more difficult command):
```php
<?php

set_time_limit(30);

$sftp = new \phpseclib3\Net\SFTP('host', 22, 60);
$sftp->login('login', 'password');
$sftp->setTimeout(0);

$idx = 0;
do {
    $sftp->exec('sleep 1; echo test;');
    var_dump($idx);

    $idx++;
} while ($idx < 60);

echo 'OK';
```

Correct output in version 3.0.37:
```
int(0) int(1) int(2) int(3) int(4) int(5) int(6) int(7) int(8) int(9) int(10) int(11) int(12) int(13) int(14) int(15) int(16) int(17) int(18) int(19) int(20) int(21) int(22) int(23) int(24) int(25) int(26) int(27) int(28) int(29) int(30) int(31) int(32) int(33) int(34) int(35) int(36) int(37) int(38) int(39) int(40) int(41) int(42) int(43) int(44) int(45) int(46) int(47) int(48) int(49) int(50) int(51) int(52) int(53) int(54) int(55) int(56) int(57) int(58) int(59) OK
```

Maximum execution time exceeded throw in version 3.0.38 or 3.0.39:
```
int(0) int(1) int(2) int(3) int(4) int(5) int(6) int(7) int(8) int(9) int(10) int(11) int(12) int(13) int(14) int(15) int(16) int(17) int(18) int(19) int(20) int(21) int(22) int(23) int(24) int(25) int(26) int(27)
Fatal error: Maximum execution time of 30 seconds exceeded in /vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php on line 3554
```

**Comment by terrafrost** [comment]
First, apologies for the delay. I traveled to Japan from Texas for a week on vacation and just got back.

Second, I'm not able to duplicate the issue on either 3.0.38 or 3.0.39. When I do `define('NET_SSH2_LOGGING', 3)` on 3.0.39 I get this between each loop:

```
-> NET_SSH2_MSG_CHANNEL_OPEN (since last: 0.0005, network: 0s)
00000000  00:00:00:07:73:65:73:73:69:6f:6e:00:00:00:01:7f  ....session.....
00000010  ff:ff:ff:00:00:40:00                             .....@.

<- NET_SSH2_MSG_CHANNEL_OPEN_CONFIRMATION (since last: 0.14, network: 0s)
00000000  00:00:00:01:00:00:00:00:00:00:00:00:00:00:80:00  ................

-> NET_SSH2_MSG_CHANNEL_REQUEST (since last: 0.0006, network: 0.0001s)
00000000  00:00:00:00:00:00:00:04:65:78:65:63:01:00:00:00  ........exec....
00000010  13:73:6c:65:65:70:20:31:3b:20:65:63:68:6f:20:74  .sleep 1; echo t
00000020  65:73:74:3b                                      est;

<- NET_SSH2_MSG_CHANNEL_WINDOW_ADJUST (since last: 0.0497, network: 0s)
00000000  00:00:00:01:00:20:00:00                          ..... ..

<- NET_SSH2_MSG_CHANNEL_SUCCESS (since last: 0.0005, network: 0s)
00000000  00:00:00:01                                      ....

<- NET_SSH2_MSG_CHANNEL_REQUEST (since last: 1.0058, network: 0s)
00000000  00:00:00:01:00:00:00:0b:65:78:69:74:2d:73:74:61  ........exit-sta
00000010  74:75:73:00:00:00:00:00                          tus.....

<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0006, network: 0s)
00000000  00:00:00:01:00:00:00:05:74:65:73:74:0a           ........test.

<- NET_SSH2_MSG_CHANNEL_EOF (since last: 0.0005, network: 0s)
00000000  00:00:00:01                                      ....

<- NET_SSH2_MSG_CHANNEL_CLOSE (since last: 0.0003, network: 0s)
00000000  00:00:00:01                                      ....

-> NET_SSH2_MSG_CHANNEL_CLOSE (since last: 0.0013, network: 0.0002s)
00000000  00:00:00:00                                      ....
```
Which is what I'd expect.

What do you get between each loop?

For that matter I'm curious what `echo $ssh->getServerIdentification()` returns for you.

**Comment by liborm85** [comment]
Server identification is: `SSH-2.0-OpenSSH_7.9p1 Debian-10+deb10u2`

Log one loop (version 3.0.39):

```
-> NET_SSH2_MSG_CHANNEL_OPEN (since last: 0.0001, network: 0s)
00000000  00:00:00:07:73:65:73:73:69:6f:6e:00:00:00:01:7f  ....session.....
00000010  ff:ff:ff:00:00:40:00                             .....@.

<- NET_SSH2_MSG_CHANNEL_OPEN_CONFIRMATION (since last: 0.0417, network: 0s)
00000000  00:00:00:01:00:00:00:00:00:00:00:00:00:00:80:00  ................

-> NET_SSH2_MSG_CHANNEL_REQUEST (since last: 0.0002, network: 0s)
00000000  00:00:00:00:00:00:00:04:65:78:65:63:01:00:00:00  ........exec....
00000010  13:73:6c:65:65:70:20:31:3b:20:65:63:68:6f:20:74  .sleep 1; echo t
00000020  65:73:74:3b                                      est;

<- NET_SSH2_MSG_CHANNEL_WINDOW_ADJUST (since last: 0.0006, network: 0s)
00000000  00:00:00:01:00:20:00:00                          ..... ..

<- NET_SSH2_MSG_CHANNEL_SUCCESS (since last: 0.0002, network: 0s)
00000000  00:00:00:01                                      ....

<- NET_SSH2_MSG_CHANNEL_DATA (since last: 1.004, network: 0s)
00000000  00:00:00:01:00:00:00:05:74:65:73:74:0a           ........test.

<- NET_SSH2_MSG_CHANNEL_REQUEST (since last: 0.0002, network: 0s)
00000000  00:00:00:01:00:00:00:0b:65:78:69:74:2d:73:74:61  ........exit-sta
00000010  74:75:73:00:00:00:00:00                          tus.....

<- NET_SSH2_MSG_CHANNEL_EOF (since last: 0.0001, network: 0s)
00000000  00:00:00:01                                      ....

<- NET_SSH2_MSG_CHANNEL_CLOSE (since last: 0.0001, network: 0s)
00000000  00:00:00:01                                      ....

-> NET_SSH2_MSG_CHANNEL_CLOSE (since last: 0.0001, network: 0s)
00000000  00:00:00:00                                      ....
```

**Comment by terrafrost** [comment]
I note that in your log these are switched from mine:

```
<- NET_SSH2_MSG_CHANNEL_REQUEST (since last: 1.0058, network: 0s)
00000000  00:00:00:01:00:00:00:0b:65:78:69:74:2d:73:74:61  ........exit-sta
00000010  74:75:73:00:00:00:00:00                          tus.....

<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0006, network: 0s)
00000000  00:00:00:01:00:00:00:05:74:65:73:74:0a           ........test.
```
The problem with that is that idk how to make it so OpenSSH behaves as yours is.

I could try to analyze how that would work and try to guess at possible fixes when I'm not at work (today's my first day back since I got back from my Japan vacay) but that's liable to be time consuming and potentially not super effective. Being able to actually reproduce the problem would be super helpful.

Could you maybe give me SSH access to the server that's having the issue? If you'd be willing to do that you could email the login info to terrafrost@php.net.

Thanks!

**Comment by liborm85** [comment]
Sorry, I can't give you access because it's the employer's server, which is only accessible from internal network.

In log from version 3.0.37 I have also request and data switched and it doesn't cause problem:
```
-> NET_SSH2_MSG_CHANNEL_OPEN (since last: 0.0001, network: 0s)
00000000  00:00:00:07:73:65:73:73:69:6f:6e:00:00:00:01:7f  ....session.....
00000010  ff:ff:ff:00:00:40:00                             .....@.

<- NET_SSH2_MSG_CHANNEL_OPEN_CONFIRMATION (since last: 0.0406, network: 0.0001s)
00000000  00:00:00:01:00:00:00:00:00:00:00:00:00:00:80:00  ................

-> NET_SSH2_MSG_CHANNEL_REQUEST (since last: 0.0002, network: 0s)
00000000  00:00:00:00:00:00:00:04:65:78:65:63:01:00:00:00  ........exec....
00000010  13:73:6c:65:65:70:20:31:3b:20:65:63:68:6f:20:74  .sleep 1; echo t
00000020  65:73:74:3b                                      est;

<- NET_SSH2_MSG_CHANNEL_WINDOW_ADJUST (since last: 0.0007, network: 0s)
00000000  00:00:00:01:00:20:00:00                          ..... ..

<- NET_SSH2_MSG_CHANNEL_SUCCESS (since last: 0.0001, network: 0s)
00000000  00:00:00:01                                      ....

<- NET_SSH2_MSG_CHANNEL_DATA (since last: 1.0036, network: 0.0001s)
00000000  00:00:00:01:00:00:00:05:74:65:73:74:0a           ........test.

<- NET_SSH2_MSG_CHANNEL_EOF (since last: 0.0002, network: 0s)
00000000  00:00:00:01                                      ....

<- NET_SSH2_MSG_CHANNEL_REQUEST (since last: 0.0001, network: 0s)
00000000  00:00:00:01:00:00:00:0b:65:78:69:74:2d:73:74:61  ........exit-sta
00000010  74:75:73:00:00:00:00:00                          tus.....

<- NET_SSH2_MSG_CHANNEL_CLOSE (since last: 0.0003, network: 0s)
00000000  00:00:00:01                                      ....

-> NET_SSH2_MSG_CHANNEL_CLOSE (since last: 0.0002, network: 0.0001s)
00000000  00:00:00:00                                      ....
```

**Comment by liborm85** [comment]
I did a little research.

If I test version 3.0.39 with high set_time_limit everything we call via sftp works correctly, then maybe won't be problem with switch request/data (when both versions do it). Only time limit is not "prolonged".

I don't fully understand how phpseclib connection works internally, but I researched this: 
- in version 3.0.37 is call `stream_select` if not set keepAlive (see [SSH2.php#L3515](https://github.com/phpseclib/phpseclib/blob/3.0.37/phpseclib/Net/SSH2.php#L3515)),
- but in version 3.0.39 is call `$this->send_keep_alive()` (see [SSH2.php#L3544](https://github.com/phpseclib/phpseclib/blob/3.0.39/phpseclib/Net/SSH2.php#L3544)) where is not call `stream_select` (see [SSH2.php#L4377](https://github.com/phpseclib/phpseclib/blob/3.0.39/phpseclib/Net/SSH2.php#L4377))

According to PHP documentation [set_time_limit](https://www.php.net/manual/en/function.set-time-limit.php) stream operations is not counted to limit. That's why I think call `stream_select` to waiting caused "waititing" not to be counted to limit.

But maybe my idea is wrong.

**Comment by terrafrost** [comment]
So I was able to reproduce the issue. `set_time_limit(30)` is the culprit. I guess I failed to copy / paste that when I tried to run my earlier test.

That said, I think the current behavior is correct. That PHP wasn't timing out for you before is quite surprising tbh. It times out for me on phpseclib 3.0.37.

Can you post your `php -i` output? Maybe I'll be able to reproduce the phpseclib 3.0.37 behavior you're describing if I can match the version of PHP you're using. Like maybe one possibility is that the version of PHP you're using has a bug in it that results in `set_time_limit(30)` not always behaving as one would expect and later versions of PHP changed it? Or maybe it works one way on Windows and differently on Linux?

Either way your `php -i` output will enable me to more faithfully reproduce your setup and will hopefully enable me to give a more meaningful response.

**Comment by liborm85** [comment]
I test everything on linux.
(According to [documentation](https://www.php.net/manual/en/function.set-time-limit.php) counting limits on Windows works differently.)

Primarily used PHP 8.1.28:
[php-info-8.1.txt](https://github.com/user-attachments/files/16359960/php-info-8.1.txt)

Same behavior is also on PHP 7.4.26:
[php-info-7.4.txt](https://github.com/user-attachments/files/16359961/php-info-7.4.txt)

**Comment by liborm85** [comment]
Tested example script on Windows 11 now and both versions throws Maximum execution time exceeded.

Documentation [say:](https://www.php.net/manual/en/function.set-time-limit.php)
> The set_time_limit() function and the configuration directive [max_execution_time](https://www.php.net/manual/en/info.configuration.php#ini.max-execution-time) only affect the execution time of the script itself. Any time spent on activity that happens outside the execution of the script such as system calls using [system()](https://www.php.net/manual/en/function.system.php), stream operations, database queries, etc. is not included when determining the maximum time that the script has been running. **This is not true on Windows where the measured time is real.**

If you're trying it on Windows, there really hasn't been any change in versions. It only shows up on linux, where time is calculated differently.

**Comment by terrafrost** [comment]
Interesting. I did not know that. Nice sleuthing!

That said, altho I do recognize that this is a BC breaking change, I do think this new behavior is more intuitive. I try my darndest not to break BC between minor releases, however, as https://xkcd.com/1172/ kinda hints at, sometimes that's unavoidable.

The current behavior was introduced to resolve some other underlying issues (#1993) but apparently it had the unintended side effect of fixing another issue I didn't even know about. Like phpseclib ought to behave the same way on Linux as it does on Windows, which it now does, but didn't, before. Like with the 3.0.37 behavior I don't think it'd be all that unreasonable for someone to submit a bug report on the inconsistent behavior and what I do then?

If I make Windows behave like Linux I'm introducing a BC breaking change for Windows users and if I make Linux work like Windows (which is apparently what was done) then I'm introducing a BC breaking change for Linux. If the only fix to this issue is going to possibly break someone's workflow I'd rather the workflow be broken in such a way that the new behavior is the more intuitive behavior and I think the way it's behaving _now_ on Linux is the more intuitive behavior, even if it is a BC break.

Like at this point I'm kinda damned if I do and damned if I don't.

All in all, altho I am glad to have been made aware of this issue / change I think imma keep phpseclib's current behavior.

Could you just do `set_time_limit(0)` or `set_time_limit(60)` or some such?

**Comment by liborm85** [comment]
> Like with the 3.0.37 behavior I don't think it'd be all that unreasonable for someone to submit a bug report on the inconsistent behavior and what I do then?

The question is whether it is more intuitive and can someone create a bug report when would it really be considered as bug. Because PHP itself is inconsistent in this, if counting time limit different on platforms.
My opinion is that linux users expect time limit to be suspended and windows users don't expect that. I think Linux users will be a little surprised by this new behavior.


> If I make Windows behave like Linux I'm introducing a BC breaking change for Windows users and if I make Linux work like Windows (which is apparently what was done) then I'm introducing a BC breaking change for Linux. 

I don't think any change back in this would be BC breaking change for Windows, because as I wrote above link to PHP documentation, time limit on Windows works differently - it is always a real time from start of script. I.e. any call to exec, system, stream operations does not "suspend" time limit like on linux. For windows users everything would still work as before.


> Could you just do set_time_limit(0) or set_time_limit(60) or some such?

Yes, this is last option. It will probably cause problems in use case with downloading/uploading large files because there is time unexpected, where somehow in linux it is expected that the script will wait.


I understand what was solved in https://github.com/phpseclib/phpseclib/issues/1993. If possible, I would plead for the original behavior with a time limit to be implemented in this new solution, because it won't be breaking change for windows and it will more closely match the behavior of generic php.

I leave the decision up to you. Thanks for replies.

**Comment by terrafrost** [comment]
> My opinion is that linux users expect time limit to be suspended and windows users don't expect that. I think Linux users will be a little surprised by this new behavior.

My thought is that - assuming that they even encounter this issue - that they may be surprised from the BC break but that this new behavior would be more intuitive for people who've never used phpseclib before or any functionality of phpseclib that relied on this behavior.

Kinda like...   a DVORAK keyboard may technically have a superior layout to QWERTY keyboard but I grew up learning how to use a QWERTY keyboard. Like if I was learning to type from scratch I could read up on both layouts and make a decision unencumbered by accumulated experiences but, as is, I'm not learning to type from scratch and I do have pre-conceived notions of where keys ought to be.

Maybe given time more people will voice their opinion and maybe that'll change my mind but right now I'm gonna let the new behavior stand.

I am sorry for the inconvenience to you. BUT FWIW I am most impressed by your sleuthing and I really do want to applaud you for that!!

**Comment by rposky** [comment]
There does seem to be a bug here. After all, stream functions are still being used in a blocking way, such that maximum execution time should continue to be discounted on Linux.

What I think the culprit may be here, is that we're not actually allowing a wait to occur on the socket stream, and we're continuously looping until packet receipt within `get_binary_packet`. #1993 also introduced `get_stream_timeout`, which defaults to `sec=0, msec=0` if the user has not supplied a timeout in the way of `setTimeout` or a keep-alive interval, the case in the above example.

Testing with the following yields an immediate return, while updating to use `stream_set_timeout($fsock, -1, -1)` can forever block without triggering the time limit.
`set_time_limit(1);
$fsock = fsockopen('127.0.0.1', 22);
stream_set_timeout($fsock, 0, 0);
stream_get_contents($fsock);
echo "DONE\n";`

The use of `stream_set_timeout` to clear a stream timeout is not documented. I had presumed `stream_set_timeout($fsock, 0, 0);` to have that effect. But as we allow for mutability in timeout via `setTimeout`, we do need some means of clearing it, since a user can always provide an initial timeout and then remove it. I would hesitate to update to use `-1` values if they are not documented as removing the timeout, or unless we can find some evidence to the contrary in the PHP stream source. Alternatively, we could default to PHP_INT_MAX, which would not be truly unlimited, but it would outlive any of us.

**Comment by liborm85** [comment]
I tested this behavior in more detail and even now time is calculated differently in linux and windows because with linux there is still partial blocking as writes @rposky. Now it's a bit of chaos. So it's no longer a different behavior (respectively unified behavior with windows), but a bug, it needs to be fixed with `stream_set_timeout` or otherwise.

We have locked phpseclib to version 3.0.37 on our projects until this bug is resolved.

**Comment by terrafrost** [comment]
Well for what it's worth I'm still not convinced that it's a bug.

Like it sounds like @rposky is suggesting that `$ssh->setTimeout(0)` should trump `set_time_limit(30)`? Assuming that that's a correct interpretation then idk that I agree tbh.

That `set_time_limit()` behaves differently seems more like a consequence of the way php-src implements it.

Consider `openssl_random_pseudo_bytes`. That function was introduced in PHP 5.3.0 and from PHP 5.3.0 to PHP 5.3.3, inclusive, that function could block on Windows. http://php.net/ChangeLog-5.php#5.3.4 kinda hints at this it's "possible blocking behavior" entry for PHP 5.3.4. So why did it block on Windows? Was it a bug? Nope. It was a consequence of the syscall's that they used.

Here's what it did before PHP 5.3.4:

```
#ifdef WINDOWS
        RAND_screen();
#endif
```
Source: https://github.com/php/php-src/blob/80926568f19901678754d37e3b4039ad2b1ffb48/ext/openssl/openssl.c#L4909

Here's what it did after PHP 5.3.4:

```
#ifdef PHP_WIN32
	strong_result = 1;
	/* random/urandom equivalent on Windows */
	if (php_win32_get_random_bytes(buffer, (size_t) buffer_length) == FAILURE){
		efree(buffer);
		if (zstrong_result_returned) {
			ZVAL_BOOL(zstrong_result_returned, 0);
		}
		RETURN_FALSE;
	}
#else
```
(`mcrypt_create_iv` had already been calling `php_win32_get_random_bytes` so they just made `openssl_random_pseudo_bytes` behave the same way as `mcrypt_create_iv`)

If `php_win32_get_random_bytes` didn't already exist it would have been a lot more difficult for the PHP core devs to fix the issue. Maybe they wouldn't have.

In the case of `set_time_limit()` it seems to me that, like I said, it's just a consequence of the syscalls that they're using - that it's not an endorsement of one behavior or another. Maybe it's possible to work around the syscalls behavior with a lot of effort (hence why it hasn't been done) or maybe it's not possible to work around the syscalls behavior (at which point it hasn't been done because it can't be done). But neither of these interpretations assume that it's by design.

Even in phpseclib `$ssh->setTimeout(5)` doesn't work well with `$ssh->exec('sleep 10')`. Like idk what you'd expect from that but what I'd expect is that `$ssh->exec('sleep 10')`would return after 5s instead of 10s. #1440 talks about this in more detail. And if I could easily change that behavior I would, in a heartbeat. That it behaves like that is _not_ by design and likewise suspect that `set_time_limit()`'s behavior is not by design either.

**Comment by rposky** [comment]
My understanding of the issue is really irrespective of `set_time_limit`. It just so happens to be a good way to detect it. 

When a user requests unlimited blocking read/writes through `setTimeout(0)`, we are not relaying that same intent though `stream_set_timeout`. By using args `sec=0,msec=0`, we're setting up the stream functions to be non-blocking, with immediate return. We're thus doing all of the "blocking" in our own loop implementation, hence `set_time_limit` behaving differently, as we're putting the CPU through substantially more cycles.

**Comment by rposky** [comment]
I opened #2023 in response to this thread, which I think will also help to drive home the point I'm trying to make above.

**Comment by terrafrost** [comment]
Good catch rposky! That's been merged.

Also, like I said in that ticket, I do apologize for the delay - I'm attending Black Hat USA this week but left a few days early to get some sight seeing in so I've been distracted. I also don't normally travel this much lol - I was in Japan when the ticket was first created and now I'm elsewhere lol

**Comment by terrafrost** [comment]
3.0.40, which includes the `setTimeout(0)` fix, has been released!
