### ISSUE TITLE
SSH not working since 3.0.38, getting ConnectionClosedException on login

### ISSUE THREAD

**Issue by simPod** [phpseclib/phpseclib#2028]
I have seen some SSH fixes in 3.0.41 but it is still not working. I create ssh connection and when calling `login()`, it fails with ConnectionClosedException after specified timeout 3s.

```php
$connection = new SSH2($host, 22, 3);
$connection->enablePTY();
$connection->setWindowSize(1000, 2_147_483_647);
$connection->login($u, $p);
```

v 3.0.37 works fine.

<details>
  <summary>Click to expand log details</summary>

```
<-
...  SSH-1.99-Cisco-1
...                                      .25.

->
...  SSH-2.0-phpsecli
...  b_3.0 (libsodium
...  , openssl, gmp).
...

-> NET_SSH2_MSG_KEXINIT (since last: 0.7129, network: 0s)
...

<- NET_SSH2_MSG_KEXINIT (since last: 0.0001, network: 0s)
...

-> NET_SSH2_MSG_KEXDH_GEX_REQUEST (since last: 0.0031, network: 0s)
...

<- NET_SSH2_MSG_KEXDH_GEX_GROUP (since last: 1.6925, network: 1.6924s)
...

-> NET_SSH2_MSG_KEXDH_GEX_INIT (since last: 0.0411, network: 0s)
...

<- NET_SSH2_MSG_KEXDH_GEX_REPLY (since last: 0.5341, network: 0.5339s)
...

-> NET_SSH2_MSG_NEWKEYS (since last: 0.003, network: 0.0001s)


<- NET_SSH2_MSG_NEWKEYS (since last: 0.0002, network: 0s)


-> NET_SSH2_MSG_SERVICE_REQUEST (since last: 0.0037, network: 0s)
...  ....ssh-userauth

-> NET_SSH2_MSG_DISCONNECT (since last: 0.126, network: 0s)
...
```

</details>

**Comment by rposky** [comment]
The provided log trace suggests traversing the "bad key size" error handler in `login_helper`, which handler alters an internal key size setting and then reconnects, to accommodate an [old bug](https://bugzilla.mindrot.org/show_bug.cgi?id=1291).

You've confirmed receiving a `ConnectionClosedException` error, but could you also provide the exception message? Furthermore, can you also provide log output for the same test executed on v3.0.37?

**Comment by terrafrost** [comment]
It's unclear how long the `fsockopen()` is taking, how long the `SSH-1.99-Cisco-1.25` packet took or how long the `NET_SSH2_MSG_SERVICE_ACCEPT` is taking but with the inbound `NET_SSH2_MSG_KEXDH_GEX_GROUP` and `NET_SSH2_MSG_KEXDH_GEX_REPLY` packets taking, collectively, 2.2266s, if the rest are taking, collectively, 0.7734s or longer then the behavior your describing seems quite correct.

I created a new branch that'll include how long `fsockopen()` and the identification packet (`SSH-1.99-Cisco-1.25` in your case) took:

https://github.com/terrafrost/phpseclib/tree/3.0-enhanced-logging

Maybe you could try that out and report back on what it says?

That said, it's quite impossible to know how long the `NET_SSH2_MSG_KEXDH_GEX_REPLY` packet took from the logs since it would appear that phpseclib is timing out before that packet is received. Perhaps you could make the timeout longer so that we can get a better idea of how long `NET_SSH2_MSG_KEXDH_GEX_REPLY` is taking?

Also, I note that the logs are redacted. If you want to share the non-redacted logs you could send them to terrafrost@php.net.

That said, don't discount @rposky's input - he implemented the rewritten timeout code. If you did share the unredacted log to my email (and if rposky were to email me) would you be okay if I shared the unredacted logs with him, as well?

**Comment by terrafrost** [comment]
I think I've figured this out.

In 3.0.37 `get_binary_packet()` only subtracted from `$this->curTimeout` when `$skip_channel_filter` was true. eg. `get_binary_packet(true)`. It is true in `get_channel_packet()` but not in any of the calls in `key_exchange()`. Consequently, none of the packets in the key exchange actually count against the timeout.

In 3.0.38 `get_binary_packet()` was updated to not even use `$skip_channel_filter`. Because of that key exchange packets now _do_ count against the timeout.

The old behavior was wrong - the new behavior is correct.

**Comment by simPod** [comment]
@terrafrost aight, so the correct migration guide would be to increase the timeout? Or should I share logs?

**Comment by terrafrost** [comment]
> aight, so the correct migration guide would be to increase the timeout?

Yah - that's what I'd say.

> Or should I share logs?

At this point I don't think there's a need for that.

Thanks!

**Comment by simPod** [comment]
Looks like it has a positive effect, thanks!
