### ISSUE TITLE
Add support for DSA

### ISSUE THREAD

**Issue by BT643** [phpseclib/phpseclib#216]
Just wondered if DSA is on the list of requested features?

Would be so handy to have and would mean we could use this project for absolutely everything we need it for! 

I realise it's probably low on the list of priorities though.

**Comment by garak** [comment]
:+1: for supporting ECDSA

**Comment by ZeroCenter** [comment]
Its good, here is java xml sign, is that mean will support it.

http://weistar.iteye.com/blog/1982979

**Comment by terrafrost** [comment]
@ZeroCenter - your request probably ought to be a new post instead of a reply to an existing one.

Anyway, the XML in that blog post contains an RSA key - not a DSA key. phpseclib should be able to read that RSA key and create an RSA object from it that can be used to perform signature verification or encryption. That said, phpseclib doesn't currently support XML signatures. You could /use/ phpseclib to verify an XML signature but it's not something phpseclib does out of the box.

Also, I'm going to close this. DSA has been implemented in the master branch. ECDSA is being worked on (I have pretty much all the prime short weierstrass curves implemented [eg. the SEC curves, the brainpool curves, etc] and am working on Ed25519 / Ed448 support right now).
