### ISSUE TITLE
Implement chacha20-poly1305@openssh.com SSH2 transport cipher

### ISSUE THREAD

**Issue by bantu** [phpseclib/phpseclib#397]
Available since OpenSSH 6.5 - http://www.openssh.com/txt/release-6.5

This is probably almost as fast as arcfour128 while being a lot more secure and should possibly replace all the "rather weak" arcfour ciphers. I have not taken a too deep look into this, though.

Also see #396

**Comment by bantu** [comment]
RFC7465 now prohibits the use of RC4 in TLS.

**Comment by paragonie-scott** [comment]
It's also side-channel resistant. :+1:

Do you need help with this one?

**Comment by bantu** [comment]
> Do you need help with this one?

Feel free to (help) implement this via libsodium. I believe this will be a bit more complex than https://github.com/phpseclib/phpseclib/pull/755/files?w=0 though.

**Comment by terrafrost** [comment]
I'd prefer this be implemented as it's own stand-alone cipher. eg. Crypt/ChaCha20.php or some such. Certainly libsodium could be used if it's available on the system (as indeed `sha256()` is used in the 1.0 branch on systems using suhosin) but - and especially in the case of symmetric ciphers - I don't want support for symmetric ciphers being added to SSH2.php that don't natively exist in phpseclib.

I don't mind libsodium being used as much for #755 since there's currently no framework in place for any sort of DH / ECDH within phpseclib. But in this case there is a framework for symmetric ciphers to be added. They go in the Cipher/ directory.

It's definitely more work but half the idea of phpseclib is that it doesn't require dependencies. Like mcrypt's increasing obsolescence isn't a huge issue for phpseclib since it doesn't /need/ mcrypt. I suppose libsodium wouldn't be a dependency per say since it could very well only be used if it's available but I also don't want to hack up Net/SSH2.php, making it so it either uses a Crypt/*.php file or a libsodium instance.

Basically, I think it ought to be done right or not done at all and I don't think bypassing the existing framework and just hacking in a one-off solution into Net/SSH2.php is doing it right.

**Comment by mcarbonneaux** [comment]
a first approch ?!
https://github.com/fpoirotte/pssht/blob/master/src/ChaCha20.php 
https://github.com/fpoirotte/pssht/blob/master/src/Poly1305.php

**Comment by terrafrost** [comment]
Looks impressive! Not just ChaCha20 / Poly1305 but the whole thing! I'm actually most impressed by the compression. I didn't even think it'd be possible without a pure-PHP implementation of the algorithm:

https://github.com/phpseclib/phpseclib/wiki/GSoC-Ideas

But it looks like that uses the PECL-only HTTP extension and I generally assume that PECL extensions have about zero-deployment.

Still, it's pretty impressive!

**Comment by mcarbonneaux** [comment]
her is a pure php deflate algorithm in php : http://www.phpconcept.net/pclzip i think no ?!!
