### ISSUE TITLE
Use login option

### ISSUE THREAD

**Issue by Anahkiasen** [phpseclib/phpseclib#452]
I have a command that I need to execute with ssh's `--login` option but I can't find a way to emulate that via phpseclib, is that not possible or did I miss it somewhere ?

For the note, the reason I need this is because I need RVM to be loaded when I execute my commands but without it that won't work.

**Comment by vijin0404** [comment]
I was struggling with this issue and like to post a vote of thanks for info regarding appending "bash -lc".

**Comment by lukepolo** [comment]
I also am having this issue, @terrafrost is there a option to load these now with some configuration option ?

**Comment by terrafrost** [comment]
If you have questions you should probably post them in tickets that haven't already been closed ;)

That said, it works fine for me. My Vagrantfile:

```
Vagrant.configure("2") do |config|
	config.vm.box = "ubuntu/trusty64"
	config.vm.provision "shell", inline: <<-SHELL
 		echo vim > /home/vagrant/.bashrc
	SHELL
end
```

My PHP script (running 1.0.5):

```php
<?php
include('Net/SSH2.php');

$ssh = new Net_SSH2('127.0.0.1', 2200);
$ssh->login('vagrant', 'vagrant');

echo $ssh->exec('ls -latr');
```

Output:

```
~
~
~
~
~                              VIM - Vi IMproved
~
~                                version 7.4.52
~                           by Bram Moolenaar et al.
~           Modified by pkg-vim-maintainers@lists.alioth.debian.org
~                 Vim is open source and freely distributable
~
~                        Become a registered Vim user!
~                type  :help register<Enter>   for information
~
~                type  :q<Enter>               to exit
~                type  :help<Enter>  or  <F1>  for on-line help
~                type  :help version7<Enter>   for version info
~
~
~
~
~
                                                              0,0-1         All
```

Here's what I get if I replace `exec()` with this:

```php
$ssh->enablePTY();
$ssh->exec('ls -latr');
$ssh->setTimeout(5);
echo $ssh->read();
```

```
~
~
~
~
~                              VIM - Vi IMproved
~
~                                version 7.4.52
~                           by Bram Moolenaar et al.
~           Modified by pkg-vim-maintainers@lists.alioth.debian.org
~                 Vim is open source and freely distributable
~
~                           Sponsor Vim development!
~                type  :help sponsor<Enter>    for information
~
~                type  :q<Enter>               to exit
~                type  :help<Enter>  or  <F1>  for on-line help
~                type  :help version7<Enter>   for version info
~
~
~
~
~
                                                              0,0-1         All
```

It looks pretty much exactly the same except the colors are different (which I guess means that the ANSI escape codes are different).

Here's what I get if I replace the `exec` with this:

```php
$ssh->write("ls -latr\n");
echo $ssh->read();
```

```
 -latr

~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
-- INSERT --                                                  2,1           All
```

So, long story short, .bashrc is working fine for me. I'm actually a little surprised it's working for `$ssh->exec()` without a PTY but whatever.

That said, in general, when it comes to duplicating features of existing SSH clients...  it's a ton easier for me to do so in PuTTY. PuTTY has this really useful feature [where the decrypted SSH packets are logged](https://the.earth.li/~sgtatham/putty/0.58/htmldoc/Chapter4.html#config-logging). OpenSSH has no such feature. What this means, in-so-far as PuTTY is concerned, is that I can pretty much duplicate any feature of PuTTY because I can see what PuTTY is actually sending out in the form of SSH packets and can duplicate that. I can't do that with OpenSSH. I have to dig through the OpenSSH sources or else I'd have to actually modify OpenSSH to make it log the raw packets like PuTTY optionally does. ie. it's a ton more work. If people really want this feature they can do some of the leg work by telling me how OpenSSH does what it does (using one of the two methods I just described) or they can tell me how to do this in PuTTY.

**Comment by terrafrost** [comment]
Another thought: if phpseclib isn't running the .bashrc files than I'd see if PuTTY or OpenSSH even runs them when SSH'ing with that. If neither PuTTY or OpenSSH are running them than I submit that the issue isn't with phpseclib but rather with your Linux setup and altho I like to think I have decent Linux skills an SSH client like phpseclib is not a Linux shell and there's only so much help I can provide when the SSH client ends and the Linux shell begins.
