### ISSUE TITLE
Remove the "global $$host;" hack from SFTP Stream class

### ISSUE THREAD

**Issue by bantu** [phpseclib/phpseclib#572]
Using global variables to pass arguments is not in spirit with best practices (dependency injection). For php5 the use of stream_context_get_options() should be enforced.

https://github.com/phpseclib/phpseclib/blob/master/phpseclib/Net/SFTP/Stream.php#L190

**Comment by johnsterling** [comment]
> It's not actually setting global variables. The idea is... say you have $zzz = new Net_SFTP(...). Then you do sftp://$zzz/path/to/filename.php. The method will declare $zzz global and try to access it with a scope that'd let it be accessed.
>
> It isn't 100% compatible with libssh2's method. With libssh2, in my testing, as I recall, "sftp://$zzz/" and 'sftp://$zzz/' both work. With phpseclib's stream wrapper just 'sftp://$zzz/' works.

Hi, I thought I'd chime in here since I kind of like the expressiveness of this usage. I haven't done any actual testing to back this up, but my impression is that this could be implemented by leveraging the [`__toString()` magic method](http://php.net/manual/en/language.oop5.magic.php#object.tostring).

One might maintain a static array of instantiated `SFTP` instances and assign each an ID string (could just be int-based, like a resource type). `__toString()` would return the current instance's ID. Then in the stream wrapper, the ID is looked up in the static array and resolved to an actual instance.

I believe this implementation is implied in the [PHP documentation for `ssh2://`](http://php.net/manual/en/wrappers.ssh2.php), in the explanation under Example 2:
> [...] *$connection_string* does not hold a reference to the *$session* variable, just a string cast derived from it.

This approach, while adding a bit of overhead to maintain the registry of instances, would allow scope-independent referencing of `SFTP` instances. This would prevent the use of `'sftp://$zzz/'` in favor of exclusively `"sftp://$zzz/"` though, so if `ssh2://` supports that then perhaps the above isn't the whole story. I do think it would be a reasonable alternative to exclusively supporting the former as phpseclib does currently.

**Comment by terrafrost** [comment]
That would probably be a workable solution in the php5 / 2.0 branch!

**Comment by terrafrost** [comment]
Fixed by #787
