### ISSUE TITLE
Use of undefined constant NET_SSH2_MASK_WINDOW_ADJUST

### ISSUE THREAD

**Issue by jimmycleuren** [phpseclib/phpseclib#656]
I'm receiving this warning:

Use of undefined constant NET_SSH2_MASK_WINDOW_ADJUST - assumed 'NET_SSH2_MASK_WINDOW_ADJUST'

phpseclib/phpseclib/phpseclib/Net/SSH2.php on line 3206

**Comment by bantu** [comment]
Which version are you using?

**Comment by terrafrost** [comment]
You're going to need to provide more information. Perhaps even provide your whole Net/SSH2.php file. Here's the commit where that constant was initially defined (in 0.3.6):

https://github.com/phpseclib/phpseclib/commit/0f96fae81879e6d8a19831a98063ecd9e2e1fdf9

This commit changed that line:

https://github.com/phpseclib/phpseclib/commit/a14e71f38b441829c1ad945b9094e27a943f5a11

And later there's this commit:

https://github.com/phpseclib/phpseclib/commit/3eac2582d6668ef6c6ef29e7de9cacf6f1b9f834

I looked at line 3206 in tagged versions of Net/SSH2.php going back to 0.3.1 and none of them have NET_SSH2_MASK_WINDOW_ADJUST on line 3206.  Maybe you checked out master from git and haven't updated since? Either way, updating to the latest version would be good. Failing that post your Net/SSH2.php.

**Comment by jimmycleuren** [comment]
Sorry, it was at line 3272. I've just checked the master branch and it's still there.

**Comment by terrafrost** [comment]
Looks like a valid issue in the 2.0 branch. The fact that you're using that branch is something you prob should have mentioned. None-the-less I'll try to implement a fix this evening, time permitting.

**Comment by terrafrost** [comment]
The fix for this has been merged. Thanks!
