### ISSUE TITLE
unpack() is not cache-timing safe

### ISSUE THREAD

**Issue by paragonie-scott** [phpseclib/phpseclib#761]
If `unpack()` is used on cryptographic secrets, it may leak information through cache-timing side-channels

Background:
* http://cr.yp.to/antiforgery/cachetiming-20050414.pdf
* https://crypto.stackexchange.com/a/5527/24405

Based on:
* https://github.com/phpseclib/phpseclib/search?utf8=%E2%9C%93&q=unpack
* https://github.com/magento/magento2/blob/develop/lib/internal/phpseclib/Crypt/Random.php#L71

See also:
* https://github.com/php/php-src/blob/c47c526290b924a1588f317abce94ca3eeddb980/ext/standard/pack.c#L881-L913
* https://github.com/php/php-src/blob/c47c526290b924a1588f317abce94ca3eeddb980/ext/standard/pack.c#L538

-------

### Safe examples in PHP

Cache-timing-safe bin2hex-encoding (taken from libsodium):
* https://github.com/defuse/php-encryption/blob/d2c33279e31d5f3d4b74a82139b6ce56d551965b/src/Crypto.php#L691-L747

Cache-timing-safe bin2int (from random_compat):
* https://github.com/paragonie/random_compat/blob/d6efc0a466f973cdf8235fc3a53dfc022354c32c/lib/random.php#L380-L393

**Comment by terrafrost** [comment]
phpseclib re-implementing functions to protect against timing attacks is certainly not without precident. One example I can think of off hand:

https://github.com/phpseclib/phpseclib/blob/master/phpseclib/Crypt/RSA.php#L2201

Anyway, I'll try to take a look at this this weekend or, depending on how busy I am, early next week.

Thanks!

**Comment by terrafrost** [comment]
On what basis are you alleging that unpack() is vulnerable to timing attacks? You posted a link to the C implementation of unpack and two "background" links as if that's a prima facie explanation but I would like more detail.

My thoughts follow.

So in order to be vulnerable to time attacks the processing time has to vary based on the input. In the case of `==` it makes sense if we consider the most intuitive implementation of `==`. eg. if the length's are equal go through each character one by one, until you find a non-matching character, and then return immediately. `RSA::_equals()` addresses this by creating an implementation of `==` that doesn't return prematurely.

In the case of `unpack('N', ...)` it's essentially doing this:

```
issigned = input[inputpos] & 0x80;
map = big_endian_long_map;
if (SIZEOF_ZEND_LONG > 4 && issigned) {
    v = ~INT_MAX;
}
v |= php_unpack(&input[inputpos], 4, issigned, map);
if (SIZEOF_ZEND_LONG > 4) {
    v = (unsigned int) v;
}
add_assoc_long(return_value, n, v);
```

`php_unpack` is defined as follows:

```
static zend_long php_unpack(char *data, size_t size, int issigned, int *map)
{
	zend_long result;
	char *cresult = (char *) &result;
	int i;

	result = issigned ? -1 : 0;

	for (i = 0; i < size; i++) {
		cresult[map[i]] = *data++;
	}

	return result;
}
```

If my reading is correct input represents the second parameter parameter string and SIZEOF_ZEND_LONG corresponds to PHP_INT_SIZE. So on systems that are using 64-bit integers the output is conditionally set to 0xFFFF... / -1. ie. that's the only time the processing time varies based on the input. ie. there's no timing attack that can be utilized on 32-bit systems.

Quoting the first PDF you link to...

> So what went wrong? Answer: NIST failed to recognize that table lookups do
> not take constant time. “Table lookup: not vulnerable to timing attacks,” NIST
> stated in [19, Section 3.6.2]. NIST’s statement was, and is, incorrect.

I wouldn't call `cresult[map[i]]` a table lookup but maybe the same timing vulnerability exists in that. Certainly it seems that the same L1/L2 caching issues described in sections 10 - 15 (inclusive) could still apply. I think the only way to ensure that they wouldn't would be to do everything in assembly since not even C would let you have that level of fine tuned control over the cache.

So, basically, in reviewing the links you posted, I am seeing evidence that supports the notion that unpack() is vulnerable to timing attacks. But I am, none-the-less, curious what led you to that conclusion. What, specifically, in `unpack()` are you asserting makes it vulnerable to timing attacks?

**Comment by terrafrost** [comment]
Actually, never mind - I guess you kinda did post it with your second link lol.

https://github.com/php/php-src/blob/c47c526290b924a1588f317abce94ca3eeddb980/ext/standard/pack.c#L538

**Comment by paydofor** [comment]
Yes, unpack() is vulnerable to timing attacks, but then again, so to is the proposed alternative.

Test file:

```php
<?php
$bytes = 4;
$randomByteString = 'abcd';

$val = 0;
for ($i = 0; $i < $bytes; ++$i) {
    $val |= ord($randomByteString[$i]) << ($i * 8);
}

echo $val;
```

Here's what that looks like when passed through [PHP's Vulcan Logic Disassembler](https://pecl.php.net/package/vld):

```
Finding entry points
Branch analysis from position: 0
Jump found. Position 1 = 15, Position 2 = 8
Branch analysis from position: 15
Return found
Branch analysis from position: 8
Jump found. Position 1 = 6
Branch analysis from position: 6
Jump found. Position 1 = 4
Branch analysis from position: 4
filename:       C:\medigap360\test3.php
function name:  (null)
number of ops:  17
compiled vars:  !0 = $bytes, !1 = $randomByteString, !2 = $val, !3 = $i
line     # *  op                           fetch          ext  return  operands
--------------------------------------------------------------------------------
-
   2     0  >   ASSIGN                                                   !0, 4
   3     1      ASSIGN                                                   !1, 'abcd'
   5     2      ASSIGN                                                   !2, 0
   6     3      ASSIGN                                                   !3, 0
         4  >   IS_SMALLER                                       ~4      !3, !0
         5    > JMPZNZ                                        8          ~4, ->1
5
         6  >   PRE_INC                                                  !3
         7    > JMP                                                      ->4
   7     8  >   FETCH_DIM_R                                      $6      !1, !3
         9      SEND_VAR                                                 $6
        10      DO_FCALL                                      1  $7      'ord'
        11      MUL                                              ~8      !3, 8
        12      SL                                               ~9      $7, ~8
        13      ASSIGN_BW_OR                                  0          !2, ~9
   8    14    > JMP                                                      ->6
  10    15  >   ECHO                                                     !2
        16    > RETURN                                                   1

branch: #  0; line:     2-    6; sop:     0; eop:     3; out1:   4
branch: #  4; line:     6-    6; sop:     4; eop:     5; out1:  15; out2:   8
branch: #  6; line:     6-    6; sop:     6; eop:     7; out1:   4
branch: #  8; line:     7-    8; sop:     8; eop:    14; out1:   6
branch: # 15; line:    10-   10; sop:    15; eop:    16
path #1: 0, 4, 15,
path #2: 0, 4, 8, 6, 4, 15,
```

Contrast that with unpack:

```php
<?php
$randomByteString = 'abcd';

extract(unpack('Nval', $randomByteString));

echo $val;
```

The output:

```
Finding entry points
Branch analysis from position: 0
Return found
filename:       C:\medigap360\test3.php
function name:  (null)
number of ops:  8
compiled vars:  !0 = $randomByteString, !1 = $val
line     # *  op                           fetch          ext  return  operands
--------------------------------------------------------------------------------
-
   2     0  >   ASSIGN                                                   !0, 'abcd'
   4     1      SEND_VAL                                                 'Nval'
         2      SEND_VAR                                                 !0
         3      DO_FCALL                                      2  $1      'unpack'
         4      SEND_VAR_NO_REF                               F          $1
         5      DO_FCALL                                      1          'extract'
   6     6      ECHO                                                     !1
         7    > RETURN                                                   1

branch: #  0; line:     2-    6; sop:     0; eop:     7
path #1: 0,
```
The more opcodes that are run the more of an opportunity something has to get out of the L1/L2 cache and note how your code 5 branches in the vld analysis whereas unpack has none. Plus, with PHP, you have zval's. The string is a zval. When you try to get at a specific element you get a zval. When you do ord() you get a zval. And zval's are pretty bloated. The following URL elaborates:

https://nikic.github.io/2011/12/12/How-big-are-PHP-arrays-really-Hint-BIG.html

The larger the data the greater the chance that it'll be swapped out of the L1/L2 cache to clear the way for other stuff.

Basically, since the table indexing timing vulnerability you're trying to address relies in L1/L2 cache misses to work implementing a solution that's going to result in even more L1/L2 cache misses isn't much of a solution at all.

Remediating this particular variety of timing attacks in PHP is not really possible. If you want code that provides better remediation don't use PHP.

**Comment by paydofor** [comment]
Also, see [Why do crypto libs use table lookups when they're vulnerable to timing attacks?](http://crypto.stackexchange.com/a/27315/4520). Quoting it,

> The countermeasures needed as you go down the stack become increasingly expensive; it sounds reasonable that an implementation will say "we'll go down this far and no farther"

**Comment by paragonie-scott** [comment]
> Remediating this particular variety of timing attacks in PHP is not really possible.

Sigh, you're right. I better tell @defuse that my solution is ineffective. :(

**Comment by paragonie-scott** [comment]
https://github.com/paragonie/constant_time_encoding uses `pack()` and `unpack()` for converting from characters to unsigned ints (and vice versa), but actually performs the encoding calculation in constant time.

**Comment by defuse** [comment]
I posted this comment https://github.com/defuse/php-encryption/pull/180#issuecomment-204810225 in one of my repositories which is relevant to this discussion. In particular I claim that the analysis in https://github.com/phpseclib/phpseclib/issues/761#issuecomment-127269694 is wrong. `ord()` is safe, `chr()` is unsafe, `pack()` and `unpack()` are safe when used with "C".
