### ISSUE TITLE
Handling mbstring.func_overload

### ISSUE THREAD

**Issue by paragonie-scott** [phpseclib/phpseclib#762]
PHP has this really stupid feature called `mbstring.func_overload` which affects the behavior of `strlen()` and `substr()`.

Normally, these functions operate on a per-byte basis, but if you enable `mbstring.func_overload` it adopts multibyte character support. The consequences can be insane (e.g. string lengths being calculated based off a UTF-8 interpretation of a string, which can degrade security).

defuse/php-encryption solves this by using `mb_strlen($string, '8bit')` and `mb_substr($string, $start, $length, '8bit');` if these functions exist, and falls back to the defaults if they do not.

https://github.com/defuse/php-encryption/blob/d2c33279e31d5f3d4b74a82139b6ce56d551965b/src/Crypto.php#L654-L709

It might be worthwhile to adopt a similar approach in phpseclib.

**Comment by terrafrost** [comment]
`mbstring.func_overload` has been brought up before, here:

http://www.frostjedi.com/phpbb3/viewtopic.php?p=188632#p188632

If the fix that defuse/php-encryption implemented fixes it without a significant speed penalty I'd be up for it. It looks like defuse/php-encryption is using OpenSSL and only OpenSSL so it's only doing `ourSubstr` 4x for each `decrypt` call, no matter how big the ciphertext is. With some of the internal implementations it could wind up being called a *lot*. Like with the internal implementation phpseclib can do 1MB with AES in 1s per this:

http://phpseclib.sourceforge.net/crypt/examples.html

If doing this would make that take 5s I'd almost rather not do it. Instead, an exception could be thrown in the constructor or some such. Or maybe it's utilized for mcrypt / openssl but not for internal mode and if you have `mbstring.func_overload` in internal mode an exception is thrown.

Either way benchmarks need to be done.

**Comment by paragonie-scott** [comment]
> It looks like defuse/php-encryption is using OpenSSL and only OpenSSL

It was originally implemented in mcrypt (see https://github.com/defuse/php-encryption/releases/tag/v1.1). After a lot of discussion with @defuse I suggested switching to OpenSSL (because of [concerns about mcrypt's design and abandonment](https://paragonie.com/blog/2015/05/if-you-re-typing-word-mcrypt-into-your-code-you-re-doing-it-wrong)) and drafted a pull request to do just that.

> Instead, an exception could be thrown in the constructor or some such.

I see no problem with failing hard if this option is enabled. People might complain about the usability, but really if they need multibyte character support they should use the mb_* functions explicitly rather than enabling a dangerous and ill-advised configuration option anyway.

(Can you tell I'm not a fan of the decision to support function overloading?)

**Comment by terrafrost** [comment]
> It was originally implemented in mcrypt (see https://github.com/defuse/php-encryption/releases/tag/v1.1). After a lot of discussion with @defuse I suggested switching to OpenSSL (because of concerns about mcrypt's design and abandonment) and drafted a pull request to do just that.

This is totally tangential lol but I actually like mcrypt's design.

I do agree that it's being abandoned is a problem. It definitely has bugs (in fact, I've submitted a few lol) and I think they ought to create an MCRYPT_AES cipher as an alias of MCRYPT_RIJNDAEL_128 to eliminate the confusion your blog speaks of, but aside from that I actually like it.

The problem with OpenSSL is that the key size and mode are tied to the algorithm name whereas with mcrypt they're separate. I guess for the mode it's not a huge issue but for the key size it's a little annoying. So let's say you wanted to do 256-bit RC4. Per wikipedia RC4 supports keys between 40 and 2048 bits so it's possible. But not with OpenSSL. With OpenSSL you can do `rc4-40`, `rc4-64` or `rc4` (which is 128) but not 256. With mcrypt you just give it a key 32 bytes long as the key and you're good to go.

I suppose, in the case of RC4, it's not a huge issue, as people ought not be using it, anyway, but if you're gonna support it, I think you ought to support the full gamut of options and not a small subset.

I also agree with the null padding by default. That's why phpseclib doesn't null pad plaintext's / ciphertext's by default lol. Altho both OpenSSL and mcrypt does null pad keys and IV's.

> if they need multibyte character support they should use the mb_* functions explicitly rather than enabling a dangerous and ill-advised configuration option anyway.

I agree (I'm not a fan either lol). I think PHP should deprecate that in future versions :)

**Comment by bantu** [comment]
My preference would be to simply not support stupid features like `mbstring.func_overload` and to throw an error/exception in those cases.

**Comment by bantu** [comment]
Possible implementation via https://getcomposer.org/doc/04-schema.md#files

**Comment by paragonie-scott** [comment]
In the master branch, you can use `\ParagonIE\ConstantTime\Binary` for `safeSubstr()` and `safeStrlen()` instead of `substr()` and `strlen()`. But since this isn't a big concern, I'm closing this ticket.
