### ISSUE TITLE
SFTP stream wrapper doesn't support hashes in file name

### ISSUE THREAD

**Issue by PVince81** [phpseclib/phpseclib#778]
Passing a file name with a hash inside like "/somepath/#somefile.txt", the hash part gets stripped away by the subsequent call to `parseurl`.

https://github.com/phpseclib/phpseclib/blob/master/phpseclib/Net/SFTP/Stream.php#L251

Furthermore passing a URL-encoded path doesn't work either.
If "/somepath/%23somefile.txt" is passed, it will just create a remote file called "%23somefile.txt".

**Comment by bantu** [comment]
I think the behaviour should be made consistent with built-in streams such as `file://`.

**Comment by PVince81** [comment]
Any update on this ?

**Comment by terrafrost** [comment]
First, I apologize for the delay - I did kinda forget about this.

Anyway, it seems to me that a case could be made for retaining the same behavior. The characters of `#` and `?` have a specific meaning in the URI standard and, per that, it seems like it might be better to urlencode `?` and `#`. eg. `%23` for `#` and `%3F` for `?`. Altho that said, `parse_url` does not automatically do this:

```php
<?php
$a = parse_url('https://www.google.com/se%61rch?q=test');

print_r($a);
```

That outputs the following:

```
Array
(
    [scheme] => https
    [host] => www.google.com
    [path] => /se%61rch
    [query] => q=test
)
```
Maybe that's a bug in `parse_url`? idk. 

Requests to google.com, with a replaced with %61 work just fine when https://www.google.com/se%61rch?q=test is entered into the address bar. It does appear that the browser is converting %61 to a, tho, so let's try it with a manual HTTP request:

```
<?php
$fsock = fsockopen('www.google.com', 80);

fputs($fsock, "GET /se%61rch?q=test HTTP/1.0\r\n");
fputs($fsock, "Host: www.google.com\r\n\r\n");

while (!feof($fsock)) {
	echo fgets($fsock, 1024);
}
```
That works as well.

That said, I went ahead and made it so that `#` works directly since that's what libssh2 does.
