### ISSUE TITLE
Drop PHP 5.3

### ISSUE THREAD

**Issue by GrahamCampbell** [phpseclib/phpseclib#792]
I think it would be a good idea to drop php 5.3 support for 3.x given that it's been EOL for quite a while. Maybe you should consider dropping php 5.4 too since that'll be EOL before you ship 3.x.

5.4 might be a long shot, but ditching 5.3 would be a good idea imo.

**Comment by cweagans** [comment]
This basically amounts to abandoning the 1.0 branch + removing all the version checks for old PHP versions + adding a PHP version constraint in composer.json.

+1 for dropping 5.4 support in master (might as well leave it for 2.0, though - nothing *technically* requires it)

**Comment by terrafrost** [comment]
@cweagans - I don't think @GrahamCampbell's proposal had anything to do with the 1.0 or 2.0 branches. Rather, I think it had more to do with the master branch.

And as far as master is concerned I think you're right about the only thing that this would entail would be a version constraint in composer.json. I'm not aware of a PHP 5.4 specific feature that'd benefit phpseclib. Like PHP 5.3 introduced namespaces and that is a total BC break from earlier versions but I don't think 5.4 has anything comparable.

And if that's the case I guess I'm okay with it. I mean, in truth, there are still a lot of servers out there with 5.3. Even 5.2 is more prevalent than it ought to be.

At my last job we had at least one PHP 5.2 server, which prevented namespaced packages from working. It's easy as a dev to say they need to be upgraded when you're not the one upgrading them. Plus, people could always just say "oh I'll use something else that does work on my version of PHP" if your software doesn't.

I mean, I can only assume that phpseclib has achieved the level of popularity that it has due to the fact that it's server requirements are pretty minimal. I'm not a big fan of upending that approach when I believe it's that approach that has gotten phpseclib where it is today.

But, that said, if the only change is in composer.json people could still manually install phpseclib on PHP 5.3 even if the composer.json said PHP 5.4 was required. And I think I'd be okay with that. Like for 3.0 we can see how much of an issue it is by writing PHP 5.3 compatible code but saying in composer.json that it only works on 5.4. If no one complains after a certain period of time we can start doing PHP 5.4-only things. Like `[]` instead of `array()`. Maybe. I guess doing that could increase the likelihood of merge conflicts idk..

**Comment by cweagans** [comment]
@terrafrost I guess it depends on what you mean by "drop support for PHP 5.3". I assume that means PHP 5.3 and below, which means that 1.0 would still run, but why wouldn't you just use 2.0 in that case? If PHP 5.3 is the minimum version, there's no reason to continue supporting 1.0.

That said, you may be interested in the PHP version stats that Wordpress collects: https://wordpress.org/about/stats/ According to that (and if you assume that the PHP versions collected by Wordpress are a good representation of all PHP deployments), PHP 5.2 & PHP 5.3 make up 44% of PHP installations. That's not very good.

I'd still support dropping support for PHP 5.3 and below, and taking that a step further, just following the support timelines for PHP versions: http://php.net/supported-versions.php  It doesn't make any sense to maintain a security library on top of an old, unpatched, likely insecure PHP installation.

**Comment by GrahamCampbell** [comment]
> If no one complains after a certain period of time we can start doing PHP 5.4-only things. Like [] instead of array(). Maybe. I guess doing that could increase the likelihood of merge conflicts idk.

I'd say we shouldn't change the array style on the master branch until 2.0 is actually dead, which is a LONG way off yet. The main benefit I see to dropping 5.3 is that we can remove more version specific hacks, and stop worrying about bugs found in php 5.3.4, for example.

> That said, you may be interested in the PHP version stats that Wordpress collects:

I don't think wordpress reflects usage of our target audience though, tbh.

> I mean, in truth, there are still a lot of servers out there with 5.3. Even 5.2 is more prevalent than it ought to be.

Yeh, considering this library is meant for cryptography, I don't think we should encorage using EOL versions of php, but there's nothing stopping people from using 1.x and 2.x to get older versions of PHP. They're not going away anytime soon. :)

**Comment by GrahamCampbell** [comment]
@terrafrost What's the timescale for 3.0 btw? When are you planning to release? 3 months? 1 year? 2 years?

**Comment by terrafrost** [comment]
> @terrafrost I guess it depends on what you mean by "drop support for PHP 5.3". I assume that means PHP 5.3 and below, which means that 1.0 would still run, but why wouldn't you just use 2.0 in that case? If PHP 5.3 is the minimum version, there's no reason to continue supporting 1.0.

The different branches have different PHP requirements.

2.0 requires PHP 5.3, 1.0 works on PHP 4.4 or some such. master could drop PHP 5.4

> @terrafrost What's the timescale for 3.0 btw? When are you planning to release? 3 months? 1 year? 2 years?

Probably closer to a year. I want to pretty much completely redo X509.php and do a lot of refactoring of SSH2.php and maybe SFTP.php too. ie. to give people a reason to update.

**Comment by GrahamCampbell** [comment]
If the release is in Q3 2016, I'd say it would be reasonable to drop both php 5.3 and 5.4 in 3.0.

**Comment by terrafrost** [comment]
> If the release is in Q3 2016, I'd say it would be reasonable to drop both php 5.3 and 5.4 in 3.0.

I think we should cross that bridge when we get there.

Q3 2016 is my best guess but what if it gets done Q4 2015 or Q1 2016? Let's not commit to anything until we need to. For the time being I think any such discussion is premature.

**Comment by cweagans** [comment]
I don't think a decision to drop support for an unsupported runtime is premature at *any* time, and there's a lot of nice refactoring that can happen if you can assume a recent version of PHP. I don't think it's unreasonable to make that assumption, and many widely used frameworks and components are making that same assumption and pushing the PHP world forward.
