### ISSUE TITLE
Login Failed

### ISSUE THREAD

**Issue by scriptzteam** [phpseclib/phpseclib#849]
Alwas gettin Login Failed, and credential are good, which libraries i need , like mcrypt etc?

**Comment by terrafrost** [comment]
I don't know why this was closed - seems like a valid support issue.

Anyway, @scriptzteam - can you post your logs? You can get the logs by doing `define('NET_SSH2_LOGGING', 2)` before you initialize the Net_SSH2 object and then do `$ssh->getLog()` after the failed login attempt.

In lieu of that it could be any number of things. Maybe the `fsockopen` connection failed. Maybe the server requires zlib compression (it shouldn't, per the SSH specs, but some none-the-less do). Maybe it has a buggy implementation of algorithm that phpseclib and the server agreed upon. Without the logs it's pretty much impossible to say for sure.

**Comment by omnomnymous** [comment]
I'm having the very same issue. 
Code: 
<pre>
    set_include_path(__DIR__ . '/phpseclib/');
    include('SSH2.php');
    include 'Crypt/RSA.php';
    define('NET_SSH2_LOGGING', NET_SSH2_LOG_COMPLEX);
    $rsa = new Crypt_RSA();
    $rsa->loadKey($server['key']);
    $ssh = new Net_SSH2($server['ip'],$server['port']);
    $ssh->setTimeout(10);
    if (!$ssh->login($server['login'], $rsa)) {
      echo '<textarea cols=80 rows=20>'.$ssh->getLog().'</textarea>';
      die('Login Failed');
    }
    echo $ssh->exec('pwd');
</pre>

Log:
<pre><-
00000000  53:53:48:2d:32:2e:30:2d:4f:70:65:6e:53:53:48:5f  SSH-2.0-OpenSSH_
00000010  35:2e:33:0d:0a                                   5.3..

->
00000000  53:53:48:2d:32:2e:30:2d:70:68:70:73:65:63:6c:69  SSH-2.0-phpsecli
00000010  62:5f:31:2e:30:20:28:6f:70:65:6e:73:73:6c:29:0d  b_1.0 (openssl).
00000020  0a                                               .

<- NET_SSH2_MSG_KEXINIT (since last: 4.0181, network: 1.6416s)
00000000  14:77:3d:04:a4:b0:b6:58:4e:32:80:02:4d:87:f6:9d  .w=....XN2..M...
00000010  00:00:00:7e:64:69:66:66:69:65:2d:68:65:6c:6c:6d  ...~diffie-hellm
00000020  61:6e:2d:67:72:6f:75:70:2d:65:78:63:68:61:6e:67  an-group-exchang
00000030  65:2d:73:68:61:32:35:36:2c:64:69:66:66:69:65:2d  e-sha256,diffie-
00000040  68:65:6c:6c:6d:61:6e:2d:67:72:6f:75:70:2d:65:78  hellman-group-ex
00000050  63:68:61:6e:67:65:2d:73:68:61:31:2c:64:69:66:66  change-sha1,diff
00000060  69:65:2d:68:65:6c:6c:6d:61:6e:2d:67:72:6f:75:70  ie-hellman-group
00000070  31:34:2d:73:68:61:31:2c:64:69:66:66:69:65:2d:68  14-sha1,diffie-h
00000080  65:6c:6c:6d:61:6e:2d:67:72:6f:75:70:31:2d:73:68  ellman-group1-sh
00000090  61:31:00:00:00:0f:73:73:68:2d:72:73:61:2c:73:73  a1....ssh-rsa,ss
000000a0  68:2d:64:73:73:00:00:00:9d:61:65:73:31:32:38:2d  h-dss....aes128-
000000b0  63:74:72:2c:61:65:73:31:39:32:2d:63:74:72:2c:61  ctr,aes192-ctr,a
000000c0  65:73:32:35:36:2d:63:74:72:2c:61:72:63:66:6f:75  es256-ctr,arcfou
000000d0  72:32:35:36:2c:61:72:63:66:6f:75:72:31:32:38:2c  r256,arcfour128,
000000e0  61:65:73:31:32:38:2d:63:62:63:2c:33:64:65:73:2d  aes128-cbc,3des-
000000f0  63:62:63:2c:62:6c:6f:77:66:69:73:68:2d:63:62:63  cbc,blowfish-cbc
00000100  2c:63:61:73:74:31:32:38:2d:63:62:63:2c:61:65:73  ,cast128-cbc,aes
00000110  31:39:32:2d:63:62:63:2c:61:65:73:32:35:36:2d:63  192-cbc,aes256-c
00000120  62:63:2c:61:72:63:66:6f:75:72:2c:72:69:6a:6e:64  bc,arcfour,rijnd
00000130  61:65:6c:2d:63:62:63:40:6c:79:73:61:74:6f:72:2e  ael-cbc@lysator.
00000140  6c:69:75:2e:73:65:00:00:00:9d:61:65:73:31:32:38  liu.se....aes128
00000150  2d:63:74:72:2c:61:65:73:31:39:32:2d:63:74:72:2c  -ctr,aes192-ctr,
00000160  61:65:73:32:35:36:2d:63:74:72:2c:61:72:63:66:6f  aes256-ctr,arcfo
00000170  75:72:32:35:36:2c:61:72:63:66:6f:75:72:31:32:38  ur256,arcfour128
00000180  2c:61:65:73:31:32:38:2d:63:62:63:2c:33:64:65:73  ,aes128-cbc,3des
00000190  2d:63:62:63:2c:62:6c:6f:77:66:69:73:68:2d:63:62  -cbc,blowfish-cb
000001a0  63:2c:63:61:73:74:31:32:38:2d:63:62:63:2c:61:65  c,cast128-cbc,ae
000001b0  73:31:39:32:2d:63:62:63:2c:61:65:73:32:35:36:2d  s192-cbc,aes256-
000001c0  63:62:63:2c:61:72:63:66:6f:75:72:2c:72:69:6a:6e  cbc,arcfour,rijn
000001d0  64:61:65:6c:2d:63:62:63:40:6c:79:73:61:74:6f:72  dael-cbc@lysator
000001e0  2e:6c:69:75:2e:73:65:00:00:00:85:68:6d:61:63:2d  .liu.se....hmac-
000001f0  6d:64:35:2c:68:6d:61:63:2d:73:68:61:31:2c:75:6d  md5,hmac-sha1,um
00000200  61:63:2d:36:34:40:6f:70:65:6e:73:73:68:2e:63:6f  ac-64@openssh.co
00000210  6d:2c:68:6d:61:63:2d:73:68:61:32:2d:32:35:36:2c  m,hmac-sha2-256,
00000220  68:6d:61:63:2d:73:68:61:32:2d:35:31:32:2c:68:6d  hmac-sha2-512,hm
00000230  61:63:2d:72:69:70:65:6d:64:31:36:30:2c:68:6d:61  ac-ripemd160,hma
00000240  63:2d:72:69:70:65:6d:64:31:36:30:40:6f:70:65:6e  c-ripemd160@open
00000250  73:73:68:2e:63:6f:6d:2c:68:6d:61:63:2d:73:68:61  ssh.com,hmac-sha
00000260  31:2d:39:36:2c:68:6d:61:63:2d:6d:64:35:2d:39:36  1-96,hmac-md5-96
00000270  00:00:00:85:68:6d:61:63:2d:6d:64:35:2c:68:6d:61  ....hmac-md5,hma
00000280  63:2d:73:68:61:31:2c:75:6d:61:63:2d:36:34:40:6f  c-sha1,umac-64@o
00000290  70:65:6e:73:73:68:2e:63:6f:6d:2c:68:6d:61:63:2d  penssh.com,hmac-
000002a0  73:68:61:32:2d:32:35:36:2c:68:6d:61:63:2d:73:68  sha2-256,hmac-sh
000002b0  61:32:2d:35:31:32:2c:68:6d:61:63:2d:72:69:70:65  a2-512,hmac-ripe
000002c0  6d:64:31:36:30:2c:68:6d:61:63:2d:72:69:70:65:6d  md160,hmac-ripem
000002d0  64:31:36:30:40:6f:70:65:6e:73:73:68:2e:63:6f:6d  d160@openssh.com
000002e0  2c:68:6d:61:63:2d:73:68:61:31:2d:39:36:2c:68:6d  ,hmac-sha1-96,hm
000002f0  61:63:2d:6d:64:35:2d:39:36:00:00:00:15:6e:6f:6e  ac-md5-96....non
00000300  65:2c:7a:6c:69:62:40:6f:70:65:6e:73:73:68:2e:63  e,zlib@openssh.c
00000310  6f:6d:00:00:00:15:6e:6f:6e:65:2c:7a:6c:69:62:40  om....none,zlib@
00000320  6f:70:65:6e:73:73:68:2e:63:6f:6d:00:00:00:00:00  openssh.com.....
00000330  00:00:00:00:00:00:00:00                          ........

-> NET_SSH2_MSG_KEXINIT (since last: 0.0003, network: 0.0001s)
00000000  b5:d7:74:43:fe:46:d0:13:b1:21:12:34:04:00:6c:9a  ..tC.F...!.4..l.
00000010  00:00:00:7e:64:69:66:66:69:65:2d:68:65:6c:6c:6d  ...~diffie-hellm
00000020  61:6e:2d:67:72:6f:75:70:31:2d:73:68:61:31:2c:64  an-group1-sha1,d
00000030  69:66:66:69:65:2d:68:65:6c:6c:6d:61:6e:2d:67:72  iffie-hellman-gr
00000040  6f:75:70:31:34:2d:73:68:61:31:2c:64:69:66:66:69  oup14-sha1,diffi
00000050  65:2d:68:65:6c:6c:6d:61:6e:2d:67:72:6f:75:70:2d  e-hellman-group-
00000060  65:78:63:68:61:6e:67:65:2d:73:68:61:31:2c:64:69  exchange-sha1,di
00000070  66:66:69:65:2d:68:65:6c:6c:6d:61:6e:2d:67:72:6f  ffie-hellman-gro
00000080  75:70:2d:65:78:63:68:61:6e:67:65:2d:73:68:61:32  up-exchange-sha2
00000090  35:36:00:00:00:0f:73:73:68:2d:72:73:61:2c:73:73  56....ssh-rsa,ss
000000a0  68:2d:64:73:73:00:00:00:e9:61:72:63:66:6f:75:72  h-dss....arcfour
000000b0  32:35:36:2c:61:72:63:66:6f:75:72:31:32:38:2c:61  256,arcfour128,a
000000c0  65:73:31:32:38:2d:63:74:72:2c:61:65:73:31:39:32  es128-ctr,aes192
000000d0  2d:63:74:72:2c:61:65:73:32:35:36:2d:63:74:72:2c  -ctr,aes256-ctr,
000000e0  74:77:6f:66:69:73:68:31:32:38:2d:63:74:72:2c:74  twofish128-ctr,t
000000f0  77:6f:66:69:73:68:31:39:32:2d:63:74:72:2c:74:77  wofish192-ctr,tw
00000100  6f:66:69:73:68:32:35:36:2d:63:74:72:2c:61:65:73  ofish256-ctr,aes
00000110  31:32:38:2d:63:62:63:2c:61:65:73:31:39:32:2d:63  128-cbc,aes192-c
00000120  62:63:2c:61:65:73:32:35:36:2d:63:62:63:2c:74:77  bc,aes256-cbc,tw
00000130  6f:66:69:73:68:31:32:38:2d:63:62:63:2c:74:77:6f  ofish128-cbc,two
00000140  66:69:73:68:31:39:32:2d:63:62:63:2c:74:77:6f:66  fish192-cbc,twof
00000150  69:73:68:32:35:36:2d:63:62:63:2c:74:77:6f:66:69  ish256-cbc,twofi
00000160  73:68:2d:63:62:63:2c:62:6c:6f:77:66:69:73:68:2d  sh-cbc,blowfish-
00000170  63:74:72:2c:62:6c:6f:77:66:69:73:68:2d:63:62:63  ctr,blowfish-cbc
00000180  2c:33:64:65:73:2d:63:74:72:2c:33:64:65:73:2d:63  ,3des-ctr,3des-c
00000190  62:63:00:00:00:e9:61:72:63:66:6f:75:72:32:35:36  bc....arcfour256
000001a0  2c:61:72:63:66:6f:75:72:31:32:38:2c:61:65:73:31  ,arcfour128,aes1
000001b0  32:38:2d:63:74:72:2c:61:65:73:31:39:32:2d:63:74  28-ctr,aes192-ct
000001c0  72:2c:61:65:73:32:35:36:2d:63:74:72:2c:74:77:6f  r,aes256-ctr,two
000001d0  66:69:73:68:31:32:38:2d:63:74:72:2c:74:77:6f:66  fish128-ctr,twof
000001e0  69:73:68:31:39:32:2d:63:74:72:2c:74:77:6f:66:69  ish192-ctr,twofi
000001f0  73:68:32:35:36:2d:63:74:72:2c:61:65:73:31:32:38  sh256-ctr,aes128
00000200  2d:63:62:63:2c:61:65:73:31:39:32:2d:63:62:63:2c  -cbc,aes192-cbc,
00000210  61:65:73:32:35:36:2d:63:62:63:2c:74:77:6f:66:69  aes256-cbc,twofi
00000220  73:68:31:32:38:2d:63:62:63:2c:74:77:6f:66:69:73  sh128-cbc,twofis
00000230  68:31:39:32:2d:63:62:63:2c:74:77:6f:66:69:73:68  h192-cbc,twofish
00000240  32:35:36:2d:63:62:63:2c:74:77:6f:66:69:73:68:2d  256-cbc,twofish-
00000250  63:62:63:2c:62:6c:6f:77:66:69:73:68:2d:63:74:72  cbc,blowfish-ctr
00000260  2c:62:6c:6f:77:66:69:73:68:2d:63:62:63:2c:33:64  ,blowfish-cbc,3d
00000270  65:73:2d:63:74:72:2c:33:64:65:73:2d:63:62:63:00  es-ctr,3des-cbc.
00000280  00:00:39:68:6d:61:63:2d:73:68:61:32:2d:32:35:36  ..9hmac-sha2-256
00000290  2c:68:6d:61:63:2d:73:68:61:31:2d:39:36:2c:68:6d  ,hmac-sha1-96,hm
000002a0  61:63:2d:73:68:61:31:2c:68:6d:61:63:2d:6d:64:35  ac-sha1,hmac-md5
000002b0  2d:39:36:2c:68:6d:61:63:2d:6d:64:35:00:00:00:39  -96,hmac-md5...9
000002c0  68:6d:61:63:2d:73:68:61:32:2d:32:35:36:2c:68:6d  hmac-sha2-256,hm
000002d0  61:63:2d:73:68:61:31:2d:39:36:2c:68:6d:61:63:2d  ac-sha1-96,hmac-
000002e0  73:68:61:31:2c:68:6d:61:63:2d:6d:64:35:2d:39:36  sha1,hmac-md5-96
000002f0  2c:68:6d:61:63:2d:6d:64:35:00:00:00:04:6e:6f:6e  ,hmac-md5....non
00000300  65:00:00:00:04:6e:6f:6e:65:00:00:00:00:00:00:00  e....none.......
00000310  00:00:00:00:00:00                                ......

-> NET_SSH2_MSG_KEXDH_INIT (since last: 0.0085, network: 0s)
00000000  00:00:00:80:35:f3:e3:93:7d:c6:0e:48:db:41:3e:e2  ....5...}..H.A>.
00000010  c8:0f:e8:f2:c4:0d:1a:67:45:85:18:68:02:5b:f9:a7  .......gE..h.[..
00000020  bc:38:5e:f5:74:7a:d2:c1:33:41:cb:21:d3:7f:54:03  .8^.tz..3A.!..T.
00000030  4d:73:61:a6:29:0b:a7:2b:d1:ed:4d:b9:74:09:ba:01  Msa.)..+..M.t...
00000040  ba:26:cb:98:e1:38:83:a8:82:1a:78:16:c5:dc:67:73  .&...8....x...gs
00000050  86:38:c9:e8:37:2a:a2:db:ae:90:4e:d3:02:7d:c8:8b  .8..7*....N..}..
00000060  36:c7:e0:c8:53:ee:c4:a1:55:9a:fb:31:d2:ad:82:34  6...S...U..1...4
00000070  ef:d7:1f:f1:e9:6c:ec:f0:30:fc:65:be:8a:93:8e:b7  .....l..0.e.....
00000080  75:c4:35:14                                      u.5.

<- NET_SSH2_MSG_KEXDH_REPLY (since last: 2.2417, network: 2.2416s)
00000000  00:00:01:15:00:00:00:07:73:73:68:2d:72:73:61:00  ........ssh-rsa.
00000010  00:00:01:23:00:00:01:01:00:c2:c4:87:4b:4b:17:c7  ...#........KK..
00000020  05:ae:3a:08:22:ce:bb:4d:48:36:a6:54:e0:d5:1c:a3  ..:."..MH6.T....
00000030  d3:5d:c8:0d:fc:88:95:67:67:0b:79:ee:e0:7e:34:8c  .].....gg.y..~4.
00000040  b6:be:d9:a4:9c:c2:f8:23:d5:f6:97:30:a2:2c:71:67  .......#...0.,qg
00000050  b0:72:18:78:9c:c0:dd:38:2d:a3:2c:91:69:a2:30:a5  .r.x...8-.,.i.0.
00000060  d1:da:28:d3:03:bc:bf:69:eb:47:4a:03:38:99:10:df  ..(....i.GJ.8...
00000070  57:fe:27:af:10:33:5f:0d:04:59:18:a6:ea:85:7d:c6  W.'..3_..Y....}.
00000080  96:db:4f:96:f3:e6:95:13:d1:12:bf:4e:5b:4b:eb:8a  ..O........N[K..
00000090  be:47:27:f5:13:90:f6:b1:14:13:0d:f1:b6:77:d4:68  .G'..........w.h
000000a0  00:d0:31:4f:6b:e7:b2:48:f9:e9:85:85:a6:4e:93:88  ..1Ok..H.....N..
000000b0  e5:f7:7e:f0:27:9e:23:90:09:f7:05:db:f2:1b:10:a3  ..~.'.#.........
000000c0  fa:5d:92:8a:62:82:fd:52:14:c2:dc:ea:7e:d9:10:e7  .]..b..R....~...
000000d0  f9:d9:7a:a8:cd:70:1d:e2:bf:33:77:7e:8a:fc:09:9d  ..z..p...3w~....
000000e0  80:32:45:9e:66:a1:ee:80:cc:4f:50:9c:b2:13:25:0b  .2E.f....OP...%.
000000f0  44:8c:bf:9f:ee:a9:b3:63:d7:76:43:32:3e:3d:74:76  D......c.vC2>=tv
00000100  ba:46:0c:52:32:a0:ef:ed:0b:8d:55:c6:0f:83:88:78  .F.R2.....U....x
00000110  51:24:36:be:d5:ad:2c:af:59:00:00:00:80:10:d8:b8  Q$6...,.Y.......
00000120  9b:97:a2:31:00:99:5f:87:09:1c:48:02:75:bf:21:68  ...1.._...H.u.!h
00000130  fa:fe:47:b0:35:6d:c2:08:06:81:fc:63:d5:09:aa:25  ..G.5m.....c...%
00000140  5b:04:1b:ff:85:91:77:c4:54:15:9d:56:5f:55:8a:be  [.....w.T..V_U..
00000150  8e:57:f4:33:1d:ed:2c:af:fd:12:11:70:4e:a1:c7:5f  .W.3..,....pN.._
00000160  b7:29:48:c0:ed:37:b8:db:ca:b5:ae:dd:ad:ca:de:fa  .)H..7..........
00000170  18:dd:5b:89:57:db:ff:34:fb:03:cd:50:e3:f0:55:f1  ..[.W..4...P..U.
00000180  09:c3:eb:63:9e:2b:91:37:25:0b:d5:3f:0e:d8:cd:4e  ...c.+.7%..?...N
00000190  a1:9b:cb:93:38:82:37:d7:53:30:6d:74:ee:00:00:01  ....8.7.S0mt....
000001a0  0f:00:00:00:07:73:73:68:2d:72:73:61:00:00:01:00  .....ssh-rsa....
000001b0  06:ce:e6:90:e9:05:10:03:fe:06:5f:56:3d:e3:6e:06  .........._V=.n.
000001c0  39:38:d3:30:0c:90:4d:07:ae:94:9d:80:5a:2e:09:a5  98.0..M.....Z...
000001d0  a1:07:6b:30:dc:ff:49:a4:85:95:01:ea:51:e9:e0:d9  ..k0..I.....Q...
000001e0  3e:c3:61:c2:4d:f1:09:1d:cb:11:5a:d3:0a:73:52:f8  >.a.M.....Z..sR.
000001f0  7a:b0:8b:01:05:46:27:68:9e:8b:d7:64:e2:ac:7b:77  z....F'h...d..{w
00000200  0b:91:5a:59:8e:ca:8d:c7:89:b1:fd:1f:ea:2d:0b:a0  ..ZY.........-..
00000210  5f:b8:6e:6f:22:e4:53:3d:46:6b:b2:a0:9e:a2:c8:c4  _.no".S=Fk......
00000220  7e:f2:af:93:77:e4:e8:72:5c:e0:3e:29:07:98:28:d8  ~...w..r\.>)..(.
00000230  7c:8c:64:58:e2:4a:2e:8a:82:40:7f:d7:22:9c:f1:79  |.dX.J...@.."..y
00000240  9d:7f:4d:55:99:3b:87:74:6a:88:91:7b:99:ed:c8:50  ..MU.;.tj..{...P
00000250  b1:32:9a:cc:19:c2:1c:86:29:b6:7f:b2:1c:b3:c5:7e  .2......)......~
00000260  67:2f:c9:67:f0:c6:c8:a2:98:9f:5d:5c:37:85:12:f2  g/.g......]\7...
00000270  26:03:fc:16:53:78:31:37:60:da:e7:84:e2:9e:d9:bd  &...Sx17`.......
00000280  0a:ef:72:c5:70:3c:df:47:9e:87:d7:4f:60:ee:f8:0d  ..r.p..G...O`...
00000290  ff:c1:85:98:74:42:9a:92:26:f0:a4:29:04:f0:2e:2f  ....tB..&..).../
000002a0  76:75:54:8f:58:6f:d7:24:92:d5:e6:ae:49:8a:49:37  vuT.Xo.$....I.I7

-> NET_SSH2_MSG_NEWKEYS (since last: 0.008, network: 0s)
                                                 

<- NET_SSH2_MSG_NEWKEYS (since last: 0.0001, network: 0s)
                                                 

-> NET_SSH2_MSG_SERVICE_REQUEST (since last: 0.0026, network: 0s)
00000000  00:00:00:0c:73:73:68:2d:75:73:65:72:61:75:74:68  ....ssh-userauth

<- NET_SSH2_MSG_SERVICE_ACCEPT (since last: 2.1404, network: 2.1402s)
00000000  00:00:00:0c:73:73:68:2d:75:73:65:72:61:75:74:68  ....ssh-userauth
</pre>


PHP 5.6.1 with mcrypt, hash, and mhash extensions installed

**Comment by omnomnymous** [comment]
:facepalm: the private key was empty. 
Sorry for the noise.
