### ISSUE TITLE
Can't read CRL using phpseclib

### ISSUE THREAD

**Issue by danowar2k** [phpseclib/phpseclib#871]
Hello, (Hallo)

I'm trying to read a CRL file using phpseclib.
The CRL in question is:
http://ca.fernuni-hagen.de/certserver/certs/crl2009.crl

My code:
        $der_data = file_get_contents(CertificateValues::getLocalCrlLocation()); // works local and via url
        $der2pem = someClass::der2pem($der_data);
        $crl = new File_X509();
        $crl->loadCRL($der2pem);

Did I miss something? Do I have to have something configured differently?
My code seems to hang around inside the _decodeBER function. The file is 2MB big.

**Comment by terrafrost** [comment]
First, I apologize for the tardyness of this response. I've been out of town this week per https://github.com/phpseclib/phpseclib/issues/835 .

Anyway, this is slow for a number of reasons.

1. It's doing lots of substr()'s. There are ~150,000 revoked certs in that CRL so that's over 300,000 substr() calls at minimum, thanks to __string_shift(), which, itself, does 2x substr() calls.

 The problem with that is that substr() just isn't the fastest thing in the universe. See https://github.com/phpseclib/phpseclib/pull/129 for an example of how eliminating one substr() call yielded a pretty significant speedup.

2. A PHP array with ~150,000 elements (and subelements) is, itself, fairly slow. Check out https://github.com/terrafrost/phpseclib/commit/b3dfb99536428809606814b4c8e98234413c95a5 and read the in-line comments.

 Maybe it wouldn't be so slow on PHP7 since PHP7 is supposed to be a lot faster with arrays:

 https://nikic.github.io/2014/12/22/PHPs-new-hashtable-implementation.html

 But who knows.

**Comment by danowar2k** [comment]
Gonna close this.
