### ISSUE TITLE
key size of RSA

### ISSUE THREAD

**Issue by nimasdj** [phpseclib/phpseclib#908]
Please consider to set key size default of RSA to 2048 or greater instead of 1024.

**Comment by Joey3000** [comment]
:+1: The default size of 2048 sounds good, given that SSL/TLS certificates with less than 2048-bit RSA key lengths are being [phased out](https://www.symantec.com/page.jsp%3Fid%3D1024-bit-migration-faq#phasedout) as well.

**Comment by GrahamCampbell** [comment]
:+1: for doing that for 3.0. I just did a quick search in one of my own apps and found `$rsa->createKey(2048);`.

**Comment by terrafrost** [comment]
The reason it was 1024 was not by coincidence. It was because generating 2048-bit keys could potentially take an obscene amount of time. ie. internal mode (no OpenSSL, no gmp, no bcmath) on PHP 4.4 or 5.0. The following chart demonstrates the situation:

http://phpseclib.sourceforge.net/math/intro.html

That said, the 2.0 and master branches now require 5.3 and PHP has gotten a lot faster since then so I suppose the original motivation is no longer as applicable as it once was.

**Comment by GrahamCampbell** [comment]
Yeh, 2048 bit key generation is pretty fast on php 7 with the openssl extension.

**Comment by nimasdj** [comment]
Do you want me to do a Pull Request for this?

**Comment by terrafrost** [comment]
I'll just do it in my RSA branch. I still think this should only be changed in master. Right now if people are generating keys with 2.0 they may be content with the speed but if we up the number of bits keys are they may find the new speed to be unsatisfactory. And since the 2.0 branch is aiming to maintain BC...

In the master branch it doesn't really matter. Everything in the master branch is different as is and no one should have any expectations w.r.t. to the API or anything.

**Comment by terrafrost** [comment]
See https://github.com/terrafrost/phpseclib/commit/6abbbfdfe3fe040e017d3ace58c1241c122dd581

**Comment by nimasdj** [comment]
This is pull request? When will be released?

**Comment by GrahamCampbell** [comment]
Ages. It's going into 3.0.

**Comment by GrahamCampbell** [comment]
Don't expect it this quarter.

**Comment by terrafrost** [comment]
This has been merged.
