### ISSUE TITLE
Store AES and RSA encoded output in db

### ISSUE THREAD

**Issue by nimasdj** [phpseclib/phpseclib#909]
Hi,
How is the best way to store AES and RSA encoded output in db? I was thinking of base64_encode with str_replace to remove trailing == but I am wondering if you suggest any better way?

**Comment by terrafrost** [comment]
That should work. Altho removing the trailing == could cause `base64_decode()` to fail.

That said, I'm not completely sure what you'll be doing with your crypto. Typically, you want to some sort of authentication with an HMAC as well. Some algorithms have do both but phpseclib does not currently implement those algorithms. In lieu of that you can do separate encryption / authentication. Wikipedia provides a discussion of the various approaches here:

https://en.wikipedia.org/wiki/Authenticated_encryption#Approaches_to_Authenticated_Encryption

SSH does Encrypt-and-Mac but Encrypt-then-Mac is supposed to be the best.

Anyway, if you have more general crypto questions along these lines you'd probably be better off posting at http://crypto.stackexchange.com/ . I can help you out if you have phpseclib-specific questions but for more general questions...  you can get answers from a wider array of people over there. So like instead of having to wait 6h for me to reply you might get a reply over there in like 30 minutes.
