### ISSUE TITLE
2.0 branch, catch(Exception) was not updated to work in namespace

### ISSUE THREAD

**Issue by oxygens** [phpseclib/phpseclib#949]
At least in RSA.php catch statements are ignored (PHP automatically ignores/skips catch statements with undefined exception classes) because Exception is not defined in the current namespace.

**Easy fix**: import at file top.
`use \Exception`
This is not good going forward, as using Exception would be a better fit for a future "Exception" class in of the current namespace.

**Suggested fix:**
Add the namespace root to all Exception usages. `catch(\Exception $exception)`.

This will also make the code more readable, immediately making it clear that all exceptions types are caught.

**Comment by terrafrost** [comment]
Good "catch" lol.

It's been fixed with https://github.com/phpseclib/phpseclib/commit/698efd030a1a794fceba78eed4113fb5daa17bcc . Thanks!

**Comment by oxygens** [comment]
One more problem with these `catch(\Exception)`s.

Where the intention is to catch any error, in PHP 7 you might want `catch(\Throwable $error)` and not \Exception.

**Comment by khelle** [comment]
I believe it is much better to catch \Error then \Exception instead of \Throwable then \Exception, and heres why:

```
try {
   // code
} catch (\Throwable) {
   // will catch both Error and Exception in PHP7
   // will catch nothing in PHP5
} catch (\Exception) {
   // will catch Exception in PHP5
}
```

```
try {
   // code
} catch (\Error) {
   // will catch error in PHP7
} catch (\Exception) {
   // will catch Exception in PHP5 and PHP7
}
```

This means, that the second option with \Error and \Exception will create separate catch block for Errors, and leave shared block for Exception regardless on PHP version. It will divide catch blocks per throwable type. It is much more logical than using Throwable then Exception and divide catching mechanism per PHP version.
