### ISSUE TITLE
SFTP class login with no password ?

### ISSUE THREAD

**Issue by ZiperRom1** [phpseclib/phpseclib#961]
The SFTP class has a login method with no password in parameters but a password in var comment phpDoc ...

``` PHP
`/**
     * Login
     *
     * @param string $username
     * @param string $password
     * @return bool
     * @access public
     */
    function login($username)
    { //...
```

Weird and unusable. About 1000 stars project with `var` keyword in class attributes declaration. My linter is crying at about every lines of code lol.

**Comment by terrafrost** [comment]
Maybe you should look like 5 lines down. eg.

```php
    function login($username)
    {
        $args = func_get_args();
        if (!call_user_func_array(array(&$this, '_login'), $args)) {
            return false;
        }
```

It's doing `func_get_args()`. Maybe you should look that up in the PHP manual. Might learn a thing or two.

As for the use of the `var` keyword...  phpseclib was written back in 2007, back when PHP4 dominated hosts. The 1.0 branch is BC with the original release. New features have been added, sure, but 1.0 will work on the same versions of PHP as phpseclib's initial release back in the PHP4 heyday.

The 2.0 and master branches are not PHP4 compatible, owing to their use of namespaces, among other things, but they still use the var keyword all the same. They could use public but public and var do basically the same thing. There is an on-going RFC for 7.1 for deprecating var in that version and removing it in 8.0. Whether or not it'll pass is an open question. But, to quote that RFC,

> var is currently a simple alias for public.

Here's the link:

https://wiki.php.net/rfc/var_deprecation

But that said, I have no intention of making variables private or protected. private prevents child classes from utilizing variables, so there's that. But also the SCP class accesses "private" variables from both the SSH1 and SSH2 classes. Maybe in your mind that means phpseclib is crap and you're certainly entitled to think that. And if you think it's such crap do feel free to write your own alternative implementations to everything that phpseclib does.

In the mean time I'm going to create a new tag just for this ticket. Troll.

Thank you for your "issue". Have a nice day.

**Comment by terrafrost** [comment]
If in the event that you aren't trolling I apologize for my response. But your post really does read to me like that of a troll.

**Comment by terrafrost** [comment]
Oh - and, also, login() technically takes between 1 and infinite parameters. Check out the documentation:

http://phpseclib.sourceforge.net/ssh/auth.html

"No Authentication" takes one parameter - the username - and that's it:

http://phpseclib.sourceforge.net/ssh/auth.html#noauth,

The example for multi-factor authentication has three parameters but you could technically have there be an 10, 20, 30 parameters, it doesn't matter:

http://phpseclib.sourceforge.net/ssh/auth.html#multifactor,

Given the dynamic range of input it is not clear to me what a proper phpDoc block for that method would look like.

**Comment by ZiperRom1** [comment]
Well I was tired last night after a day of coding. I didn't look for the `_login ` function in the parent class because the obsolete use of "_" in attributes / methods meant that it is a private one.
I may hurt your feeling with my last comment but going into your source hurt mine.
While the PHP 7 is released, seeing a lib updated few day ago with a PHP 4 style which broke many coding rules standards and design patterns. Like preferring annotate @access in phpDocBlock instead of simply put the visibility behind the method name; 150 + lines method; camel case, anti-pattern, etc.
Sorry for complaining I must be a douchbag, I get out of here.
Have a nice day.

**Comment by terrafrost** [comment]
>  I didn't look for the _login function in the parent class 

You obviously didn't see `call_user_func_array` either. Let alone even test it out. Typically end users ought not even be looking at the source code. In-so-far as they are concerned the implementation details are a black box. Except with you, where all you look at is the source code, and you do a half assed job, too.

> broke many coding rules standards

That's true - it does do that. But do keep in mind, as I said, that the 1.0 version was released in 4.0's heyday and to maintain BC with itself still works on 4.0. But I guess BC isn't something you give a shit about. Following your advice I guess everyone who installed phpseclib with `composer require phpseclib/phpseclib:~1.0` will have a broken product when 1.0.2 is released. But that's okay because at least ZiperRom1 will feel good about the universe!

> Like preferring annotate @access in phpDocBlock instead of simply put the visibility behind the method name

I have already addressed this several times. Clearly reading comprehension is not a strong suit of yours. I suggest you go back to grade school. But I will add one other thing - the **@access** docblock comment affects what methods show up when you're building the documentation from the comments. By default private methods do not show up when you're building the documentation whereas public methods do. So by doing **@access private** on a public function that public function is basically being hidden from the default phpdoc parameters. And as I said earlier, the SCP class, for example, calls "private" methods. Making them "public" in the docblock comments might lead to other people using those methods when they're not intended for general use. The SCP class is internal to phpseclib so it's kinda private within the scope of phpseclib but not private within the scope of the class or it's inheriting classes (SCP doesn't extend SSH1 or SSH2).

idk that the design utilized is the best possible design but then again "best" is subjective. If you or anyone else has an idea for a "better" API for SCP (or anything else) feel free to mention it and it'll be considered. Obviously not in the 1.0 or 2.0 branches, to maintain BC, but in the master branch.

**Comment by terrafrost** [comment]
A few other things too.

Sometimes when people have asked for help with phpseclib and have suggested that it wasn't connecting to their server I've basically debugged by proxy, which may consist of, among other things, calling private methods. ie. "maybe calling this method will do the trick" or "maybe calling this 'private' method will give me more info with which I can make a diagnostics". If I had to have people alter the code to adjust the visibility as well...  that'd be one extra hoop people would have to jump through and one thing I've learned...  the more hoops you ask people to jump through the less likely they are to do something.

Also, sometimes if phpseclib hasn't done something someone needs I've given them workarounds in the form of "you can call these 'private' methods to do what you want until official support for what you're wanting to do is added". In-so-far as I am concerned these pseudo-private methods are fair game for being changed (backwards compatibility isn't something I'm concerned about for pseudo-private methods / variables) but if you need a solution now, can live with the fact that newer versions of phpseclib may break what you're doing, and can't wait x months or however long it takes for me to do another release...  well phpseclib may still be able to accommodate you.

Overall, I think private / protected solve a problem that was never really a problem to begin with. I've never seen anyone use "private" methods without explicitly being told to do so. So although using them may be considered "best practices" it also hinders my ability to provide support. And for what? So people like you can feel good about themselves?

Another thing to consider...  as I said, the 1.0 API was designed back in PHP4's heyday. It was designed with what I perceived to be the "PHP Way". But the "PHP Way" is changing. Back then the "PHP Way" was to silently fail and mangle invalid data to be valid without throwing exceptions or anything (not that PHP4 even supported exceptions). A lot of this has changed in the master branch. If you pass keys or IV's that are too short you'll get exceptions.

The "PHP Way" is changing but the versioned branches of phpseclib can't change with it for reasons of BC. The master branch can but that's the only one.

And as for camel case...  how about you go file a bug report with PHP and ask them to change the `DOMDocument` API. That's completely camel case:

http://php.net/manual/en/book.dom.php

And I'm sure they'd be willing to break BC with every version of PHP since PHP 5.0 just because **you** said so. It may screw over millions of PHP users and make them never update again but that's all okay because ZiperRom1 said so!

**Comment by raxbg** [comment]
It is none of my business to post here, but this is awesome! I hate trolls so much...but I can never express my anger so well :D @terrafrost thank you!

**Comment by ZiperRom1** [comment]
![troll](http://www.reactiongifs.com/wp-content/uploads/2013/01/interesting.gif?raw=true)

**Comment by terrafrost** [comment]
Oh - something else too.

> 150 + lines method

In-so-far as I'm concerned a method ought to be created when not doing so would result in duplicated code. Per that there's no point to creating an internal method (or a whole new object) if you're only going to use it once.

The thing is...  if you create a library and make it excessively object oriented with an excessive number of methods then that makes it harder to trace the code to understand what it's doing.

I'll give an example.

I used to do code reviews for phpBB modifications. And one modification I saw tried to abstract away string concatenation. It's an operation that you can do with a simple primitive but they abstracted it away. They used an object (defined in one file) that used a constructor and that extended another object (defined in another file). The method that they were using to do string concatenation also called a function in a third file. So I had to look in three different files and in four different places to understand that all the code was doing was string concatenation.

If you're goal is to obfusticate code and make it as difficult as possible for people to figure out what it is that you're doing, then yah, creating thousands of methods is a good thing. But if your goal is to actually write software that people can understand you don't do that.

Some developers feel that they need to pigeonhole themselves into design patterns and other "best" practices while forgetting that a library also needs to be easy and intuitive to use and to maintain. Admittedly what qualifies as "easy" and "intuitive" is subjective, but none-the-less, if you think you can do better, I invite you to do so. Competition is never a bad thing. But I guess that would be too much effort for a troll.

**Comment by ZiperRom1** [comment]
I personally concatenate strings with a dot. Thanks for this awesome example. You should tell to the developers community that they should stop to use oriented object programming style.
You seem better to write than to code, consider changing your job as a community manager to answer all the troll on Facebook or Twitter.
Have a good night ;p
