### ISSUE TITLE
What causes dramatically slow RSA key generation?

### ISSUE THREAD

**Issue by DavidAnderson684** [phpseclib/phpseclib#963]
I'm the lead developer of a WP plugin with a lot of users (700k). Only a small minority use the features that invoke phpseclib. When they do, this involves generating a 2048-bit RSA key pair.

Normally, this takes a second or two - which is what always happens in my testing.

However, for some, it takes around a minute. For some of them, this times out completely, as they have a web host that limits PHP execution time, or a gateway/proxy with a timeout.

Do you have any insight into what could cause this, and any possibilities to resolve it? I've tried some Googling, without success. With those who've been in our support channel with this issue, we've advised workarounds that avoid the use of phpseclib entirely, or, switching their PHP version in their web hosting control panel. Those who've tried switching their PHP version have found success (i.e. back to a couple of seconds). Does this give any clues?

**Comment by bantu** [comment]
There are multiple BigInteger backends phpseclib can use. GMP being the
fastest, bcmath an alternative and the native php implementation the
slowest.

Try to find out which of those two php modules are available to your users
in slow/fast cases.

**Comment by DavidAnderson684** [comment]
Thank you.... that makes sense - when an error has been reported, the PHP execution time has expired whilst in Math/BigInteger.php

Looks like I can do some testing via defining MATH_BIGINTEGER_MODE.

When I find out what PHP modules they have available - presumably then it's just a matter of telling them "install this PHP module"? i.e. it's unlikely to be the case that they're using anything other than the native PHP implementation, if it's taking a minute?

**Comment by DavidAnderson684** [comment]
OK, here's what I've discovered.

It's setting MATH_BIGINTEGER_OPENSSL_DISABLE that's the killer. Without that, all values of MATH_BIGINTEGER_MODE give me a key in under 1 second.

With MATH_BIGINTEGER_OPENSSL_DISABLE, MATH_BIGINTEGER_MODE_GMP is still fast.

But, MATH_BIGINTEGER_MODE_BCMATH is > 100 seconds, and MATH_BIGINTEGER_MODE_INTERNAL is > 600 seconds.

These timings are for generating a 2048-bit RSA key-pair (new Crypt_RSA()->createKey(2048)), on my everyday laptop (4 years old, Pentium).

So, the availability of whatever bits of OpenSSL are being used are the main factor.

Any thoughts?

**Comment by terrafrost** [comment]
It's actually fastest with GMP. GMP is even faster than OpenSSL, per this:

http://phpseclib.sourceforge.net/math/intro.html

Newer versions of PHP are also quite a bit faster as well.

One thing to keep in mind is that those benchmarks for encryption / decryption - not for key generation. Key generation is just...  expensive.

A few things you could do...  you could try to do `exec('ssh-keygen -t rsa')` if exec is available and if the ssh-keygen command exists and fallback to phpseclib otherwise. phpseclib doesn't do that because idk I just don't like CLI calls.

You could also try to kinda scale down depending on what's available. eg. do 1024-bit keys for PHP 5.5 without OpenSSL or GMP. Or do multi-prime RSA keys as well, which you can do by doing `define('CRYPT_RSA_SMALLEST_PRIME', 256)` or some such. This'll speed up key generation but it'll also reduce the security of the key. ie. a 4-prime 2048-bit key has about the same security as a 2-prime 1024-bit key. Actually, it may have /slightly/ more security but you're not getting the security you might be expecting all the same.

You could also do successive calls to `$rsa->createKey(2048, 30)`. On the initial call you'd do `$rsa->createKey(2048, 30)` and you'd get the output. eg. `$result['partial']`. On subsequent calls you'd do `$rsa->createKey(2048, 30, $result['partial'])`. You could use this to do a bunch of calls in succession via AJAX. In theory I guess you could have the browser work on generating primes concurrent with the server but idk.

**Comment by terrafrost** [comment]
Oh, also, since you're doing Wordpress plugins, maybe you could take over my SSH SFTP plugin! I don't really provide support for it or make any real updates to it or anything. I think it's a useful plugin and I think lots of people have found it useful but I just...  I just don't care that much about it. I don't devote as much time to phpseclib as I'd like and trying to maintain and support that plugin would mean even /less/ time for phpseclib.

**Comment by DavidAnderson684** [comment]
Hi,

Thanks for the various tips. I ended up "solving" it by putting a "key size" option into the user interface. That way, users both have a solution, and get to "own" the problem, in the sense of making a choice based on the strength/speed/PHP-duff-install trade-offs involved.

Regarding the WP plugin, I think I'm not the right person for that; I wouldn't have any skin in the game, as I don't have any sites needing it, so I'd be likely to let it rot too.... I've already got a few plugins that are just a "community service", and, as with you, it's hard to keep keeping up and I often wonder about handing them over. You can tag your plugin to alert potentially interested people that you're interested in someone taking it over: http://wptavern.com/adopt-me-plugin-tag-is-now-in-use-on-wordpress-org

David
