### ISSUE TITLE
Login failing due to timeout

### ISSUE THREAD

**Issue by Parcye** [phpseclib/phpseclib#989]
When I try to login, it failes due to a timeout. But if I remove the `return false` on line 1065 in SSH2.php it continues and I end up in a connection that seems to take an age... for example:

Set script-timeout I get messages on the follow lines : 
30secs timeout phpseclib/Net/SSH2.php on line 3420
60secs timeout phpseclib/Net/SSH2.php on line 3550
120secs timeout phpseclib/Net/SSH2.php on line 3398
180secs timeout phpseclib/Net/SSH2.php on line 3433

Thus it is not stuck in any loop... just doesn't seem to get the answer it needs .

On my Synology it works like a charm... big difference : OpenSSL version. 

What could the issue be? I have it working fine locally and now want to push it to a online project.

`if (!@stream_select($read, $write, $except, $sec, $usec) && !count($read))`  is where it starts going wrong and after this timeout `$this->fsock` is still alive.

**Comment by Parcye** [comment]
Running PHP from shell, without Apache, it works fine.

**Comment by terrafrost** [comment]
I don't know what version of phpseclib you're using. It's not 2.0.1 or 1.0.2 since those versions don't have a `return false` on that line:

https://github.com/phpseclib/phpseclib/blob/2.0.1/phpseclib/Net/SSH2.php#L1065
https://github.com/phpseclib/phpseclib/blob/1.0.2/phpseclib/Net/SSH2.php#L1065

It's not 1.0.1 either...

https://github.com/phpseclib/phpseclib/blob/1.0.1/phpseclib/Net/SSH2.php#L1065

That said I'm gonna assume that the issue you're having is in the `_connect` method.

Something you could do that'd give me a little more insight into what's going on (these are for the 1.0.2 version - they may work on other versions depending on what version you're running)...

```php
#
#-----[ OPEN ]------------------------------------------
#
Net/SSH2.php
#
#-----[ FIND ]------------------------------------------
#
        while (!feof($this->fsock) && !preg_match('#^SSH-(\d\.\d+)#', $temp, $matches)) {
            if (substr($temp, -2) == "\r\n") {
                $extra.= $temp;
                $temp = '';
            }
#
#-----[ AFTER, ADD ]------------------------------------
#
            if (!isset($i)) $i = 0;
            echo "$i. $temp<br />\r\n";
            $i++;
#
#-----[ FIND ]------------------------------------------
#
                if (!@stream_select($read, $write, $except, $sec, $usec) && !count($read)) {
                    $this->is_timeout = true;
                    return false;
                }
#
#-----[ REPLACE WITH ]----------------------------------
#
                if (!stream_select($read, $write, $except, $sec, $usec) && !count($read)) {
echo "read = " . count($read) . "<br />\n";
echo "write = " . count($write) . "<br />\n";
echo "except = " . count($except) . "<br />\n";
echo "sec = $sec<br />\n";
echo "usec = $usec<br />\n";
                    $this->is_timeout = true;
                    return false;
                }
```

Another possibility... maybe try to use this branch:

https://github.com/terrafrost/phpseclib/tree/stream-get-contents-1.0

It still does `stream_select` but it's not doing it with `fgets()` or `fread()` - it's doing it with `stream_get_contents()` and `stream_get_line()`. That branch is branched from the 1.0 branch, as well, and not the 2.0 branch (I don't know which version you're using).
